### ISSUE TITLE
[8.2.0 PTR] EditBox Broken

### ISSUE THREAD

**Issue by Stanzilla** [Stanzilla/WoWUIBugs#1]
**Describe the bug**
When selecting multiple characters with the mouse, or with shift+keyboard arrows, it highlights characters on the next line.

![img](https://i.imgur.com/k5crkT6.gif)

![img](https://i.imgur.com/FXe6132.gif)

Verifiable Example:
[EditBoxBugTest.zip](https://github.com/WeakAuras/WeakAuras2/files/3098189/EditBoxBugTest.zip)

Refs: https://github.com/WeakAuras/WeakAuras2/issues/1290

**Comment by Stanzilla** [comment]
`[18:27:32] TSquare: @Stanzilla - we have a bug in for it, unfortunately it won't be fixed in this patch`

**Comment by Stanzilla** [comment]
Ref ElvUI ticket https://git.tukui.org/elvui/elvui/issues/101

**Comment by Meorawr** [comment]
Still present as of the first PTR 8.2.5 build (31337).

**Comment by Nevcairiel** [comment]
This issue is fixed on the 8.3 PTR, btw, in case anyone is following this.

**Comment by Meorawr** [comment]
As 8.3 has been released I think we can close this (assuming it didn't unfix itself).
