### ISSUE TITLE
9.1: Conduit list is now created repeatedly

### ISSUE THREAD

**Issue by siweia** [Stanzilla/WoWUIBugs#102]
Each time you open the SoulbindViewer frame, blizzard seems to throw the old conduit list away and recreate a new one.
Not sure it is intentionally or just a bug.
By using cmd /fstack, we can tell that the debug name for each header and conduit button changed.
`SoulbindViewer.ConduitList.ScrollBox.ScrollTarget:GetNumChildren()` is increased by 3 on each time.

**Comment by Meorawr** [comment]
Should be fixed in an upcoming (but probably not next) build.

**Comment by Meorawr** [comment]
Should be fixed as of 9.1.0.38394.
