### ISSUE TITLE
TBC: IsQuestFlaggedCompleted missing in build 38364

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#103]
As this'll probably trip a few people up, 2.5.1.38364 is missing the IsQuestFlaggedCompleted API both as a global function and namespaced inside C_QuestLog. This isn't intentional and should be corrected in a future build, wherein it _should_ find itself successfully relocated to its new home within the C_QuestLog namespace.

**Comment by Aviana** [comment]
![image](https://user-images.githubusercontent.com/425023/115992621-e217f900-a5ce-11eb-8ce4-4bb7ea04b15c.png)
Build 38401

**Comment by Meorawr** [comment]
Yeah, forgot to close it after the latest build - thanks.
