### ISSUE TITLE
[8.2.0 PTR] Hyperlink + SimpleHTML crash

### ISSUE THREAD

**Issue by ls-** [Stanzilla/WoWUIBugs#11]
Setting `SimpleHTML`'s text to a string with a lot of hyperlinks and mousing over hyperlinks closer to the end of the list results in this crash:

![](https://i.imgur.com/LKXSKx8.png)

Reproduction:

![](https://i.imgur.com/KFMJjhL.gif)
 
Code: https://gist.github.com/ls-/2df20f4693c0346782d30cace07b26d6

**Comment by Meorawr** [comment]
Testing with Total RP 3, I've noticed that the 128th through 192nd hyperlinks inside a SimpleHTML frame will consistently crash the client. Anything outside that range (before and after) works fine - I've tested up to 257 or so.

What's interesting is your capture shows it crashing on the 111th hyperlink, so I'm not sure if that's just your crash somehow being slow. When using your test case it'll obey the same range I've noticed with TRP3 and crash on anything after/including the 128th link (the right-side Worthy Champions one onwards).

**Comment by ls-** [comment]
Good catch.

I think the crash in the gif is caused by the 131st (bottom left ) hyperlink, there's just some kind of lag, for example, if I mouse over the last/132nd hyperlink and just wait a bit, the client will crash.

**Comment by Meorawr** [comment]
Did a bit more investigating, this time with 1024 hyperlinks. From the bottom:

- Links #1024 to 914 work.
- 913 to 911 crash.
- 910 to 784 work.
- 783 to 781 crash.
- 780 to 654 work.
- 653 to 651 crash.
- 650 to 524 work.
- 523 to 521 crash.
- 520 works, but I couldn't test how far this "working" range extends as the PTR servers got shut down. 

I'm assuming that the 128 to 196 range is still broken in this test case, but I won't be able to test that for a while.

**Comment by Meorawr** [comment]
Seems to be fixed as of build 30669 (both the original test case and my ridiculous 1024 link one).

**Comment by ls-** [comment]
\o/
