### ISSUE TITLE
Hardware event requirements for critical functions

### ISSUE THREAD

**Issue by Stanzilla** [Stanzilla/WoWUIBugs#110]
There currently is a inconsistency in hardware event restricted functions across the three WoW flavors, BC and Vanilla are lacking some protections that make scamming or griefing via addons possible that should be backported from Retail.

Examples but not all of them:
- DeleteCursorItem()

**Comment by Meorawr** [comment]
DeleteCursorItem was hardware protected in 2.5.1.38521 or some build thereabouts; as that's the only one offered on the list do we want to close this?

**Comment by Meorawr** [comment]
I'll close this as the one example was fixed ages ago.
