### ISSUE TITLE
TBC: Dump.lua not loaded by Frame/GlueXML TOC

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#115]
The latest 2.5.1.38521 build relocates Dump.lua from Blizzard_DevTools to SharedXML, however neither FrameXML.toc nor GlueXML.toc have been told to load the script - as a result the `/dump` command doesn't work.

**Comment by QartemisT** [comment]
This is being hotfixed now;

KirbyAu — Today at 00:17
Was on lunch but dump should be fixed
If not now, it will be soon

**Comment by Meorawr** [comment]
I guess we can all look forward to getting `/dump`-ed soon then.

**Comment by Ketho** [comment]
[Fixed](https://github.com/Gethe/wow-ui-source/commit/af7dd149cb76bbee50ad76a7cd6f048df35b87d1#diff-dac3c6d947dc39bc645bdf81056c21b4ad8c93bdbe7946ce60012fcd92dd90c2R44) in 2.5.1 (38548)
