### ISSUE TITLE
Default keybindings get unbound after a /reload

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#12]
When defining a default keybind in the XML it will become unbound after reloading. But it's set again after relogging.

- Reproduced on: Live 8.1.5 (29981), PTR 8.2.0 (30430)
- Video: https://streamable.com/l7grk

**DefaultKeybind.toc**
```xml
## Interface: 80100
## Version: 1.0
## Title: DefaultKeybind

Bindings.xml
```

**Bindings.xml**
```xml
<Bindings>
	<Binding name="Test Keybind" category="Test" default="F7">
		print("Keybind Test")
	</Binding>
</Bindings>
```

**Comment by mooreatv** [comment]
is there a workaround ? like calling the right LoadBindings()

**Comment by stianhoiland** [comment]
Issue also present in Classic 1.13.2 (31882)

**Comment by cocovanana** [comment]
> is there a workaround ? like calling the right LoadBindings()

For me it worked to save the current keybinding in savedvariables, and then use the SetOverrideBinding on a custom binding, so it replaces the one the user had.

**Comment by Ketho** [comment]
Fixed on Beta
