### ISSUE TITLE
TBC: SetTexture filterMode "TRILINEAR" crashing client

### ISSUE THREAD

**Issue by andycoates** [Stanzilla/WoWUIBugs#120]
Sent a few game crash reports but logging it here too in case its somehow only affecting me...

In the current TBC beta build (2.5.1 38537 Apr 30 2021), calling `SetTexture` (https://wowpedia.fandom.com/wiki/API_Texture_SetTexture) with a `filterMode` value of `TRILINEAR` will crash the client.  This doesn't happen in live Classic/Retail.

Repeatable for me - example using the Peacebloom texture ID:
`/run i = CreateFrame("FRAME"); t = i:CreateTexture(nil,"BACKGROUND"); t:SetTexture(133939, "CLAMPTOBLACKADDITIVE", nil, "TRILINEAR")`

**Comment by Meorawr** [comment]
This triggers an assertion in test builds in general (as tested on the retail PTR) it seems, so it's unlikely this would crash a release build of the BC client.

Generally speaking the client crash reporter is the preferred mechanism for reporting these types of issues, and as long as the crash reports contain the relevant instructions they'll triage them as needed based on their own metrics. A link to issues here can help too.

For the sake of not confusing matters by reporting the same issue to Blizzard through multiple channels both here and via crash reports, and as this doesn't feel like an issue that's particularly high impact, I'll close this _for now_ unless the issue manifests on a release client *or* if more people start running into this issue.

**Comment by andycoates** [comment]
Yep all good - I honestly wasn't sure if it was just something related to my client (as I had the original classic beta still and it updated that, I thought maybe some data/setting got mixed up somewhere and might be only causing it for me), so good to at least know its not just me (didn't think of testing PTR).  I don't recall this happening in the original Classic beta though (unless that wasn't classed as a test build).. either way thanks for insight into assertions - sort of makes sense now I think about it.
