### ISSUE TITLE
TBC: ArenaFrame and BattlefieldFrame both show when queue for arena

### ISSUE THREAD

**Issue by siweia** [Stanzilla/WoWUIBugs#121]
Not sure whether it is intentional, and press key ESC won't close the ArenaFrame.
If you set this two frames movable, you can tell that they are actually coincide, and press escape only shut down the BattlefieldFrame.

Before drag:
![p1](https://user-images.githubusercontent.com/1502922/116982294-31f76e00-acfb-11eb-8f1f-95cbe57d9a70.png)

After drag:
![p2](https://user-images.githubusercontent.com/1502922/116982301-33c13180-acfb-11eb-9311-53a3faa77567.png)

After press escape:
![P3](https://user-images.githubusercontent.com/1502922/116982792-d7124680-acfb-11eb-907e-4964e8e68ead.png)

**Comment by Meorawr** [comment]
Looking at the diff I _think_ this is fixed in 2.5.1.38561 which is currently on the submission branch. That build or a newer one should hit beta servers soon-ish.

**Comment by siweia** [comment]
Although they are not opened in the same time at patch 38589, but label on ArenaFrame is still anchor to BattlefieldFrame.
![QQ截图20210509182447](https://user-images.githubusercontent.com/1502922/117568611-d7dc1b80-b0f3-11eb-944e-8da1e60e3404.png)
