### ISSUE TITLE
Classic: ManifestInterfaceData not updated for ScrollBox additions

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#125]
Classic build 1.13.7.38631 was recently released with a backport of ScrollBox, various FrameXML utilities, and the new event trace tool present on the BC and Retail (PTR) clients. The update however failed to include an updated ManifestInterfaceData client database, which means that none of the newly added files can be exported via the `exportinterfacefiles` command.

The table of changes needed is below; "Added" means this file was added in the build and is missing from the database, "Removed" means the file was removed and doesn't need to remain in there.

| Status  | File ID | File Path |
| ------  | ------: | :-------- |
| Added   | 2747253 | interface/sharedxml/timeutil.lua |
| Added   | 3046538 | interface/auctionframe/auctionhouse.blp |
| Added   | 3183835 | interface/sharedxml/dropdowntogglebutton.lua |
| Added   | 3183837 | interface/sharedxml/dropdowntogglebutton.xml |
| Added   | 3196369 | interface/sharedxml/globalcallbackregistry.lua |
| Added   | 3492904 | interface/sharedxml/callbackregistry.lua |
| Added   | 3492916 | interface/sharedxml/functionutil.lua |
| Added   | 3492920 | interface/sharedxml/tableutil.lua |
| Added   | 3492922 | interface/sharedxml/textureutil.lua |
| Added   | 3492924 | interface/sharedxml/mathutil.lua |
| Added   | 3512232 | interface/sharedxml/anchorutil.lua |
| Added   | 3513315 | interface/sharedxml/animationtemplates.xml |
| Added   | 3513317 | interface/sharedxml/animationtemplates.lua |
| Added   | 3934544 | interface/sharedxml/dataprovider.lua |
| Added   | 3934546 | interface/sharedxml/interpolator.lua |
| Added   | 4008100 | interface/buttons/scrollbarproportionalvertical.blp |
| Added   | 4032003 | interface/buttons/scrollbarproportional.blp |
| Added   | 4033725 | interface/buttons/scrollbarproportionalhorizontal.blp |
| Added   | 4082172 | interface/sharedxml/scroll/scrollboxview.lua |
| Added   | 4082173 | interface/sharedxml/scroll/scrollboxgridview.lua |
| Added   | 4082175 | interface/sharedxml/scroll/scrollutil.lua |
| Added   | 4082178 | interface/sharedxml/frame/eventeditbox.lua |
| Added   | 4082180 | interface/sharedxml/scroll/scrollbox.xml |
| Added   | 4082182 | interface/sharedxml/frame/eventbutton.lua |
| Added   | 4082185 | interface/sharedxml/scroll/scrolltemplates.lua |
| Added   | 4082187 | interface/sharedxml/frame/eventframe.xml |
| Added   | 4082190 | interface/sharedxml/frame/eventframe.lua |
| Added   | 4082191 | interface/sharedxml/scroll/scrollbar.xml |
| Added   | 4082192 | interface/sharedxml/scroll/scrollbar.lua |
| Added   | 4082193 | interface/sharedxml/scroll/scrollcontroller.lua |
| Added   | 4082195 | interface/sharedxml/scroll/scrollbox.lua |
| Added   | 4082196 | interface/sharedxml/frame/eventbutton.xml |
| Added   | 4082197 | interface/sharedxml/scroll/scrollboxlinearview.lua |
| Added   | 4082198 | interface/sharedxml/frame/eventeditbox.xml |
| Added   | 4082199 | interface/sharedxml/scroll/scrolltemplates.xml |
| Added   | 4094487 | interface/sharedxml/enumutil.lua |
| Removed | 2168459 | interface/sharedxml/anchor.lua |
| Removed | 2168463 | interface/sharedxml/anchorutil.xml |

**Comment by Ketho** [comment]
Just want to say I can confirm this in the 1.13.7 (38704) build since it makes it troublesome to dump the api

**Comment by Meorawr** [comment]
This is implicitly resolved in 1.14.0.
