### ISSUE TITLE
BCC: GetAuctionItemInfo("list", i) stopped ever returning owner, ownerFullName

### ISSUE THREAD

**Issue by mooreatv** [Stanzilla/WoWUIBugs#127]
The code that worked fine in Classic: 

- Start a scan using `QueryAuctionItems("", nil, nil, 0, 0, 0, true)`
- Query items using
```lua
         local _name, _texture, itemCount, _quality, _canUse, _level, _levelColHeader, minBid, minIncrement,
                buyoutPrice, bidAmount, highBidder, _bidderFullName, owner, ownerFullName, _saleStatus, _itemId,
                _hasAllInfo = GetAuctionItemInfo("list", j)
```
yield / reenter event loop if owner and ownerFullName are both nil

In Classic:
At most 2-3 reenter were needed to obtain the seller information

In Classic era:
Still works fine

In Burning crusade classic:
Even waiting indefinitely the information never populates

(full code : https://www.curseforge.com/wow/addons/auction-house-database  )

**Comment by Ketho** [comment]
Might have been carried over from the `C_AuctionHouse.GetReplicateItemInfo` hotfix where `owner` and `ownerFullName` now always return nil to stop people from disconnecting

**Comment by mooreatv** [comment]
noone got disconnected on classic so not sure how that relates - did someone at blizzard say they don't plan on fixing / why are we closing bugs?

By the way I just tested despite the AH hotfix this is still an issue
(I was wondering if the issue is maybe layers related (seller in another layer))

**Comment by mooreatv** [comment]
This bug has now also unfortunately propagated to Classic (1.14 was working fine in 1.13)

had to do
https://github.com/mooreatv/AuctionDB/commit/cdef14780f83518b454efda455a7e904b7c5fadd#diff-7fcb016d6306e40cbd3ea4acb04b243d86906d369eb817e9eec5b5cd58f204f4R293-R294
earlier but I guess now need to forget about sellers entirely until / if ever this gets fixed
