### ISSUE TITLE
All equipment, items and bags can be deleted instantly

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#13]
It's possible to delete all gear, items and bags with a single script. This does not require a hardware event and was disclosed to the #wowuidev IRC on August 9th, 2018.

- Reproduced on: Live 8.1.5 (30706), PTR 8.2.0 (30774)
- Videos: https://streamable.com/d91sf, https://streamable.com/fwa4j

```lua
function DeleteEverything()
	for bag = 0, NUM_BAG_SLOTS do
		for slot = 1, GetContainerNumSlots(bag) do
			PickupContainerItem(bag, slot)
			DeleteCursorItem()
		end
	end
	for invSlot = 0, 23 do
		PickupInventoryItem(invSlot)
		DeleteCursorItem()
	end
end

```

**Comment by Meorawr** [comment]
DeleteCursorItem now requires a hardware event as of build 9.0.2.36206.

**Comment by Ketho** [comment]
Still a bit dangerous that a single hardware event is still enough to delete all items together, but better than nothing

**Comment by Walkerbo** [comment]
This change broke my addon Aardvark.
One of the main features was you could manually add items to a destroy list and when you visited a vendor all those listed items would be destroyed.
It was not a problem and this change sucks.

**Comment by Ketho** [comment]
They're not going to revert
