### ISSUE TITLE
[BCC] Quest API Consistency

### ISSUE THREAD

**Issue by orionshock** [Stanzilla/WoWUIBugs#130]
Requesting some consistancy and parity with the Quest API
For Gossip we have : 
[GetGossipAvailableQuests](https://wowpedia.fandom.com/wiki/API_GetGossipAvailableQuests?redirect=no)
[GetGossipActiveQuests](https://wowpedia.fandom.com/wiki/API_GetGossipActiveQuests?redirect=no)
Notably these 2 APIs provide the questID.

However for non-gossip interactions with NPCs, ones that do not trigger a "GOSSIP_SHOW" but instead a "QUEST_GREETING", the only API we have is GetAvailableTitle. This API dosn't give the questID like the Gossip ones do. Listed on the wiki there is a [GetAvailableQuestInfo](https://wowpedia.fandom.com/wiki/API_GetAvailableQuestInfo) in retail, but dosn't seem to be available in BCC or Classic Era.

Can we back port the GetAvailableQuestInfo API for BCC ?

**Comment by Meorawr** [comment]
A request for Blizzard to synchronize the `C_GossipInfo` APIs to BCC (which includes [C_GossipInfo.GetAvailableQuests](https://wowpedia.fandom.com/wiki/API_C_GossipInfo.GetAvailableQuests)) has already been submitted, so I'll close this for now to avoid duplicating it.
