### ISSUE TITLE
BCC joining battleground taint

### ISSUE THREAD

**Issue by mrbuds** [Stanzilla/WoWUIBugs#140]
StaticPopup shown for joing battleground can still be bricked by addons in BCC

Screenshot:
![TransparentTwitchChatWPF_2021-06-19_19-05-11](https://user-images.githubusercontent.com/189656/122650128-7450ff00-d131-11eb-8d3d-c54ce9a2db53.png)

Taintlog: 

[taint - Copy (3).zip](https://github.com/Stanzilla/WoWUIBugs/files/6681074/taint.-.Copy.3.zip)

**Comment by mrbuds** [comment]
It does not seem to be fixed on PTR 2.5.2.39618, i wished something was done about it, this happen for arenas too where you have only 30s to get in, people lose games because they click a bit late and a required to /reload.

**Comment by Meorawr** [comment]
This is _possibly_ fixed in 2.5.2.40011. Need someone to test and confirm.
