### ISSUE TITLE
Deprecation wrapper for C_TransmogCollection.SetShowMissingSourceInItemTooltips errors

### ISSUE THREAD

**Issue by kemayo** [Stanzilla/WoWUIBugs#142]
The deprecation wrapper in `Blizzard_Deprecated\Deprecated_9_1_0.lua` for `C_TransmogCollection.SetShowMissingSourceInItemTooltips` throws `91: attempt to call global 'SetCVarBool' (a nil value)`.

This is because it's trying to do:

```lua
	C_TransmogCollection.GetShowMissingSourceInItemTooltips = function()
		return GetCVarBool("missingTransmogSourceInItemTooltips");
	end
	C_TransmogCollection.SetShowMissingSourceInItemTooltips = function(show)
		SetCVarBool("missingTransmogSourceInItemTooltips", show and true or false);
	end
```

However, the `SetCVarBool` function doesn't exist, and there's no explicit replacement in `C_CVar`. It should just be replaced with a call to `SetCVar`, since that wrapper handles boolean values appropriately.

**Comment by Meorawr** [comment]
While this is _still_ broken as we're effectively on the last patch of the expansion before these deprecated functions get nuked anyway I think we can safely close this as a wontfix - especially as any addon using these functions would have been broken for a year at this point.
