### ISSUE TITLE
Classic/BCC: MinimapCompassTexture missing .7 scale modifier

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#147]
MinimapCompassTexture on the Classic Era and BCC clients is missing the `scale=".7"` attribute, which causes the compass to be oversized and sit outside the bounds of the minimap frame when the "Rotate Minimap" option is enabled in the Interface > Display settings. The issue can be seen below.

![image](https://user-images.githubusercontent.com/287102/126880167-de0b2858-f2ee-4848-aac2-7198474d0822.png)

This issue doesn't affect Mainline which has the attribute and scales the texture accordingly to fit within the frame, as shown below.

![image](https://user-images.githubusercontent.com/287102/126880175-6857f4af-5118-4d3c-92db-863b4df398fc.png)

**Comment by Meorawr** [comment]
Fixed in 2.5.1.39801. Classic era will probably get the fix eventually.

**Comment by Laumesis** [comment]
Note: Still not fixed in 1.14.1.40818 Classic Era PTR. I filled ingame bug report.

**Comment by Laumesis** [comment]
The bug exists still in v1.14.3.43649
