### ISSUE TITLE
Classic: lua error when Blizzard_InspectUI loaded in zhCN client

### ISSUE THREAD

**Issue by siweia** [Stanzilla/WoWUIBugs#190]
`AddOns\Blizzard_InspectUI\Localization.lua:8: attempt to index global 'InspectTalentFrameSpentPoints' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\Blizzard_InspectUI\Localization.lua"]:8: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "LoadAddOn'Blizzard_InspectUI'"]:1: in main chunk
[string "=[C]"]: in function `RunScript'
[string "@FrameXML\ChatFrame.lua"]:2160: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4833: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4496: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4532: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
`

It occurred since patch 1.14.0, and still exists in ptr 1.14.1.

**Comment by siweia** [comment]
One more localization file error:
AddOns\Blizzard_GMChatUI\Localization.lua:3: attempt to index global 'GMChatStatusFrameDescription' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\Blizzard_GMChatUI\Localization.lua"]:3: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Vanilla\FrameXML\UIParent.lua"]:365: in function `UIParentLoadAddOn'
[string "@Interface_Vanilla\FrameXML\UIParent.lua"]:443: in function `GMChatFrame_LoadUI'
[string "@Interface_Vanilla\FrameXML\UIParent.lua"]:1244: in function <Interface_Vanilla\FrameXML\UIParent.lua:655>

https://bbs.nga.cn/read.php?&tid=18321155&pid=565861830&to=1

**Comment by Meorawr** [comment]
I think the inspection UI one has been fixed for a while now in a hotfix build back in early December or so - can re-open if it's still broken.

**Comment by siweia** [comment]
Still haven't been fixed yet.

**Comment by siweia** [comment]
Still exisits in 1.14.3.43154.
Temporary solution:
`
	if not InspectTalentFrameSpentPoints then
		InspectTalentFrameSpentPoints = CreateFrame("Frame")
	end`

**Comment by EKE00372** [comment]
This issue still exisit and happened on both zhTW and zhCN.
include Classic, Cata, and the Wrath version for China.

https://github.com/Gethe/wow-ui-source/blob/classic/Interface/AddOns/Blizzard_InspectUI/Classic/Localization.lua

**Comment by Meorawr** [comment]
Fixed in 1.15.4.56573 and 4.4.1.56574.
