### ISSUE TITLE
C_LFGList.GetApplicantMemberInfo returns a decimal number for dungeonScore and pvpRating

### ISSUE THREAD

**Issue by ChrisKader** [Stanzilla/WoWUIBugs#194]
As a result, the default UI currently looks like this:

![image](https://user-images.githubusercontent.com/633360/139970587-10fc923c-b638-4549-90a5-b47875414ebb.png)

Any addons that do not use math.floor (or alternative solution to truncate the full value) on the 12th and 13th value returned from the C_LFGList.GetApplicantMemberInfo will show the full decimal number.

**Comment by Nevcairiel** [comment]
Is this still occuring? I can't say I have noticed decimal values in the default UI as of late.

**Comment by ChrisKader** [comment]
This is no longer an issue.
