### ISSUE TITLE
Broken links on 9.1.5 Consolidated UI Changes wiki page

### ISSUE THREAD

**Issue by glassleo** [Stanzilla/WoWUIBugs#196]
Sorry if this is the wrong place to report this but [the wiki page for 9.1.5 changes](https://github.com/Stanzilla/WoWUIBugs/wiki/9.1.5-Consolidated-UI-Changes) has a lot of links to townlong-yak.com that are all broken. I'd suggest changing the build number in all the links from ``39977`` to ``40871`` instead.

For example change:

``https://www.townlong-yak.com/framexml/39977/Blizzard_Deprecated/Deprecated_9_1_5.lua``

to:

``https://www.townlong-yak.com/framexml/40871/Blizzard_Deprecated/Deprecated_9_1_5.lua``

**Comment by Ketho** [comment]
It also supports linking to `live` https://www.townlong-yak.com/framexml/about
`https://www.townlong-yak.com/framexml/live/Blizzard_Deprecated/Deprecated_9_1_5.lua`

But otherwise you or me should edit it ourselves since it's wiki

**Comment by glassleo** [comment]
> It also supports linking to `live`, provided the link didn't point to a line number https://www.townlong-yak.com/framexml/about `https://www.townlong-yak.com/framexml/live/Blizzard_Deprecated/Deprecated_9_1_5.lua`

Oh nice, good to know!

> But otherwise you or me should edit it ourselves since it's wiki (edit) foxlit usually deletes beta/ptr builds so I learned not to link to them

I don't have permissions to edit the page. That's why I'm posting here.

**Comment by Ketho** [comment]
I changed the links without line numbers to 9.1.5, i.e. not the Enums and FrameXML sections
