### ISSUE TITLE
[8.2.0 PTR] Crashes on GetItemInfo links

### ISSUE THREAD

**Issue by Stanzilla** [Stanzilla/WoWUIBugs#2]
PTR started crashing on GetItemInfo for some stripped down item links. 

`|cffa335ee|Hitem:165493::::::::120:251::3:4:5124:4802:1477:4784:::|h[Deathguard's Greaves]|h|r`
works

`item:165493::::::::120:251::3:4:5124:4802:1477:4784:::`
crashes

`|cffa335ee|Hitem:166561::::::::120:251::6:5:5126:1502:4786:5402:4775:::|h[Deathguard's Casque]|h|r`
works

`item:166561::::::::120:251::6:5:5126:1502:4786:5402:4775:::`
also works.

**Comment by SinusPi** [comment]
After some tinkering, it seems that it's LibGratuity that causes the crash - there's no issue on plain GameTooltip:SetHyperlink() calls.
