### ISSUE TITLE
LFG list search tooltip reads undefined variable displayType

### ISSUE THREAD

**Issue by ChrisKader** [Stanzilla/WoWUIBugs#204]
Undefined variable `displayType` results in any activities that use the `LE_LFG_LIST_DISPLAY_TYPE_CLASS_ENUMERATE` being shown incorrectly.

[Line 3577 in LFGList.lua](https://github.com/Stanzilla/WoWUIBugs/blob/live/FrameXML/LFGList.lua#L3577) currently reads: `if ( displayType == LE_LFG_LIST_DISPLAY_TYPE_CLASS_ENUMERATE ) then`

It should read: `if ( activityInfo.displayType == LE_LFG_LIST_DISPLAY_TYPE_CLASS_ENUMERATE ) then`

**Comment by Meorawr** [comment]
Fixed in 9.2.0.42069.
