### ISSUE TITLE
TemplatedListMixin:AttachHighlightToElementFrame() anchors highlight to incorrect frame

### ISSUE THREAD

**Issue by Gethe** [Stanzilla/WoWUIBugs#208]
TemplatedListMixin:AttachHighlightToElementFrame overwrites the `elementFrame` argument with `nil` resulting in a bad frame anchor for the subsequent SetPoint.
https://github.com/Gethe/wow-ui-source/blob/d4eb799237c26f046cfecd2a3bf8d0cc96106de2/Interface/SharedXML/TemplatedList.lua#L132

**Comment by Meorawr** [comment]
Fixed in 11.0.0.
