### ISSUE TITLE
C_VoiceChat.SpeakText stops working after character logout

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#209]
The `C_VoiceChat.SpeakText` API breaks once the player has logged out of a character and no longer speaks any text until the client is fully restarted.

This is currently reproducible on the following client versions:

* 9.2.0.41827
* 1.14.2.41858
* 2.5.3.41812

The issue **does not** occur on the following client versions:

* 9.1.5.41793
* 1.14.1.41794

To reproduce the issue:

1. Log into the game on any character.
2. Execute the following command ~10 seconds after logging in: `/run C_VoiceChat.SpeakText(0, "Just a test", 6, 1, 100)`.
3. Log out back to the character selection screen.
4. Log back in onto either the same character or a different one.
5. Run the command again ~10 seconds after logging in: `/run C_VoiceChat.SpeakText(0, "Just a test", 6, 1, 100)`

The expectation would be that TTS says "Just a test" both times when the command is executed, however it seemingly only works the first time and not the second. The issue only appears to be resolved with a full client restart - no amount of waiting nor logging out and in again appears to help.

**Comment by Duugu** [comment]
Apparently a Windows-only issue.
Mac seems to be unaffected.

**Comment by Duugu** [comment]
That issue seems to be fixed with one of the recent patches.
