### ISSUE TITLE
API to determine if a unit is a quest giver, vendor, etc.

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#211]
This request is to extend the unit API with new functions that can determine if a given unit offers quests, is a vendor, or otherwise provides some service to the current player - namely any of the ones trackable on the minimap such as repairs, auction house, banking, etc. Ideally this would be implemented such that any unit token belonging to an NPC can be queried - including nameplate tokens.

This has a few use cases for accessibility-related addons as well as those that wish to adorn interaction markers on friendly nameplates of NPCs. As this information is already essentially made visible in the UI via the minimap and to some degree the cursor when mousing-over a unit, it feels reasonable that it could be exposed directly as a function without much risk.

Addons currently can embed databases with this information included, however maintenance of such databases is extremely difficult and often requires some level of crowdsourcing - which is problematic for players who may rely on these addons when new content is released.

**Comment by kemayo** [comment]
You could get a fair amount out of just "what cursor would be shown if it was placed over this NPC?" as an API. (It'd be a start, at least, and is presumably information that the game already has available...)

**Comment by Meorawr** [comment]
This is resolved in 10.0.0.49999 with the new `UnitCursor(unit[, style, includeLowPriority])` API which - from basic testing - seems to return sensible values for mouseover/target unit tokens on both friendly and enemy NPCs.
