### ISSUE TITLE
Add CURSOR_CHANGED event to Classic/TBC

### ISSUE THREAD

**Issue by Duugu** [Stanzilla/WoWUIBugs#212]
The CURSOR_CHANGED event (https://wowpedia.fandom.com/wiki/CURSOR_CHANGED) would be quite helpful to support visually impaird / blind players.

As it is available in Retail I guess there's no reason why it shouldn't be added to TBC, Classic, and SoM.

**Comment by Meorawr** [comment]
Closing as this has been ported over as of 3.4.0. Classic Era should get a service patch one day that brings it there too.
