### ISSUE TITLE
Keyboard values and bindings changed unexpectedly on 9.2 for french AZERTY keyboards

### ISSUE THREAD

**Issue by LenweSaralonde** [Stanzilla/WoWUIBugs#217]
Some key values are no longer correct on French AZERTY keyboards on WoW 9.2. 

Some bindings get broken when upgrading from 9.1.5 to 9.2 and needs to be reset manually.

Here is how a french AZERTY PC keyboard layout looks like :
![image](https://user-images.githubusercontent.com/34239920/154810001-c1e7cb45-43dd-48ff-8690-5705daa1c8d7.png)

Here is how this keyboard translates in WoW 9.1.5 (correct) : 
![image](https://user-images.githubusercontent.com/34239920/154810024-5496ea47-25e9-49b9-b664-4f0ad7373f47.png)

Here is how this exact same keyboard translates in WoW 9.2 (some inconsistencies) : 
![image](https://user-images.githubusercontent.com/34239920/154810114-5997503d-fc2c-4e7c-86e7-b834bd61e401.png)

Some keys differ, for example `²` that becomes `'`, `)` becomes `[`, `:` becomes `/` etc.

I would expect as a player to have the translated key values unchanged and reflect my actual keyboard layout.

**Comment by Meorawr** [comment]
This is reported as having been fixed as of build 9.2.0.42488.
