### ISSUE TITLE
[classic] whispers to/from a player start without -realm and then switch to fully qualified p-r

### ISSUE THREAD

**Issue by mooreatv** [Stanzilla/WoWUIBugs#22]
If you have the chat set to "IM style" (and no addon)
you end up with 2 tabs, the initial message and your reply with player-realm and the remaining of the conversation

It seems this happens when the 2 players are on different layer

**Comment by mooreatv** [comment]
> It seems this happens when the 2 players are on different layer

actually Blaumeux (us) is now single layer and this is still happening

**Comment by Ketho** [comment]
You need a better repro example and/or screenshot

**Comment by mooreatv** [comment]
repro is easy: anyone sends you a message it goes to 1 tab without realm name you reply, the rest of the convo goes to new tab with the realm name (using default UI + open new tabs for private messages)

**Comment by Meorawr** [comment]
Can't reproduce this in 1.14.0, assuming it's fixed - otherwise I'll agree with Ketho and better repro instructions and screenshots/video are needed.
