### ISSUE TITLE
LoadWith TOC directive doesn't work (again)

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#223]
The `LoadWith` TOC directive has broken again in Classic Era and BCC clients and doesn't appear to function at all.

This has been tested on the following client versions:

- Wrath 3.4.0.45198: **Broken**
- BCC 2.5.3.42328: **Broken**
- Classic Era 1.14.2.42214: **Broken**
- Mainline 9.2.0.42521: Working

A test case is attached below containing two addon folders - TestAddOn1 and TestAddOn2. Both addons are LoadOnDemand. TestAddOn1 has its `LoadWith` set to trigger upon the load of Blizzard_MovePad, and TestAddOn2 will trigger on load of TestAddOn1.

[LoadWith_Test.zip](https://github.com/Stanzilla/WoWUIBugs/files/8164742/LoadWith_Test.zip)

The expectations are:

- Loading Blizzard_MovePad should load TestAddOn1.
- Loading TestAddOn1 - either manually or implicitly through the above - should load TestAddOn2.

Neither of the above expectations are met in the Classic Era or BCC clients. Mainline works as expected for both of the above.

**Comment by Meorawr** [comment]
PTR build 2.5.4.42757 seems to have made some changes that make 'LoadWith' more broken than initially reported.

With the test case attached in the initial ticket the expectation was - with a UI reload between each of the following:

- `/run LoadAddOn("Blizzard_MovePad")` would load itself and then both "TestAddOn1" and "TestAddOn2" in that order.
- `/run LoadAddOn("TestAddOn1")` would load itself and then only "TestAddOn2".
- `/run LoadAddOn("TestAddOn2")` would only load itself.

With the most recent build, the following occurs:

- `/run LoadAddOn("Blizzard_MovePad")` loads only itself.
- `/run LoadAddOn("TestAddOn1")` loads itself and then "Blizzard_MovePad".
- `/run LoadAddOn("TestAddOn2")` loads itself and then "TestAddOn1" and "Blizzard_MovePad" in that order.

**Comment by Ketho** [comment]
I can confirm LoadWith addons still will not load, after testing with e.g. GuildBankSearch on 2.5.4 (44036)
```
## LoadOnDemand: 1
## LoadWith: Blizzard_GuildBankUI
```

**Comment by Meorawr** [comment]
Still broken as of 3.4.0.45189, unfortunately.

**Comment by Meorawr** [comment]
This has seemingly been fixed for a while - works fine in 3.4.3 and 1.15.1.
