### ISSUE TITLE
Duplicate LFG applications after refreshing list since patch 9.1.5

### ISSUE THREAD

**Issue by Witnesscm** [Stanzilla/WoWUIBugs#224]
This issue has been reported in the official Bug Reports forum a few times.

https://us.forums.blizzard.com/en/wow/t/group-finder-sign-up-doubled/1135123
https://us.forums.blizzard.com/en/wow/t/duplicates-in-lfg-after-refreshing-list/1129565
https://us.forums.blizzard.com/en/wow/t/showing-doubles-of-lfg-posts/1130456

It seems that the return value of `C_LFGList.GetSearchResults` and `C_LFGList.GetFilteredSearchResults` has changed.

Anyway, I made a simple fix.
```
hooksecurefunc("LFGListSearchPanel_UpdateResultList", function(self)
    if next(self.results) and next(self.applications) then
        for _, value in ipairs(self.applications) do
            tDeleteItem(self.results, value)
        end
        self.totalResults = #self.results

        LFGListSearchPanel_UpdateResults(self)
    end
end)
```

**Comment by Milky063** [comment]
Where do i put this string in for the simple fix?

**Comment by ChrisKader** [comment]
Does this taint the stack since it modifies the results table? From what I could tell, the "results" from GetSearchResults includes applications so I simply do not include the applications when updating buttons.
```for i = 1, #buttons do
      local button = buttons[i]
      local idx = i + offset
      local result = results[idx] --(idx <= #apps) and apps[idx] or results[idx - #apps]
      if result then
        --local searchResultInfo = C_LFGList.GetSearchResultInfo(result)
        button.resultID = result
        LFGListSearchEntry_Update(button)
        button:Show()
        lastVisibleButton = button
      else```
