### ISSUE TITLE
EventTrace tooltip drawn behind frame

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#227]
The mouseover tooltip is obscured when using the /etrace window. This appears to be a result of changing its framestrata to "TOOLTIP".
https://github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_EventTrace/Blizzard_EventTrace.xml#L170

![image](https://user-images.githubusercontent.com/1073877/159659552-c9bd7806-9a8d-4128-9bc6-02dddd9e2c5f.png)

Setting the framelevel higher `EventTraceTooltip:SetFrameLevel(501)` seems to remedy it.
Reproduced in retail 9.2.0 (42698), ptr 9.2.5 (42850)

**Comment by kodewdle** [comment]
confirming this. i fixed it on **ElvUI** side with our skin using same method (bumping the level up): https://github.com/tukui-org/ElvUI/commit/de8064f3aef3150898ecf9516bd72d8e29e73163

**Comment by Meorawr** [comment]
Resolved in 9.2.5.43022.
