### ISSUE TITLE
Suggestion Get Realm Is Develpment Info

### ISSUE THREAD

**Issue by javierhimura** [Stanzilla/WoWUIBugs#236]
I think it could be helpful to have a way to query the server to determine if the player is currently on a live realm or a ptr/beta realm.
Currently, the only method that I know is to use LibRealmInfo, a library that contains a full list of live realms from Classic and Retail, so if the player is from a realm not on that list that means he is on a ptr/beta, but this approach required to keep the list up to date.

It will work just with a function that returns ptr on a ptr realm, beta on a beta realm, and nil on non-development realms. The different versions of beta and ptr (classic/retail) could be differentiated by checking if the client is classic or retail.

**Comment by Meorawr** [comment]
What use cases would this solve?

- There's already an `IsTestBuild()` function in the API which will return true for the _majority_ of PTR and beta builds with the exception of release candidates that appear ~two weeks prior to launch of a patch.
- You can check the contents of the "portal" console variable to determine if the player connected to the PTR login servers on client launch: `/dump C_CVar.GetCVar("portal") == "test"`.

**Comment by javierhimura** [comment]
The case use is to make for example addons for completionists that export a list of things the players have done like quests, achievements, and reputations and paste it on a version of the addon on a different version of the game.

For the achievements, part players would be able to export their achievements from Classic WOTLK and import that Info and retail and vice versa. Once Classic WOTLK launch probably no player would want to import and export data from PTR/Beta versions, but while is still Beta for testing purposes most will export data from WOTLK Beta into Retail, but I will like the be able to flag that data as data from Beta so once Classic WOTLK launch they can delete Beta data on the Retail addon to not mix it with live data.
