### ISSUE TITLE
9.2.7: Autogenerated API documentation is missing

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#239]
**Re-opened as this has broken again in a post-release build (9.2.7.45161).**

The auto-generated API documentation has gone missing again in live build 9.2.7.45161. Running `/api` will result in the following popup, and the `exportinterfacefiles code` console command doesn't export the documentation files.

![image](https://user-images.githubusercontent.com/287102/185575970-c860ac45-b3ed-467c-b9d3-8bb3955599b9.png)

**Comment by funkydude** [comment]
"soon" being "not yesterdays build" for whatever reason. 9.2.7 is supposed to be soon which is concerning.

**Comment by Meorawr** [comment]
The API documentation is in the latest build and works via `/api`, it just isn't exported now. Small steps.

**Comment by Meorawr** [comment]
Fixed in 9.2.7.45144.

**Comment by Meorawr** [comment]
Re-opening as this is broken again in the immediate build after the patch has released (9.2.7.45161). Presumably related to the path for the documentation being case-corrected from "Interface\Addons\..." to "Interface\AddOns..." resulting in all the manifest records being deleted.
