### ISSUE TITLE
[Wrath Beta] MultiCastActionBarFrame not showing up on init login but after /reload

### ISSUE THREAD

**Issue by Luckyone961** [Stanzilla/WoWUIBugs#246]
On the current Wrath Beta 3.4.0.44729 the MultiCastActionBarFrame (Shaman Totem Bar) does not spawn on the initial login.

(No AddOns enabled while testing this)

1. Launch the client
2. Login to a shaman
3. Bar is not there
4. /reload
5. Bar is there

## Initial Login  
![Initial Login](https://i.imgur.com/Ka92zQf.jpg "Initial Login")

## After Reload  
![After Reload](https://i.imgur.com/C96mHTR.jpg "After Reload")

**Comment by trixitrx** [comment]
can confirm!

**Comment by Repooc** [comment]
can confirm

**Comment by Nevcairiel** [comment]
This sort of bug report is probably better taken straight to the Wrath Beta forums, or the in-game bug reporting tool.

**Comment by Luckyone961** [comment]
I used the in-game tool as well

**Comment by Meorawr** [comment]
This appears to be fixed as of (at least) 3.4.0.45043.
