### ISSUE TITLE
macro conditional spec not working in Wrath Beta or Wrath PTR

### ISSUE THREAD

**Issue by SunNova67** [Stanzilla/WoWUIBugs#249]
macro conditional spec not working in Wrath Beta or PTR, 

my toon has dual talents

/cast [spec:1] Molten Armor ;  [spec:2] Frost Armor

nothing happens.

**Comment by siweia** [comment]
Specs will be available in MoP, not now. You don't have any 'specs' at the moment.

**Comment by SunNova67** [comment]
Looks like the spec:1 and spec:2 macro conditionals were added in the last patch, seems to be working just fine.
