### ISSUE TITLE
Garrison Shipyard UI integer overflow

### ISSUE THREAD

**Issue by esruv** [Stanzilla/WoWUIBugs#253]
When I attempt to decommission a garrison shipyard ship it gives a LUA error presenting a integer overflow (no addons enabled and reinstalled WoW and still happening) 
![image](https://user-images.githubusercontent.com/77903716/185798911-31aaaaf7-251c-4f9a-9478-9432347f301b.png)

**Comment by Nevcairiel** [comment]
Issues with the vanilla UI functionality should be reported through the normal feedback channels, its far more likely to get fixed if QA picks it up, especially since its a system several expansions old.
