### ISSUE TITLE
Frame:SetResizeBounds uses parameters in the wrong order

### ISSUE THREAD

**Issue by Nevcairiel** [Stanzilla/WoWUIBugs#255]
The usage hint for SetResizeBounds says this:
`Usage: self:SetResizeBounds(minWidth, minHeight [, maxWidth, maxHeight])`

Testing revealed, the minHeight and maxHeight parameters are swapped.

`frame:SetResizeBounds(100, 100)` results in a frame with a minimum width of 100, but a *maximum* height of 100, not a minimum. 

Using `frame:SetResizeBounds(100, 400, 400, 100)` results in a frame with 100/100 minimum, and 400/400 maximum.

Unfortunately this makes the function really impractical to use, since you cannot set a minimum without also setting a maximum (and expecting it to get fixed would break stuff later). And I reckon this also affects some Vanilla UI frames that use this call.

Tested on 10.0.0.45335

**Comment by brittyazel** [comment]
This seems fixed as of today's update

**Comment by Nevcairiel** [comment]
Can confirm this appears to be working in 10.0.2.45480
