### ISSUE TITLE
Frames inheriting SecureActionButtonTemplate no longer execute SecureActionButton_OnClick

### ISSUE THREAD

**Issue by brittyazel** [Stanzilla/WoWUIBugs#268]
In Shadowlands and prior, code implementing a simple button such as below would execute the macro text (or action, spell, whatever) upon being left-clicked.

```
local macroBtn = CreateFrame("Button", "myMacroButton", UIParent, "SecureActionButtonTemplate")
macroBtn:SetAttribute("type1", "macro") -- left click causes macro
macroBtn:SetAttribute("macrotext1", "/raid zomg a left click!") -- text for macro on left click
```

In Dragonflight, the same code doesn't register any Lua errors; however, upon clicking the button does nothing.

Using hooksecurefunc on SecureActionButton_OnClick, I can verify that SecureActionButton_OnClick is called successfully when an built-in button is clicked, but is not executed when an addon button inheriting from SecureActionButtonTemplate is clicked. This effectively breaks addons that implement custom buttons to perform actions such as Neuron, etc.

**Comment by Nevcairiel** [comment]
This works fine for me, although there is one limitation I have discovered. You need to make sure that RegisterForClicks matches the CVar ActionButtonUseKeyDown. If KeyDown is enabled, then you need RegisterForClicks("AnyDown"), if its not, you need "AnyUp" ... or just go with RegisterForClicks("AnyUp", "AnyDown") to catch both cases.

Its a bit unfortunate that its enforced on a global level now, but at least its easy enough worked around - and it gives you consistency in button press behavior, I suppose.

We could ask for a new attribute so that addons can individually control the on-down/on-up behavior of their buttons, or at least to make SecureActionButtons register for AnyDown/AnyUp by default, but this issue can be worked around for now, so maybe bigger fish to fry.

On second thought, you likely need AnyDown registered if you ever want to deal with empowered spells. So maybe this is the only way for now without complex solutions.

**Comment by Meorawr** [comment]
I'll flag this as a feature request since it's in the blurry mess between an awkward undesirable behavior and "well if we had this it'd be nice...".

If adding an `registerForClicks="AnyDown, AnyUp"` attribute to `SecureActionButtonTemplate` would fix the issue cleanly then I think we could easily ask for this as a quick tweak. If an addon is broken by the change they can always change their click registrations to the exact thing they want.

**Comment by brittyazel** [comment]
Hrm ok. I'll have to try this when I'm home from work. My addon allows users to set the on click behavior for buttons on an actionbar by actionbar basis, with the default being RegisterForClicks("AnyUp"). This change to the game potentially breaks this feature in my code, as I can't have this option be specific per actionbar as well as dependent on a global cvar. I may have to start mandating RegisterForClicks("AnyUp", "AnyDown") and take away the user selectable feature unless they return the behavior to how it was prior

**Comment by Nevcairiel** [comment]
If you create actual actionbars with normal abilities, you won't get around supporting both up and down in any case, because empowered evoker abilities definitely need it, as they start channeling on "down" and fire on "up", which is why I think its probably not the most terrible requirement.

**Comment by brittyazel** [comment]
Good point, I hadn't even thought about the evokers. 

I tested, and you are correct, 	self:RegisterForClicks("AnyDown", "AnyUp") does allow the buttons to execute. That said, this is a somewhat messy solution (not just for the above mentioned reasons), but it makes click to drag the spells around slightly more difficult as no my abilities are executing on the downclick before the drag has started. The old way was far more convenient tbh.

**Comment by brittyazel** [comment]
Wow, looking at SecureActionButton_OnClick, it has changed a TON. No wonder things are acting funky. It's a shame they've made the execution depending on that CVar globally, even for non-Blizzard elements.

Shadowlands:
```
function SecureActionButton_OnClick(self, button, down)
    -- TODO check with Tom etc if this is kosher
    if (down) then
        -- remap the button if desired for up-down behaviors. This behavior may not be safe and has been deferred.
        button = SecureButton_GetModifiedAttribute(self, "downbutton", button) or button
    end

    -- Lookup the unit, based on the modifiers and button
    local unit = SecureButton_GetModifiedUnit(self, button);

    -- Remap button suffixes based on the disposition of the unit (contributed by Iriel and Cladhaire)
    if ( unit ) then
        local origButton = button;
        if ( UnitCanAttack("player", unit) )then
            button = SecureButton_GetModifiedAttribute(self, "harmbutton", button) or button;
        elseif ( UnitCanAssist("player", unit) )then
            button = SecureButton_GetModifiedAttribute(self, "helpbutton", button) or button;
        end

        -- The unit may have changed based on button remapping
        if ( button ~= origButton ) then
            unit = SecureButton_GetModifiedUnit(self, button);
        end
    end

    if ( type(button) ~= "string" ) then
        return;
    end

    -- Don't do anything if our unit doesn't exist
    if ( unit and unit ~= "none" and not UnitExists(unit) ) then
        return;
    end

    -- Lookup the action type, based on the modifiers and button
    local actionType = SecureButton_GetModifiedAttribute(self, "type", button);

    -- Perform the requested action!
    if ( actionType ) then
        local atRisk = false;
        local handler = SECURE_ACTIONS[actionType]
        if ( not handler ) then
            atRisk = true; -- user-provided function, be careful
            -- GMA call allows generic click handler snippets
            handler = SecureButton_GetModifiedAttribute(self, "_"..actionType, button);
        end
        if ( not handler ) then
            atRisk = false;
            -- functions retrieved from table keys carry their own taint
            handler = rawget(self, actionType);
        end
        if ( type(handler) == 'function' ) then
            if ( atRisk ) then
                forceinsecure();
            end
            -- actionType arg removed for 4,0
            handler(self, unit, button);
        elseif ( type(handler) == 'string' ) then
            SecureHandler_OnClick(self, "_"..actionType, button, down);
        end
    end

    -- Target predefined item, if we just cast a spell that targets an item
    if ( SpellCanTargetItem() or SpellCanTargetItemID() ) then
        local bag = SecureButton_GetModifiedAttribute(self, "target-bag", button);
        local slot = SecureButton_GetModifiedAttribute(self, "target-slot", button);
        if ( slot ) then
            if ( bag ) then
                UseContainerItem(bag, slot);
            else
                UseInventoryItem(slot);
            end
        else
            local item = SecureButton_GetModifiedAttribute(self, "target-item", button);
            if ( item ) then
                SpellTargetItem(item);
            end
        end
    end
end
```

Dragonflight:

```
function SecureActionButton_OnClick(self, inputButton, down, isKeyPress)
	local pressAndHoldAction = SecureButton_GetAttribute(self, "pressAndHoldAction");
	local useOnKeyDown = GetCVarBool("ActionButtonUseKeyDown") or pressAndHoldAction;
	local clickAction = (down and useOnKeyDown) or (not down and not useOnKeyDown);
	local releasePressAndHoldAction = (not down) and (pressAndHoldAction or GetCVarBool("ActionButtonUseKeyHeldSpell"));

	if clickAction then
		OnActionButtonClick(self, inputButton, down, isKeyPress);
		return true;
	elseif releasePressAndHoldAction then
		OnActionButtonPressAndHoldRelease(self, inputButton, isKeyPress);
		return true;
	end

	return false;
end
```

**Comment by TimothyLuke** [comment]
Following on from this: 
```
local mybutton = CreateFrame("Button", "MYBUTTON", nil, "SecureActionButtonTemplate,SecureHandlerBaseTemplate")
mybutton:SetAttribute("type", "macro")
mybutton:RegisterForClicks("AnyUp", "AnyDown")
mybutton:WrapScript(mybutton, "OnClick", [[
  print("Hello")
  self:SetAttribute('macrotext', "/say Im here")
  print("world")
]]
```
With the following test, the Hello and World appear but the /say line is never displayed via `/click MYBUTTON`


Update: thanks @Nevcairiel 
`/click MYBUTTON` no longer defaults to LeftButton but needs to be specific: `/click MYBUTTON LeftButton`

**Comment by kemayo** [comment]
This hit me as well for SilverDragon, which is faking unit frames that do `/target` with `macrotext`. Having to register `AnyDown` does make them inevitably feel less like the unitframes they're pretending to be, which is unfortunate.

**Comment by Meorawr** [comment]
I'm going to close this in favour of splitting things into two tickets to make what we're asking clearer.

1. #282
2. #283
