### ISSUE TITLE
GetGuildInfo and GetPlayerInfoByGUID return invalid data for player names

### ISSUE THREAD

**Issue by ykiigor** [Stanzilla/WoWUIBugs#269]
Name return is filled with \000 up to 48 characters.
![gpibg](https://user-images.githubusercontent.com/28834046/189121222-dd3271f8-8eff-4a38-8878-d68c360f5e38.png)

**Comment by Meorawr** [comment]
I'll use this ticket to also collect a similar reported issue for the `GetGuildInfo("player")` API, since they're probably the same underlying problem.

![image](https://user-images.githubusercontent.com/287102/189214852-a14890a0-c48b-44a2-85eb-80a992d2e9b4.png)

**Comment by Meorawr** [comment]
This appears to be fixed in 10.0.0.45570.
