### ISSUE TITLE
UnitHealth | UnitHealthMax API Returns incorrect values

### ISSUE THREAD

**Issue by Azilroka** [Stanzilla/WoWUIBugs#273]
It is currently returning percent when it should be returning aboslute data.

[Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2/API_changes) (2008-10-14): Returns absolute health instead of percentages for non party/raid units.

**Comment by Nevcairiel** [comment]
I cannot confirm this so far. On normal enemy mobs I get full numeric health values.

**Comment by Azilroka** [comment]
On Enemy Mobs yes but it specifically states non-party / raid units.

**Comment by Ketho** [comment]
> [Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2/API_changes) (2008-10-14): Returns absolute health instead of percentages for non party/raid units.

That specific note was added to the wiki in 2019, I'm not sure how accurate it is without a reference
https://wowpedia.fandom.com/wiki/API_UnitHealth?diff=5503815&oldid=5455453

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/190282700-b6949202-0bf5-456b-acda-deccadb7ebc2.png)
When was that page updated?

**Comment by Azilroka** [comment]
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2/API_changes
This is also an older link

**Comment by Micrologist** [comment]
This seems to be fixed

**Comment by Azilroka** [comment]
It's fixed
