### ISSUE TITLE
Unitframes do not switch to vehicle unit

### ISSUE THREAD

**Issue by Aviana** [Stanzilla/WoWUIBugs#274]
Some code of the "SecureButton_GetModifiedUnit" function in .../FrameXML/SecureTemplates.lua is still comented out. This prevents unit frames from automatically switching to the vehicle unit. This is most notable during the Malygos encounter. Reported multiple times on beta.

**Comment by stratoru** [comment]
Still unfixed as of 3.4.0.45854, with raid release only 4 days away.

**Comment by Meorawr** [comment]
Should be fixed in 3.4.1.47496.
