### ISSUE TITLE
Error while importing UI (Edit Mode) from Clipboard

### ISSUE THREAD

**Issue by Tercioo** [Stanzilla/WoWUIBugs#276]
Dragonflight 10.0.2.45569
Made sure no addons enabled.

Exported (Layout Dropdown > Share > Copy To Clipboard) layout named "one" from a character level 60 on leveling realm.
Imported (Layout Dropdown > Import > pasted whatever was in the clipboard and pasted there) with the name "one(2)" on a character level 70 on Valdrakken.

Clipboard (look like the pasted string in the text area (photo) is shorter than the string pasted here):

`5 26 0 0 7 7 UIParent 0.0 25.0 1 ##$$%/&('%)$+$ 0 1 7 7 UIParent -0.9 74.1 0 ##$$%/&('%(#,$ 0 2 7 1 MultiBarBottomLeft 0.0 5.0 1 ##$$%/&('%(#,$ 0 3 5 5 UIParent -5.0 -77.0 1 #$$$%/&('%(#*$,$ 0 4 7 7 UIParent -1.0 173.7 0 ##$$%/&('%(#*#,$ 0 10 6 0 MainMenuBar 0.0 5.0 1 ##$$&('% 0 11 6 0 MainMenuBar 0.0 5.0 1 ##$$&('%,# 0 12 6 0 MainMenuBar 0.0 5.0 1 ##$$&('% 1 -1 4 4 UIParent 0.0 0.0 1 ##$# 2 -1 2 2 UIParent 0.0 0.0 1 ## 3 0 0 0 UIParent -20.0 0.0 0 ##$# 3 1 4 4 UIParent 254.8 -178.0 0 %# 3 2 3 5 TargetFrame 10.0 0.0 1 %#&# 3 3 0 2 CompactRaidFrameManager 0.0 -7.0 1 '#(#)#-#.#/# 3 4 0 2 CompactRaidFrameManager 0.0 -5.0 1 )#,#-#.#/#0$1#2( 3 5 5 5 UIParent 0.0 0.0 1 &#*$ 3 6 5 5 UIParent 0.0 0.0 1 &#*$ 4 -1 7 1 MainMenuBar 0.0 5.0 1 &#*$ 5 -1 6 0 MainMenuBar 0.0 5.0 1 &#*$ 6 0 2 0 MinimapCluster -10.0 -10.0 1 ##$#%#&+(()(*# 6 1 2 8 BuffFrame -13.0 -5.0 1 ##$#%#'+(()(*# 7 -1 6 0 MainMenuBar 0.0 5.0 1 ##$#%#'+(()(*# 8 -1 6 6 UIParent 35.0 50.0 0 #($<%&&7 9 -1 6 0 MainMenuBar 0.0 5.0 1 #($<%&&7 10 -1 0 0 UIParent 16.0 -116.0 1 #($<%&&7 11 -1 8 8 UIParent -9.0 85.0 1 #($<%&&7`

![image](https://user-images.githubusercontent.com/9000280/190409106-1a97c674-7288-4042-94a7-f37ff7b442df.png)

Error:
Message: MainMenuBar:SetPoint(): Couldn't find region named ''
Time: Thu Sep 15 09:55:39 2022
Count: 1
Stack: MainMenuBar:SetPoint(): Couldn't find region named ''
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:113: in function `ApplySystemAnchor'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:125: in function `UpdateSystem'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:281: in function `UpdateSystem'
[string "@Interface/FrameXML/EditModeManager.lua"]:929: in function `UpdateSystem'
[string "@Interface/FrameXML/EditModeManager.lua"]:918: in function `UpdateSystems'
[string "@Interface/FrameXML/EditModeManager.lua"]:820: in function `UpdateLayoutInfo'
[string "@Interface/FrameXML/EditModeManager.lua"]:223: in function <Interface/FrameXML/EditModeManager.lua:220>
[string "=[C]"]: in function `OnLayoutAdded'
[string "@Interface/FrameXML/EditModeManager.lua"]:977: in function `MakeNewLayout'
[string "@Interface/FrameXML/EditModeManager.lua"]:1025: in function `ImportLayout'
[string "@Interface/FrameXML/EditModeDialogs.lua"]:105: in function <Interface/FrameXML/EditModeDialogs.lua:102>
[string "=(tail call)"]: ?
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:1144: in function <Interface/SharedXML/SharedUIPanelTemplates.lua:1140>

Locals: (*temporary) = MainMenuBar {
 0 = <userdata>
 buttonPadding = 2
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:519
 systemInfo = <table> {
 }
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:403
 commandNamePrefix = "ACTION"
 buttonTemplate = "MainBarActionBarButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:197
 actionButtons = <table> {
 }
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:85
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:396
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:237
 buttonArtDirty = false
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:461
 EditModeActionBar_OnHide = <function> defined @Interface/FrameXML/ActionBar.lua:193
 UpdateSystemSettingHideBarArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:488
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:202
 ActionBarPageNumber = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 GetSettingValueBool = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:182
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:186
 OnVisibilityUpdated = <function> defined @Interface/FrameXML/ActionBar.lua:280
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:29
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:370
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:211
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:155
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:197
 dirty = false
 UpdateSystemSettingNumIcons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:450
 UpdateShownButtons = <function> defined @Interface/FrameXML/ActionBar.lua:141
 UpdateDirtySet

If I open the Edit Mode again, this error happen:

![image](https://user-images.githubusercontent.com/9000280/190410761-7731964a-e746-4279-a8b3-2809fb380e0d.png)

Message: Interface/FrameXML/EditModeManager.lua:738: attempt to index field 'accountSettingMap' (a nil value)
Time: Thu Sep 15 09:57:06 2022
Count: 1
Stack: Interface/FrameXML/EditModeManager.lua:738: attempt to index field 'accountSettingMap' (a nil value)
[string "@Interface/FrameXML/EditModeManager.lua"]:738: in function `GetAccountSettingValue'
[string "@Interface/FrameXML/EditModeManager.lua"]:742: in function `GetAccountSettingValueBool'
[string "@Interface/FrameXML/EditModeManager.lua"]:418: in function `ArePartyFramesForcedShown'
[string "@Interface/FrameXML/CompactPartyFrame.lua"]:46: in function `CompactPartyFrame_RefreshMembers'
[string "@Interface/FrameXML/EditModeManager.lua"]:1464: in function `RefreshPartyFrames'
[string "@Interface/FrameXML/EditModeManager.lua"]:1373: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:162: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:183: in function <Interface/FrameXML/EditModeManager.lua:181>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3147: in function `ShowUIPanel'
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:285: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:980: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = EditModeManagerFrame {
 ClearLockedLayoutButton = <function> defined @Interface/FrameXML/EditModeManager.lua:1109
 SetGridSpacing = <function> defined @Interface/FrameXML/EditModeManager.lua:839
 ShouldRaidFrameKeepGroupsTogether = <function> defined @Interface/FrameXML/EditModeManager.lua:508
 RegisterSystemFrame = <function> defined @Interface/FrameXML/EditModeManager.lua:241
 Grid = Frame {
 }
 buttonEntryPool = <table> {
 }
 GetBottomAnchoredActionBarHeight = <function> defined @Interface/FrameXML/EditModeManager.lua:516
 UpdateRightAnchoredActionBarWidth = <function> defined @Interface/FrameXML/EditModeManager.lua:520
 UpdateDropdownOptions = <function> defined @Interface/FrameXML/EditModeManager.lua:858
 ImportLayout = <function> defined @Interface/FrameXML/EditModeManager.lua:1023
 NotifyChatOfLayoutChange = <function> defined @Interface/FrameXML/EditModeManager.lua:609
 HideSystemSelections = <function> defined @Interface/FrameXML/EditModeManager.lua:166
 rightAnchoredActionBarWidth = 0
 ShowNewLayoutDialog = <function> defined @Interface/FrameXML/EditModeManager.lua:1047
 DeleteLayout = <function> defined @Interface/FrameXML/EditModeManager.lua:981
 ClearSelectedSystem = <function> defined @Interface/FrameXML/EditModeManager.lua:599
 AccountSettings = Frame {
 }
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 editModeActive = true
 RevertAllChangesButton = Button {
 }
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeManager.lua:312
 AddRightActionBarToLayout = <function> defined @Interface/FrameXML/EditModeManager.lua:1121
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeManager.lua:410
 OnLoad = <function> defined @Interface/FrameXML/EditModeManager.lua:3
 Layout = <function> defined @Interface/SharedXML/LayoutFrame.lua:319
 OpenAndShowImportLayoutLinkDialog = <function> defined @Interface/FrameXML/EditModeManager.lua:1057
 GetSettingValueBool = <function> defined @Interface/FrameXML/EditModeManager.lua:396
 SetEditModeLockState = <function> defined @Interface/FrameXML/EditModeManager.lua:204
 GetNumRaidMembersForcedShown = <function> defined @Interface/FrameXML/EditModeManager.lua:469
 UpdateLayoutInfo = <function> defined @Interface/FrameXML/EditModeManager.lua:807
 AddNewSystemsAndSet

**Comment by Nevcairiel** [comment]
Please report player-facing issues like this with the Blizzard report tool, as well as on their forums. If QA gets it, it should get sorted quicker.

**Comment by Meorawr** [comment]
Closing per above comments
