### ISSUE TITLE
requesting the macro command castglyph in classic wotlk

### ISSUE THREAD

**Issue by yepeisheng** [Stanzilla/WoWUIBugs#280]
The castglyph command seems removed since the 7.0, but as the wotlk is coming back in the classic, this command should be add back.

**Comment by Witnesscm** [comment]
This command was added in patch 4.0
https://wowpedia.fandom.com/wiki/MACRO_castglyph

You can use this macro command.
```
/use item:42902
/run PlaceGlyphInSocket(1)
```

**Comment by Nevcairiel** [comment]
Considering this command did not exist in original Wrath, and its not affecting addons or the UI in itself, I'm going to close this. If you want to request a macro feature, I would suggest the official forums.
