### ISSUE TITLE
C_Container.GetContainerNumSlots no longer supports containers with negative IDs (bank, reagent bank)

### ISSUE THREAD

**Issue by Nevcairiel** [Stanzilla/WoWUIBugs#288]
The new C_Container.GetContainerNumSlots no longer supports containers with negative IDs

eg.
`/dump C_Container.GetContainerNumSlots(BANK_CONTAINER)`
Results in:
`bad argument #1 to 'GetContainerNumSlots' (outside of expected range 0 to 4294967295 - Usage: local numSlots = C_Container.GetContainerNumSlots(containerIndex))`

This currently affects the bank and reagent bank, but theoretically also the keyring should this API change ever be ported to classic.
This is inconsistent with the old API, and should continue to report values for the inventory size of all containers.

Tested on 10.0.2.45779

**Comment by Meorawr** [comment]
Appears to be resolved in 10.0.2.45969.
