### ISSUE TITLE
SetBindingClick failing silently in Dragonflight

### ISSUE THREAD

**Issue by jnwhiteh** [Stanzilla/WoWUIBugs#291]
I use secure action buttons and BindingClicks to enable some additional keybinds. The following code works correctly on Retail but currently fails on Dragonflight. This assumes a Monk, as Spinning Crane Kick is a simple and easy bind.

```local button = TestSAButton
if not button then
   button = CreateFrame("Button", "TestSAButton", UIParent, "SecureActionButtonTemplate")
end

button:SetAttribute("type-clickbuttonF", "spell")
button:SetAttribute("spell-clickbuttonF", "Spinning Crane Kick")

SetBindingClick("F", "TestSAButton", "clickbuttonF")```

**Comment by Nevcairiel** [comment]
As cleared up on Discord already, this is related to the same issues plagueing all button clicks - missing AnyDown registration (eg. #282 etc), so nothing new to see here really.
