### ISSUE TITLE
GetSpellInfo Returning an 8th (unknown) property

### ISSUE THREAD

**Issue by ChrisKader** [Stanzilla/WoWUIBugs#292]
- `GetSpellInfo("Rake")`
  - Beta
    ![image](https://user-images.githubusercontent.com/633360/193503162-70c67325-ad90-4310-9429-fe5711482b8c.png)
  - Live
    ![image](https://user-images.githubusercontent.com/633360/193503347-a3068b43-f4ce-43f2-92ae-795bff799d05.png)

I am unsure what the 8th property should be as it currently seems to be a repeat of value 3, icon texture ID.

This becomes problematic when doing something like `IsSpellKnownOrOverridesKnown(select(7,GetSpellInfo("Rake")))`. `IsSpellKnownOrOverridesKnown` accepts two arguments and will return false on Beta and PTR as the 8th value of `GetSpellInfo` is sent as the second argument. This can be avoided by declaring a local variable from GetSpellInfo and using it instead of select (probably a better idea from a best practice standpoint). However, this report is more to determine if this 8th value being returned is intended and what it represents.

**Comment by Meorawr** [comment]
This is not the place for documentation requests, and APIs returning new values isn't a bug.

To answer the question: It's the original icon of the spell if it's been replaced by another; eg. if you query Backstab after learning Gloomblade the third return will be the icon file ID of Gloomblade, and the 8th return the original icon file ID for Backstab.

**Comment by Nevcairiel** [comment]
Note that when you want to isolate a single return value, you can wrap the call into extra brackets, eg. `(select(7, GetSpellInfo("Rake")))` will only yield one value, and cut off the 8th.
