### ISSUE TITLE
Client crash when calling Texture:SetMask() using file ID

### ISSUE THREAD

**Issue by LenweSaralonde** [Stanzilla/WoWUIBugs#293]
The beta client (10.0.2.45779) crashes when attempting to set a texture mask using file ID:

```lua
/run local icon = UIParent:CreateTexture(nil, "ARTWORK"); icon:SetSize(64, 64); icon:SetPoint("CENTER"); icon:SetMask(130925); icon:SetTexture(132089)
```
![image](https://user-images.githubusercontent.com/34239920/193511526-da76394f-77cb-4921-97d1-a7dbeb060d8d.png)

On Retail (9.2.7.45745), the texture doesn't show up but the client doesn't crash.

Textures used:
130925	interface/characterframe/tempportraitalphamasksmall.blp
132089	interface/icons/ability_ambush.blp

The macro works as intended by replacing the mask file ID by its actual path:
```lua
/run local icon = UIParent:CreateTexture(nil, "ARTWORK"); icon:SetSize(64, 64); icon:SetPoint("CENTER"); icon:SetMask("interface\\characterframe\\tempportraitalphamasksmall.blp"); icon:SetTexture(132089)
```
![image](https://user-images.githubusercontent.com/34239920/193512300-007c2dcc-7277-46ab-81ee-ba32f0b963d7.png)

I would expect to be able to use `Texture:SetMask()` with file IDs as in `Texture:SetTexture()` without any issue.

**Comment by Nevcairiel** [comment]
This is an assertion, not strictly a crash. Assertions catch bad/unintended use of the API, to notify developers. Assertions are disabled in release builds, and therefor no "crashing", and no risk of crashes on live.

Note that crashes in general (even if this doesn't exactly qualify) should just be reported through their crash reporter with as much detail as needed, as they get those reports directly, and we don't generally track crashes here.

**Comment by Meorawr** [comment]
I'd also suggest using proper MaskTexture regions instead of the effectively-deprecated `Texture:SetMask()` API, since this bug is probably not going to be fixed - per your description of the texture "not showing up" on Retail as-is I suspect you'd find this very same assertion is in-place and would have triggered in 9.x test builds.

**Comment by LenweSaralonde** [comment]
> This is an assertion, not strictly a crash. Assertions catch bad/unintended use of the API, to notify developers. Assertions are disabled in release builds, and therefor no "crashing", and no risk of crashes on live.

Shouldn't this raise a LUA error instead ? On live, this has no effect at all (no error).
