### ISSUE TITLE
POI Arrows don't respect the minimap's size

### ISSUE THREAD

**Issue by ls-** [Stanzilla/WoWUIBugs#294]
Unlike other minimap blips (vendor icons and stuff) and blobs (archaeology and quest zones) these arrows completely ignore the minimap's size and just render at a predetermined radius which may end up being problematic if you're trying to shrink the minimap or something.

![borked arrow](https://user-images.githubusercontent.com/2725970/193834606-9850dfb8-b4e6-4882-86fe-9fd407e9c166.gif)

Forcing the arrow to disappear and reappear or change it's direction by changing tracked quests or flying in and out of the POI radius doesn't change anything.

The same goes for the minimap rotation.

![borked arrow 2](https://user-images.githubusercontent.com/2725970/193835303-39361fa9-6bcd-4d85-9f97-769453474653.gif)

And while on topic of minimap arrows, neither `SetCorpsePOIArrowTexture`, nor `SetPOIArrowTexture`, nor `SetStaticPOIArrowTexture` seem to work. and I tried passing file IDs, atlases, file paths, nothing worked. They do throw errors when you pass some invalid input tho.

**Comment by LouZipher** [comment]
Is it a minimap problem or an addon problem?

**Comment by ls-** [comment]
@LouZipher did you forget to check where you are before asking? You're in `WoWUIBugs`, all the issues gathered here are related to the default UI.

**Comment by weltensturm** [comment]
Can be worked around by scaling the map instead of resizing it, but there should be a way to influence the arrow offset.

**Comment by funkydude** [comment]
> Can be worked around by scaling the map instead of resizing it, but there should be a way to influence the arrow offset.

Scale is not size. Scale also affects everything, including the blips.

This is a bug report not a feature request, we simply want it fixed, we're not looking for "a way to influence the arrow offset". Keep this issue focused on what it is please.

**Comment by weltensturm** [comment]
I am aware that workarounds are rarely the ideal solution.

Minimap masks can be smaller than the frame (or have a thick fading border), but you can account for that with `Set*BlobRingScalar` for blobs. You cannot account for that with a static solution for arrows, but oddly enough with this very bug.

That's why I would prefer bringing arrow functionality up to par with blobs, so both cases can be satisfied.

This would also have the benefit of allowing to keep arrows aligned with the border no matter the minimap shape.

**Comment by Daenarys** [comment]
seems to be fixed in 10.0.5, anyone else can confirm?

**Comment by funkydude** [comment]
Closing this, it should be fixed by Blizzard in patch 10.0.5
