### ISSUE TITLE
C_TooltipInfo.GetBagItem fails with negative container IDs (clamped to 0)

### ISSUE THREAD

**Issue by Nevcairiel** [Stanzilla/WoWUIBugs#296]
Similar to the previous validating errors, the new C_TooltipInfo.GetBagItem does not support negative container IDs (as found in the main bank or reagent bank)

Previously:
`bad argument #1 to '?' (outside of expected range 0 to 4294967295 - Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex))`

New behaviof as of 10.0.2.46144:
The ID seems to get clamped to 0 when you pass a negative ID, giving you information about backpack items instead of bank items.

Example:
`/dump C_TooltipInfo.GetBagItem(-1, 1)`

The impact of this is that it prevents using `ContainerFrameItemButtonMixin` with the bank or reagent bank, as `ContainerFrameItemButtonMixin:OnUpdate` uses `GameTooltip:SetBagItem` to create a tooltip (resulting in a call to `C_TooltipInfo.GetBagItem`)

Tested on 10.0.2.45969, Updated on 10.0.2.46144

**Comment by Nevcairiel** [comment]
This ... changed in 10.0.2.46144. Now the bag ID seems to get clamped to the range, and passing -1 returns infos for ID 0 instead. Still not allowing access to the bank contents.

**Comment by Meorawr** [comment]
Forwarded it on again; I'd assume the next build will fix it.

**Comment by Nevcairiel** [comment]
Seems like this matches 9.x and is intentional.
