### ISSUE TITLE
[8.2.0 PTR] Map icons on Krasarang Wilds offset on world map.

### ISSUE THREAD

**Issue by SinusPi** [Stanzilla/WoWUIBugs#3]
All map icons, from pets through taxis to player location arrow, are displayed in the wrong locations on Krasarang Wilds. Issue present for months now.
Attached: worldmap is wrong, minimap is right.
![image](https://user-images.githubusercontent.com/7799341/57390037-bd48d200-71bb-11e9-8500-68760ecfdb85.png)

**Comment by mednik** [comment]
As far as I remember that was the issue from the time when phasing was introduced there... I'd not hope for a fix.

**Comment by Ketho** [comment]
Don't think they are ever going to fix the map issue...
