### ISSUE TITLE
Tooltip:GetItem is missing modification info when you SetHyperlink a keystone link

### ISSUE THREAD

**Issue by Numynum** [Stanzilla/WoWUIBugs#306]
### Steps to reproduce
Run the following commands (one by one, or in a macro):
```
/run local l=string.format('|cffa335ee|Hkeystone:180653:%d:16:10:1:2:3|h[Keystone]|h|r',C_ChallengeMode.GetMapTable()[1]);SetItemRef(l,l,'LeftButton')
/dump ItemRefTooltip:GetItem()
```

### Description
On live and PTR, GetItem() will return the full item link, including all the itemModification components (the mapID and affixIDs)

However, on beta, GetItem() returns a much shorter link, which is missing all the extra information. 
This means that you cannot cleanly transition from `OnTooltipSetItem` script handlers to `TooltipDataProcessor.AddTooltipPostCall(Enum.TooltipDataType.Item, func)` as seems intended, but instead you have to use workarounds to get the information you're after.
It is worth noting, that the tooltip displayed, is still correct in all the builds.

### Screenshots
Live: 
![image](https://user-images.githubusercontent.com/17293527/196048795-cd89e4a1-7764-423a-b480-06f9d01948f6.png)

PTR:
![image](https://user-images.githubusercontent.com/17293527/196048804-6e837315-c08b-4792-878d-55f7b68f3911.png)

Beta: (note the lack of extra info, the itemLink is much shorter)
![image](https://user-images.githubusercontent.com/17293527/196048821-07208b2d-0a59-46dd-9de3-ab1d8e24d7a5.png)

**Comment by Meorawr** [comment]
This looks fixed as of at-least 10.0.2.46479.

![image](https://user-images.githubusercontent.com/287102/200080120-8b120bba-e806-4da8-aa32-b917d98d6790.png)
