### ISSUE TITLE
Protect UpdateAddOnMemoryUsage() for good

### ISSUE THREAD

**Issue by Tercioo** [Stanzilla/WoWUIBugs#308]
"Naive" addons are showing the memory usage for the user and updating each second.
The game freezes while it calculate the memory usage causing stuttering in the frame rate.
This problem passes unnoticed most of the time as memory is usually low and get problematic after 1 hour of raiding.

Addons should not be able to cause this kind of problem for the end user at all.
Make memory usage be read only from the tooltip where latency is also shown, I  think is called micro menu.

**Comment by funkydude** [comment]
This isn't really the right place for a request like this. Reports should be "straight to the point" bug with reproduction steps or feature and why it's needed. Your request could spawn an entire discussion on 1) why it's an issue and 2) what's the best way to address it, and this isn't the place for that.
