### ISSUE TITLE
RequestRaidInfo broken in Wrath build 46248

### ISSUE THREAD

**Issue by Luckyone961** [Stanzilla/WoWUIBugs#313]
1) You need to be locked to any kind of raid
2) run RequestRaidInfo()
3) UPDATE_INSTANCE_INFO fires
4) Error

```Lua
2x Interface_Wrath\FrameXML\RaidFrame.lua:165: attempt to index a nil value
[string "@Interface_Wrath\FrameXML\RaidFrame.lua"]:165: in function `RaidInfoFrame_Update'
[string "@Interface_Wrath\FrameXML\RaidFrame.lua"]:82: in function <Interface_Wrath\FrameXML\RaidFrame.lua:50>

Locals:
savedInstances = 13
instanceName = "The Obsidian Sanctum"
instanceID = 199663273
instanceReset = 119223
instanceDifficulty = "25 Player"
(for index) = 11
(for limit) = 13
(for step) = 1
i = 11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = true
(*temporary) = nil
(*temporary) = 3
(*temporary) = nil
(*temporary) = "1 |4Day:Days; 9 |4Hr:Hr; 7 |4Min:Min;"
(*temporary) = 3
(*temporary) = "attempt to index a nil value"
```

**Comment by Luckyone961** [comment]
Seems to be fixed in tonights hotfixes

**Comment by Luckyone961** [comment]
false alarm - still broken

**Comment by orionshock** [comment]
Also Point of interest -- 
This file "Interface_Wrath\FrameXML\RaidFrame.lua" dosn't seem to exist. 
Just did a fresh export of the Interface files from the client, and it's not there.

[Seems like the changes on Oct 21 got reverted](https://us.forums.blizzard.com/en/wow/t/wrath-of-the-lich-king-classic-hotfixes-updated-november-2/1323891#:~:text=The%20Raid%20Info%20Frame%20now%20distinguishes%20between%20different%20raid%20difficulties.)

Edit Update:
Did find them as unknown files: 4877746 (RaidFrame.lua) & 4877748 (RaidFrame.xml) on wow.tools -- they only appeared in the 1 patch from Oct20 and then subsequently removed in later patches.

**Comment by Meorawr** [comment]
They weren't removed. The files are shipped and loaded by the current Classic client patch, but they don't update the manifest databases for post-release builds and so they won't be exported.

**Comment by Meorawr** [comment]
I think this was fixed ages ago at this point; at least from the looks of things I suspect the error stemmed from a case where `MAX_RAID_INFOS` was larger than the number of frames which isn't the case in any client today.
