### ISSUE TITLE
bindType for GetItemInfo returns a new value (8) for BoA but NUM_LE_ITEM_BIND_TYPES still returns 5

### ISSUE THREAD

**Issue by seantimm** [Stanzilla/WoWUIBugs#316]
When you call GetItemInfo, the bindType will return a value of 8 for Bind on Account items.  This is outside the bounds of NUM_LE_ITEM_BIND_TYPES (which returns 5).

I would expect NUM_LE_ITEM_BIND_TYPES to be 6 and the value for BoA items to be a bindType of 5 (since these items start at 0).

**Comment by Meorawr** [comment]
(See also #218 for a similar issue where enums and game data don't quite agree).

**Comment by Meorawr** [comment]
Looking into this I can't reproduce this issue - all BoA items I've queried so far seem to be returning a bind type of 1 (`LE_ITEM_BIND_ON_ACQUIRE`). I'll assume this got fixed ages ago.
