### ISSUE TITLE
Color String Stacking Problem

### ISSUE THREAD

**Issue by kodewdle** [Stanzilla/WoWUIBugs#32]
**BETA ONLY**

As noted in [UI Changes](https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#summary): 
> The "|r" escape sequence now pops nested "|c" color sequences in-order, instead of resetting the text to the default color.

Having "|r" pop nested is great however, it would seem an issue has spawned from this specifically when stacking "|c" without additional "|r" along with it.

**The difference in these two:**
Working case does: [color][letter][endcolor] _(for each letter)_
Broken case does: [color][letter][color][letter][color][letter] ... [endcolor] _(only one color end, at the end)_

Broken case:
1) `/run x1 = "\124cffff0000t\124cffe61800e\124cffcd3100s\124cffb44a00t \124cff837b001\124cff6a94001\124cff52ac001\124cff39c5001\124cff20de001\124cff08f6001\124cff00ee101\124cff00d5291\124cff00bd411\124cff00a45a1\124cff008b731\124cff00738b1"`
2) `/run x2 = "\124cff005aa41\124cff0041bd1\124cff0029d51\124cff0010ee1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124cff0000ff1\124r"`
3) `/run print(x1 .. x2)`

![2020-07-27_00-35-08](https://user-images.githubusercontent.com/2266754/88503923-0e034100-cfa1-11ea-83db-648fb318ab5b.png)

Working case:
1) `/run x1 = "\124cffff0000t\124r\124cffe61800e\124r\124cffcd3100s\124r\124cffb44a00t\124r \124cff837b001\124r\124cff6a94001\124r\124cff52ac001\124r\124cff39c5001\124r\124cff20de001\124r\124cff08f6001\124r\124cff00ee101\124r\124cff00d5291\124r"`
2) `/run x2 = "\124cff00bd411\124r\124cff00a45a1\124r\124cff008b731\124r\124cff00738b1\124r\124cff005aa41\124r\124cff0041bd1\124r\124cff0029d51\124r\124cff0010ee1\124r\124cff0000ff1\124r\124cff0000ff1\124r\124cff0000ff1\124r\124cff0000ff1\124r"`
3) `/run x3 = "\124cff0000ff1\124r\124cff0000ff1\124r\124cff0000ff1\124r\124cff0000ff1\124r\124cff0000ff1\124r\124cff0000ff1\124r"`
4) `/run print(x1 .. x2 .. x3)`

![2020-07-27_00-35-47](https://user-images.githubusercontent.com/2266754/88503956-24a99800-cfa1-11ea-8d1e-cd4aa9e4ad94.png)

**Comment by Nevcairiel** [comment]
I'm not sure I would necessarily classify this as an issue. The syntax is basically always a set-reset pair now, and by not including the reset, its incomplete. Its much more deterministic now and more closely matches markup syntax concepts of other text formatting solutions.

**Comment by kodewdle** [comment]
i don't disagree, it makes more sense with it this way. it's just something i ran into with beta where it differs from retail usage in some way :)

**Comment by Stanzilla** [comment]
It's an intentional change
