### ISSUE TITLE
Buff/Debuff Frame Icon-Borders not accessable

### ISSUE THREAD

**Issue by muleyo** [Stanzilla/WoWUIBugs#321]
On Live, PTR and Beta, the Buff and Debuff Frame-Icons and their borders are not accessable/customizable at the moment.

No idea why this has been changed with 10.0, but in 9.2 this was working completely fine...

**Comment by Nevcairiel** [comment]
BuffFrame.auraFrames (a table) contains all active Buffs, you can edit them as you like.
