### ISSUE TITLE
Lua error in Retail when GMChatDialog appear

### ISSUE THREAD

**Issue by KittenBall** [Stanzilla/WoWUIBugs#334]
Message: Interface/AddOns/Blizzard_GMChatUI/Localization.lua:3: attempt to index global 'GMChatStatusFrameDescription' (a nil value)
Time: Sun Nov  6 23:30:09 2022
Count: 1
Stack: Interface/AddOns/Blizzard_GMChatUI/Localization.lua:3: attempt to index global 'GMChatStatusFrameDescription' (a nil value)
[string "@Interface/AddOns/Blizzard_GMChatUI/Localization.lua"]:3: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:688: in function `GMChatFrame_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:2118: in function <Interface/FrameXML/UIParent.lua:1350>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'GMChatStatusFrameDescription' (a nil value)"

**Comment by KittenBall** [comment]
Same with #190 in zh-CN client
https://github.com/Stanzilla/WoWUIBugs/issues/190#issuecomment-968087123

**Comment by Meorawr** [comment]
I *think* this is fixed in 10.0.5 which seems to have possibly removed the zhTW/zhCN-specific localization files for the GM chat UI.
