### ISSUE TITLE
Lua error when delete ignored player if check nothing

### ISSUE THREAD

**Issue by KittenBall** [Stanzilla/WoWUIBugs#335]
Message: Interface/FrameXML/FriendsFrame.lua:1002: Usage: C_FriendList.DelIgnoreByIndex(index)
Time: Mon Nov  7 19:37:45 2022
Count: 4
Stack: Interface/FrameXML/FriendsFrame.lua:1002: Usage: C_FriendList.DelIgnoreByIndex(index)
[string "=[C]"]: in function `DelIgnoreByIndex'
[string "@Interface/FrameXML/FriendsFrame.lua"]:1002: in function <Interface/FrameXML/FriendsFrame.lua:999>

Locals: (*temporary) = nil

Just click friend-ignore tab, and check no one, then click remove button.

**Comment by Meorawr** [comment]
This'll be fixed in 10.0.5.
