### ISSUE TITLE
Partyframe (Raidstyle and normal) pets not visible

### ISSUE THREAD

**Issue by muleyo** [Stanzilla/WoWUIBugs#336]
Pets are not visible at all in the Partyframe, no matter if Raidstyle or normal is in use.

![image](https://user-images.githubusercontent.com/32986026/200306238-2b87104e-d6d3-47e2-8ce2-f41d50689082.png)
![image](https://user-images.githubusercontent.com/32986026/200306026-ce675579-3e7e-4a4e-9bbf-a0acb4e9aacd.png)

**Comment by Nevcairiel** [comment]
This question is better directed at their QA and game design teams, as this may as well be a design decision. I would recommend using ingame feedback tools, or the official forums if you desire pets to be visible.

**Comment by nihilistzsche** [comment]
I'm sorry, but in the screenshot, you can see an option for "Display Pets" that if it was their design to not display pets then why would that option be there?  Them not showing despite the option being checked is clearly a bug, and should be tracked here as well as ingame and the forums.

**Comment by Nevcairiel** [comment]
We track bugs affecting authors, not players.

**Comment by muleyo** [comment]
well doesn't it affect authors if setting the CVar in an addon is useless? x)
