### ISSUE TITLE
The PrimaryProfessionButton checked status does not reset when reload ui if ProfessionsFrame is opend

### ISSUE THREAD

**Issue by KittenBall** [Stanzilla/WoWUIBugs#337]
Same with title

**Comment by Ketho** [comment]
sorry you need to elaborate, this barely counts as a ticket

**Comment by KittenBall** [comment]
https://user-images.githubusercontent.com/22109299/200832976-09d450b8-a808-43b5-a6e4-8152594c73b5.mp4

I'm sorry, just like the video above，the primary profession button's check status does not reset when reload ui if ProfessionsFrame is opening.

**Comment by KittenBall** [comment]
And I think this issue should be open again.

**Comment by Nevcairiel** [comment]
This is an extremely minimal visual glitch, and a player-facing one. Please report it through the ingame tool or on the forums. We don't really track player-facing issues, unless they affect addons.

**Comment by KittenBall** [comment]
I'm sorry.
