### ISSUE TITLE
zhCN locales break Keybindings categories

### ISSUE THREAD

**Issue by warbaby** [Stanzilla/WoWUIBugs#340]
In zhCN client, BINDING_HEADER_MISC is the same as BINDING_HEADER_OTHER, which breaks the follow code:

Interface\FrameXML\SettingDefinitions\Keybindings.lua
```
-- Keybinding sections
local bindingsCategories = {
	...
	[BINDING_HEADER_MISC]			= {order = 10, bindings={}},
	[BINDING_HEADER_OTHER]			= {order = 11, bindings={}},
};
...
for cat, bindingCategory in pairs(bindingsCategories) do
	sortedCategories[bindingCategory.order] = {cat = cat, bindings = bindingCategory.bindings};
end

for _, categoryInfo in ipairs(sortedCategories) do
	...
end
```

The category with "order = 10" is gone, and the later ipair loop stops after 9 items.

We can now only put a line in user addons:
  BINDING_HEADER_OTHER = "some thing else, any thing"

This makes it work, but may cause wired taint issues.  Please let Blizzard know this and help us out, thank you !

**Comment by aby-ui** [comment]
This one can be closed. Thank you.
