### ISSUE TITLE
[Bug]? Tooltip "Enum.TooltipDataType.Spell" and "Enum.TooltipDataType.Item" don't work for macros

### ISSUE THREAD

**Issue by muleyo** [Stanzilla/WoWUIBugs#342]
^Title says it all.

Normal spell in Actionbar: (see SpellID in Tooltip)
![image](https://user-images.githubusercontent.com/32986026/201237734-39004454-078e-466e-8fe9-1fd40360ab0d.png)
Macro: (SpellID missing in Tooltip)
![image](https://user-images.githubusercontent.com/32986026/201237747-ed8588d2-b48e-45ce-8737-85066a510e4a.png)

Item in bag: (see Tooltip Border)
![image](https://user-images.githubusercontent.com/32986026/201237775-f4575523-b9db-4386-9920-e9c890b4aa79.png)

Item in macro: (see Tooltip Border)
![image](https://user-images.githubusercontent.com/32986026/201237808-400694d5-02bb-4a8a-9ddd-63d0aa782bcf.png)

**Comment by Meorawr** [comment]
Not a bug.

**Comment by muleyo** [comment]
How is this not a bug? How are we supposed to change tooltips for macros then?

**Comment by Nevcairiel** [comment]
You use `Enum.TooltipDataType.Macro`
