### ISSUE TITLE
Dragonflight 'GetContainerNumSlots' error message

### ISSUE THREAD

**Issue by Gundulf981** [Stanzilla/WoWUIBugs#347]
Tested on Mac client, no other addons, generates error dialog box at addon load. 
Incredible addon, hope this is of some help. Thank you.

Message: Interface/AddOns/ButtonForge/Util.lua:2190: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Tue Nov 15 21:10:59 2022
Count: 11
Stack: Interface/AddOns/ButtonForge/Util.lua:2190: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/ButtonForge/Util.lua"]:2190: in function `CacheBagItems'
[string "@Interface/AddOns/ButtonForge/EventManager.lua"]:451: in function <Interface/AddOns/ButtonForge/EventManager.lua:414>

Locals: BagItemNameIndexes = <table> {
}
BagItemIdIndexes = <table> {
}
BagItemNameId = <table> {
}
ItemId = nil
ItemName = nil
(for index) = 4
(for limit) = 0
(for step) = -1
b = 4
(*temporary) = nil
(*temporary) = 4
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"
Util = <table> {
 CreateBlizzardBarWrappers = <function> defined @Interface/AddOns/ButtonForge/Util.lua:650
 VDriverOverride = <function> defined @Interface/AddOns/ButtonForge/Util.lua:945
 LookupEquipmentSetIndex = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2802
 RefreshBarGUIStatus = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1007
 RemoveSpell = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2113
 CallbackFunctions = <table> {
 }
 DeleteProfile = <function> defined @Interface/AddOns/ButtonForge/Util.lua:611
 DockCoords = <function> defined @Interface/AddOns/ButtonForge/Util.lua:874
 ApplySlashCommands = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1362
 ActiveBars = <table> {
 }
 RefreshGridStatus = <function> defined @Interface/AddOns/ButtonForge/Util.lua:986
 LookupItemNameBagSlot = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2236
 LookupItemIdBagSlot = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2244
 RemoveItem = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2300
 SpellMana = <table> {
 }
 InvItemNameIndex = <table> {
 }
 ActiveMacros = <table> {
 }
 TriggerZoneChanged = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2082
 AddToFlash = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1778
 TriggerAuraChanged = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2099
 ActiveItems = <table> {
 }
 AddToRangeTimer = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1766
 SetControlFrameAlphas = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1025
 UpdateBlizzardEnabledBarsMap = <function> defined @Interface/AddOns/ButtonForge/Util.lua:674
 DeallocateBar = <function> defined @Interface/AddOns/ButtonForge/Util.lua:809
 FindClosestPoint = <function> defined @Interface/AddOns/ButtonForge/Util.lua:895
 UpdateMounts602 = <function> defined @Interface/AddOns/ButtonForge/Util.lua:358
 StoreCursor = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1631
 CacheBagItems = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2183
 ForceOffCastOnKeyDown = false
 deepcopy = <function> defined @Interface/AddOns/ButtonForge/Util.lua:456
 LookupCompanion = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2151
 CachePetSpellIndexes = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1904
 BagItemIdIndex = <table> {
 }
 GetTabFrame = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1114
 NewBonusBar = <function> defined @Interface/AddOns/ButtonForge/Util.lua:789
 FindInTable = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1143
 SaveProfile = <function> defined @Interface/AddOns/ButtonForge/Util.lua:558
 Critters = <table> {
 }
 GetButtonActionInfo = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2605
 DelayedRefreshMacros = true
 RemoveMacro = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2401
 AddBonusAction = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2328
 ProcessSlashCommandParams = <function> defined @Interface/AddOns/ButtonForge/Util.lua:1168
 UnregisterCallback = <function> defined @Interface/AddOns/ButtonForge/Util.lua:2575
 RefreshTab = <function> defined

**Comment by kemayo** [comment]
This is an issue with the addon [ButtonForge](https://www.curseforge.com/wow/addons/button-forge). This repo is for tracking issues entirely with the base WoW UI. In this case, this is the addon not having been updated for the API changes in 10.0.2, and the fix is for the addon to get updated.

**Comment by Gundulf981** [comment]
my apologies; thanks for the clarification!
