### ISSUE TITLE
C_LossOfControl.GetNumEvents() fails in 9.0.1

### ISSUE THREAD

**Issue by JD-Softcode** [Stanzilla/WoWUIBugs#35]
Call to C_LossOfControl.GetNumEvents() that worked in 8.3 now returns a null pointer exception in 9.0.1 beta.

**Comment by Meorawr** [comment]
Can you clarify what you mean by "null pointer exception" in this case? 9.0.1 has outright removed that function, so there's nothing to call which would generate any form of segfault/access violation.

**Comment by Nevcairiel** [comment]
Indeed, C_LossOfControl was entirely reworked. You likely want C_LossOfControl.GetActiveLossOfControlDataCount instead.
