### ISSUE TITLE
C_Container.GetContainerItemInfo returns itemCount as nil

### ISSUE THREAD

**Issue by Walkerbo** [Stanzilla/WoWUIBugs#350]
C_Container.GetContainerItemInfo is meant to return the itemCount of items from their position in a bag slot 
[https://wowpedia.fandom.com/wiki/API_C_Container.GetContainerItemInfo](https://wowpedia.fandom.com/wiki/API_C_Container.GetContainerItemInfo)
Prior to 10.2 the itemCount was returned as expected, since 10.2 the itemCount returns nil

**Comment by mbattersby** [comment]
The API documentation doesn't list itemCount as an expected field in the ContainerItemInfo struct. Based on the diff the field you want is called stackCount. Not a bug.

```
-               local _, itemCount, locked = GetContainerItemInfo(container, self:GetID());
+               local info = C_Container.GetContainerItemInfo(container, self:GetID());
+               local itemCount = info.stackCount;
+               local locked = info.isLocked;
```

**Comment by Walkerbo** [comment]
@mbattersby I can't believe I missed that C_Container.GetContainerItemInfo actually returns a table now.
I will close
