### ISSUE TITLE
ActionButton SpellActivationAlert glow anim gets stuck

### ISSUE THREAD

**Issue by mbattersby** [Stanzilla/WoWUIBugs#358]
There's a race condition of some sort in the new non-shared ActionButton SpellActivationAlert/OverlayGlow introduced in build 46702, where the AnimIn gets stuck and the  overlay glow is left scaled large for a second or two and not animated in.

![image](https://user-images.githubusercontent.com/1300207/204167050-91bca813-c940-4b41-a7e0-05192aea09f2.png)

![image](https://user-images.githubusercontent.com/1300207/204167099-30e0726d-272c-4866-998c-d5d52c491a4d.png)

The most reliable way to trigger this is to macro a spell that gets a glow (easiest is warrior Victory Rush, not talented into Impending Victory) where a mod key will switch it to another spell. E.g.,
```
/cast [mod:alt] Taunt
/cast Victory Rush
```
then trigger the glow and hit the modifer key a few times to catch the AnimIn at the right point.

You could probably also argue that the AnimOut and new AnimIn shouldn't play when the action changes due to modifier, but that's not part of the bug.

**Comment by mbattersby** [comment]
Theses are not my screenshots but I can reproduce the issue with no addons.

There is also some discussion about it [in this reddit post](https://www.reddit.com/r/WowUI/comments/z68i8p/button_proc_glow_bug_help/).

Present in retail 46741, have not tested beta but I assume there also.

This can trigger without any macro, that's just the easiest way to force a trigger since you can get the AnimIn to show many times.

**Comment by rakkarage** [comment]
Thanks.

    #showtooltip
    /cast [mod:alt] Taunt
    /cast Victory Rush

1. If you add #showtooltip the the glow disapears when you press alt, THAT PART seems to be working as intended?
2. I thought it might be related to macros or mod/tooltip but seems to happen to normal abilities dragged onto buttons (no macros) too... maybe less often but  still

**Comment by sthdevilish** [comment]
> Present in retail 46741, have not tested beta but I assume there also.

I managed to test it on both PTR and beta when they had different builds than retail, without any addons and default config. It did occur there too.

**Comment by aby-ui** [comment]
Find out the reason how this occurs: (in build 47120)

	local button=ActionButton1 ActionButton_ShowOverlayGlow(button)
	C_Timer.After(.1, function() ActionButton_HideOverlayGlow(button) end)
	--animIn isPlaying, stopped, but OnFinished() not Called
	C_Timer.After(.11, function() ActionButton_ShowOverlayGlow(button) end)
	--animOut isPlaying stopped, but OnFinished() not Called, and the alert frame is still shown, so animIn:Play() is not called

That's the stuck. 

The blizzard overlay codes are changed in build 46702, currently:

	function ActionButton_ShowOverlayGlow(button)
		ActionButton_SetupOverlayGlow(button);

		if button.SpellActivationAlert.animOut:IsPlaying() then
			button.SpellActivationAlert.animOut:Stop();
		end

		if not button.SpellActivationAlert:IsShown() then
			button.SpellActivationAlert.animIn:Play();
		end
	end

	function ActionButton_HideOverlayGlow(button)
		if not button.SpellActivationAlert then
			return;
		end

		if button.SpellActivationAlert.animIn:IsPlaying() then
			button.SpellActivationAlert.animIn:Stop();
		end

		if button:IsVisible() then
			button.SpellActivationAlert.animOut:Play();
		else
			button.SpellActivationAlert.animOut:OnFinished();	--We aren't shown anyway, so we'll instantly hide it.
		end
	end

and before Blizzard fixes this, a work-around is something like:

	hooksecurefunc("ActionButton_SetupOverlayGlow", function(button)
		if button.SpellActivationAlert._abyDone then
			return
		end
		button.SpellActivationAlert._abyDone = 1
		button.SpellActivationAlert.animIn:SetScript("OnStop", button.SpellActivationAlert.animIn:GetScript("OnFinished"))
		button.SpellActivationAlert.animOut:SetScript("OnStop", button.SpellActivationAlert.animOut:GetScript("OnFinished"))
	end)

**Comment by rakkarage** [comment]
https://www.curseforge.com/wow/addons/hide-button-glow
Workaround that hides all glows if u got it handled in wa

**Comment by mbattersby** [comment]
Still a serious bug 6 months later.

**Comment by mbattersby** [comment]
This is a reasonable workaround for now (based on above). Issue occurs if the activation retriggers while the AnimOut is playing.

```lua
if WOW_PROJECT_ID == 1 then

    local function FixBlizzardAnimStuckBug(actionButton)
        local saa = actionButton.SpellActivationAlert
        if not saa.animIn:GetScript('OnStop') then
            saa.animIn:SetScript('OnStop', saa.animIn:GetScript('OnFinished'))
            saa.animOut:SetScript('OnStop', saa.animOut:GetScript('OnFinished'))
        end
    end

    hooksecurefunc('ActionButton_SetupOverlayGlow', FixBlizzardAnimStuckBug)

end
```

**Comment by mbattersby** [comment]
SpellActivationAlert has been redone for 10.1.5 and I believe this is fixed (at least I can no longer reproduce it and the Blizzard code is completely different).
