### ISSUE TITLE
/castsequence macro spams GET_ITEM_INFO_RECEIVED

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#36]
When putting a /castsequence macro on an action button, certain/invalid spells will spam the GET_ITEM_INFO_RECEIVED event. This still affects Classic 1.13.5 and seems fixed on Live.

* https://www.wowinterface.com/forums/showthread.php?t=57405
* http://infobot.rikers.org/%23wowuidev/20190401.html.gz

![image](https://i.imgur.com/MlzZZj6.gif)

![image](https://i.imgur.com/slPaJXp.gif)

**Comment by Ketho** [comment]
To clarify, this bug seems to happen when a castsequence macro with any kind of text is on an action button and stops again after the castsequence macro(s) have been used once.

https://streamable.com/vsrh5c
```
/castsequence Renew
```

**Comment by Ketho** [comment]
It's still happening as of patch 1.13.6; but closing it since this is classic anyway

**Comment by mooreatv** [comment]
Why is it closed? maybe it can be fixed in 1.13.7? (or tbc)

**Comment by RagedUnicorn** [comment]
Still happening in 1.13.7 btw.

`/castsequence Find Herbs, Find Minerals
`

**Comment by Meorawr** [comment]
Fixed in 1.14.0.
