### ISSUE TITLE
Dead selected player is not showing on minimap?

### ISSUE THREAD

**Issue by rakkarage** [Stanzilla/WoWUIBugs#361]
when trying to use my engineering res, since patch, have not been able to see dead players highlighted on minimap?
this used to work and show where they are so i can get close...
they recently changed the tracking options? maybe related? i think there used to be one for players? and dead players maybe? idk
has anyone else noticed this?
please & thanks

edit: sorry, thanks, there is a cvar minimapTrackingShowAll

**Comment by Ketho** [comment]
This is not a valid bug report for this repo, you should report it in-game or in the WoW Bug Report Forum
