### ISSUE TITLE
WorldMapFrame's BountyBoard leaks tainted global

### ISSUE THREAD

**Issue by p3lim** [Stanzilla/WoWUIBugs#366]
`isActivitySet` is leaked from WorldMapBountyBoardMixin's Refresh method.

https://github.com/Gethe/wow-ui-source/blob/532edb9c5c2930dcc60a2f59c48f8fb414652be1/Interface/FrameXML/WorldMapBountyBoard.lua#L152

**Comment by Meorawr** [comment]
I believe this is fixed in 10.0.2.46999 unless I dreamed the diff up.
