### ISSUE TITLE
CharacterFrame Equipment Flyout Manager causes error when equipments are in banks

### ISSUE THREAD

**Issue by aby-ui** [Stanzilla/WoWUIBugs#367]
The reason may be C function "GetInventoryItemsForSlot" and lua function "EquipmentManager_UnpackLocation" dosen't match (not counting REAGENANT_BAG).

Put a Boot into the first item of second bank bag, and run 
/dump GetInventoryItemsForSlot(8, {})
there will be 
{
  [6291713]="[itemlink]",
}
and then 
/print EquipmentManager_UnpackLocation(6291713)
it shows slot = 1, bagID = 5, but the second bank bag id is 6 in DragonFlight.

**Comment by mbattersby** [comment]
EquipmentManager_UnpackLocation is known to be broken. See #343

**Comment by aby-ui** [comment]
> 

oh, thanks, i only searched GetInventoryItemsForSlot for a dupe.
