### ISSUE TITLE
Blizzard_APIDocumentation: cannot access Transmogrify systems by name

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#37]
When looking up Transmogrify api systems in-game, `C_TransmogCollection` and `C_TransmogSets` cannot be accessed directly since they share the same name with `C_Transmog`

For example, clicking on `C_TransmogSets` would instead go to `C_Transmog`

Example: https://imgur.com/JhWjmIu

* https://mrbuds.github.io/wow-api-web/?search=s+transmogrify
* https://github.com/Gethe/wow-ui-source/blob/live/AddOns/Blizzard_APIDocumentation/TransmogDocumentation.lua
* https://github.com/Gethe/wow-ui-source/blob/live/AddOns/Blizzard_APIDocumentation/TransmogItemsDocumentation.lua
* https://github.com/Gethe/wow-ui-source/blob/live/AddOns/Blizzard_APIDocumentation/TransmogSetsDocumentation.lua

**Comment by Meorawr** [comment]
This appears to be fixed in build 9.0.2.36096 where they renamed the systems for TransmogItems and TransmogSets to "TransmogrifyCollection" and "TransmogrifySets".

**Comment by Ketho** [comment]
nice
