### ISSUE TITLE
Secondary unit power display behaves erratically

### ISSUE THREAD

**Issue by weltensturm** [Stanzilla/WoWUIBugs#375]
Occasionally, the secondary unit power display breaks and displays garbage. I am not sure if all secondary unit power is affected, but it's at least Arcane Charges and Combo Points.

What I've noticed on arcane mage:
Charges that should be there are not displayed
Charges that are empty are displayed as filled

![image](https://user-images.githubusercontent.com/811167/209219157-5211596b-4d96-494d-baba-bb16a084cb52.png)

Filling and emptying the charges fixes it _sometimes_, but not always.

I have not found a way to reliably reproduce all cases, but loading screens seem to be involved (returning from LFG/PvP content is a good bet)

Here is a way to temporarily break it (until a charge decays, then it goes back to normal):
1. Gain charges
2. Teleport to Valdrakken
3. Go outside and mount a dragonriding mount

After mounting, the charges are gone (until one decays):
![image](https://user-images.githubusercontent.com/811167/209219404-81258a7f-ed35-4ae5-beee-7b2def6bb2c7.png)

UnitPower returns 3, and yet no charges are displayed.

**Comment by Meorawr** [comment]
Could you re-test on the latest PTR build?

**Comment by weltensturm** [comment]
The Dragonriding case is still there on 10.5.47621, the other cases are so random that I can't really tell

**Comment by Meorawr** [comment]
Fixed in 10.0.7 allegedly.

**Comment by weltensturm** [comment]
https://worldofwarcraft.blizzard.com/en-us/news/23923813/dragonflight-1007-content-update-notes-now-live
![image](https://user-images.githubusercontent.com/811167/227210127-a4117cc1-a734-49a4-a403-02ac04afb237.png)
