### ISSUE TITLE
LUA Error - Classis/WOTLK - No Other Addons

### ISSUE THREAD

**Issue by Joseph-Hale** [Stanzilla/WoWUIBugs#377]
+++Here are the error screens++++
Message: Interface\AddOns\ButtonForge\Util.lua:1972: attempt to index global 'C_Container' (a nil value)
Time: Thu Dec 29 08:36:41 2022
Count: 11
Stack: Interface\AddOns\ButtonForge\Util.lua:1972: attempt to index global 'C_Container' (a nil value)
[string "@Interface\AddOns\ButtonForge\Util.lua"]:1972: in function `CacheBagItems'
[string "@Interface\AddOns\ButtonForge\EventManager.lua"]:456: in function <Interface\AddOns\ButtonForge\EventManager.lua:417>

Locals: BagItemNameIndexes = <table> {
}
BagItemIdIndexes = <table> {
}
BagItemNameId = <table> {
}
ItemId = nil
ItemName = nil
(for index) = 4
(for limit) = 0
(for step) = -1
b = 4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Container' (a nil value)"
Util = <table> {
 CreateBlizzardBarWrappers = <function> defined @Interface\AddOns\ButtonForge\Util.lua:639
 VDriverOverride = <function> defined @Interface\AddOns\ButtonForge\Util.lua:939
 LookupEquipmentSetIndex = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2582
 RefreshBarGUIStatus = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1001
 RemoveSpell = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1898
 CallbackFunctions = <table> {
 }
 DeleteProfile = <function> defined @Interface\AddOns\ButtonForge\Util.lua:600
 IsSpellIdTalentOld = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1714
 ApplySlashCommands = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1342
 ActiveBars = <table> {
 }
 RefreshGridStatus = <function> defined @Interface\AddOns\ButtonForge\Util.lua:980
 LookupItemNameBagSlot = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2018
 LookupItemIdBagSlot = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2026
 RemoveItem = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2082
 SpellMana = <table> {
 }
 InvItemNameIndex = <table> {
 }
 ActiveMacros = <table> {
 }
 StartMacroCheckDelay = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2192
 AddToFlash = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1660
 RefreshCompanions = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1943
 ActiveItems = <table> {
 }
 AddToRangeTimer = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1648
 SetControlFrameAlphas = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1019
 UpdateBlizzardEnabledBarsMap = <function> defined @Interface\AddOns\ButtonForge\Util.lua:663
 DeallocateBar = <function> defined @Interface\AddOns\ButtonForge\Util.lua:803
 FindClosestPoint = <function> defined @Interface\AddOns\ButtonForge\Util.lua:889
 UpdateMounts602 = <function> defined @Interface\AddOns\ButtonForge\Util.lua:356
 StoreCursor = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1548
 CacheBagItems = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1965
 FlashButtons = <table> {
 }
 deepcopy = <function> defined @Interface\AddOns\ButtonForge\Util.lua:445
 LookupCompanion = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1932
 CachePetSpellIndexes = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1814
 BagItemIdIndex = <table> {
 }
 GetTabFrame = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1108
 NewBonusBar = <function> defined @Interface\AddOns\ButtonForge\Util.lua:780
 FindInTable = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1137
 SaveProfile = <function> defined @Interface\AddOns\ButtonForge\Util.lua:547
 GetMountCritter = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2837
 GetButtonActionInfo = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2387
 DelayedRefreshMacros = true
 RemoveMacro = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2183
 AddBonusAction = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2110
 ProcessSlashCommandParams = <function> defined @Interface\AddOns\Butto

+++Truncated+++
+++Start of Page 2+++
Message: Interface\AddOns\ButtonForge\Util.lua:1972: attempt to index global 'C_Container' (a nil value)
Time: Thu Dec 29 08:36:41 2022
Count: 1
Stack: Interface\AddOns\ButtonForge\Util.lua:1972: attempt to index global 'C_Container' (a nil value)
[string "@Interface\AddOns\ButtonForge\Util.lua"]:1972: in function `CacheBagItems'
[string "@Interface\AddOns\ButtonForge\EventManager.lua"]:246: in function <Interface\AddOns\ButtonForge\EventManager.lua:235>

Locals: BagItemNameIndexes = <table> {
}
BagItemIdIndexes = <table> {
}
BagItemNameId = <table> {
}
ItemId = nil
ItemName = nil
(for index) = 4
(for limit) = 0
(for step) = -1
b = 4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Container' (a nil value)"
Util = <table> {
 CreateBlizzardBarWrappers = <function> defined @Interface\AddOns\ButtonForge\Util.lua:639
 VDriverOverride = <function> defined @Interface\AddOns\ButtonForge\Util.lua:939
 LookupEquipmentSetIndex = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2582
 RefreshBarGUIStatus = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1001
 RemoveSpell = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1898
 CallbackFunctions = <table> {
 }
 DeleteProfile = <function> defined @Interface\AddOns\ButtonForge\Util.lua:600
 IsSpellIdTalentOld = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1714
 ApplySlashCommands = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1342
 ActiveBars = <table> {
 }
 RefreshGridStatus = <function> defined @Interface\AddOns\ButtonForge\Util.lua:980
 LookupItemNameBagSlot = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2018
 LookupItemIdBagSlot = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2026
 RemoveItem = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2082
 SpellMana = <table> {
 }
 InvItemNameIndex = <table> {
 }
 ActiveMacros = <table> {
 }
 StartMacroCheckDelay = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2192
 AddToFlash = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1660
 RefreshCompanions = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1943
 ActiveItems = <table> {
 }
 AddToRangeTimer = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1648
 SetControlFrameAlphas = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1019
 UpdateBlizzardEnabledBarsMap = <function> defined @Interface\AddOns\ButtonForge\Util.lua:663
 DeallocateBar = <function> defined @Interface\AddOns\ButtonForge\Util.lua:803
 FindClosestPoint = <function> defined @Interface\AddOns\ButtonForge\Util.lua:889
 UpdateMounts602 = <function> defined @Interface\AddOns\ButtonForge\Util.lua:356
 StoreCursor = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1548
 CacheBagItems = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1965
 FlashButtons = <table> {
 }
 deepcopy = <function> defined @Interface\AddOns\ButtonForge\Util.lua:445
 LookupCompanion = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1932
 CachePetSpellIndexes = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1814
 BagItemIdIndex = <table> {
 }
 GetTabFrame = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1108
 NewBonusBar = <function> defined @Interface\AddOns\ButtonForge\Util.lua:780
 FindInTable = <function> defined @Interface\AddOns\ButtonForge\Util.lua:1137
 SaveProfile = <function> defined @Interface\AddOns\ButtonForge\Util.lua:547
 GetMountCritter = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2837
 GetButtonActionInfo = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2387
 DelayedRefreshMacros = true
 RemoveMacro = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2183
 AddBonusAction = <function> defined @Interface\AddOns\ButtonForge\Util.lua:2110
 ProcessSlashCommandParams = <function> defined @Interface\AddOns\Button

I hope that I did the correctly for showing the errors.

**Comment by Meorawr** [comment]
That's an issue with ButtonForge and not one with the game itself - report it to the author of that addon.
