### ISSUE TITLE
Texture String doesn't inherit alpha correctly.

### ISSUE THREAD

**Issue by kodewdle** [Stanzilla/WoWUIBugs#38]
The problem is that, if you have a frame which alpha is changed from one, that adds a font string, and the text of that font string contains a texture string: The texture string will show until that frame's alpha is adjusted in a **_frame_** (on update tick) after that.

1) `/run x = CreateFrame('Frame', 'Text', UIParent) x:SetPoint('CENTER', UIParent) x:SetSize(100, 100) x:SetAlpha(0) x:Show()`
2) `/run f = x:CreateFontString(nil, 'OVERLAY') f:SetFontObject(GameFontNormal) f:SetText('\124TInterface/FriendsFrame/PlusManz-Horde:16:16\124t test') f:SetPoint('CENTER', x)`
Here after running **2** you should not see the icon, as the parent is alpha zero.
3) `/run f:SetAlpha(0) f:SetAlpha(1)`
This corrects it **only** when it's called in a frame after.

In other words: if you were to try **1** and then: `/run f = x:CreateFontString(nil, 'OVERLAY') f:SetFontObject(GameFontNormal) f:SetText('\124TInterface/FriendsFrame/PlusManz-Horde:16:16\124t test') f:SetPoint('CENTER', x) f:SetAlpha(0) f:SetAlpha(1)` you will see the icon but when you split the `f:SetAlpha(0) f:SetAlpha(1)` into the next frame tick, it will work. There seems to be a bug in how the client is rendering the texture strings.

**Additional:** there is also "test" added to **2** and in the last code string (where we set the texture string) to show that: text renders fine, texture strings do not, even if they are shared in the same text.

**Workaround:** [HERE](https://github.com/tukui-org/ElvUI/compare/ae94d42267...eec888d8f6) this is a more technical way to delay it until the next frame and **reset** the font strings alpha. the only purpose here it to solve the rendering issue by asking the client to rerender the font string on the next frame, after **SetText** or **SetFormattedText**

**Comment by Meorawr** [comment]
This appears to have been resolved at some point - either that or the instructions aren't working. In both cases I'm not seeing the icon appear, so seemingly the alpha is now being respected.
