### ISSUE TITLE
Soft Targeting CVar "SoftTargetInteractRange" appears to have no functionality on Wrath 3.4.1 for objects

### ISSUE THREAD

**Issue by Yakehira** [Stanzilla/WoWUIBugs#383]
On Wrath 3.4.1.47720 it's currently not possible to change the distance of soft targeting interacting for objects over the SoftTargetInteractRange CVar for use with Interact Target keybind. Attempting to use the interact keybind with a Fishing Bobber for example can fail due the distance being too low even after setting the SoftTargetInteractRange value higher.

**Comment by Duugu** [comment]
It is possible to change the value, but it is restricted to 0-15. Values above 15 lead to an effective range of 15.

**Comment by Meorawr** [comment]
As this one's stale and has the noted behaviour of being capped at 15 yards I'm going to assume this is intentional.
