### ISSUE TITLE
Retail UNIT_AURA Event

### ISSUE THREAD

**Issue by doadin** [Stanzilla/WoWUIBugs#386]
So maybe its just me but I am using this code in retail:

```
RegisterEvent("UNIT_AURA", "UpdateUnitAuras")

function UpdateUnitAuras(event, unit, updatedAuras) --event, unit, updatedAuras
    if (not updatedAuras.isFullUpdate and not updatedAuras.addedAuras and not updatedAuras.updatedAuraInstanceIDs and not updatedAuras.removedAuraInstanceIDs) then
        print(event," ", unit,  " Its Happening")
    end
end
```

And it is firing every second seemingly per unit, hard to keep track it fires a lot per second in 40 man world boss raid.(with raidX as unit) When solo it seems to fire once per second even when it appears my auras are not changing.(with unit "player" and I'm not gaining or loosing any buffs/debuffs and I only have 6 permanent buffs ex. Buff "Precious's Ribbon" from the shirt of the same name)

So I guess I have 2 questions:

1. Why is it firing for myself(unit "player") when my auras are not changing?
2. If its not a isFullUpdate or addedAuras or updatedAuraInstanceIDs or removedAuraInstanceIDs,(DevTools_Dump(updatedAuras) only contains "isFullUpdate = false"), how am I supposed to treat this event? If there is no info provided what do I do ignore it? If I am supposed to use it doesn't that go against the whole point of making the event more efficient by providing info so I don't have to check all the units auras? And if I am that would be very inefficient since it fires once a second per unit, so checking all auras of 40 units every second, that can't be right?

**Comment by Stanzilla** [comment]
Hey, that does not sound like an actual bug for the UI team to investigate, what you are seeing is most likely the event firing because the index changes.

**Comment by doadin** [comment]
@Stanzilla Ah I see, so can just be safely ignored and doesn't line up visually with the default Buff frame? I would think with only permanent or no duration buffs not even the index would change but maybe not.
