### ISSUE TITLE
Addon Compartment: Strip markup prior to sorting

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#399]
The addon compartment dropdown list as of recent 10.1.0 builds attempts to sort its contents via a case-insensitive comparison of the text for each dropdown menu entry, however this still poses an issue with the numerous addons that are using UI escape sequence markup like `|c` color codes as prefixes to their addon titles.

It would be nice if a generic function could be made available to the environment that would strip all markup sequences from a string, and then plugged into the sort comparator for the addon compartment prior to the case-insensitive comparison taking place. Note that this needs to apply to ideally **all** markup sequences and not just colours, as some addons are using `|T` texture sequences as well for example.

It would also be nice if a similar change could also be made to the addon list, which has suffered from this problem for much longer - see below where all the addons are nicely alphabetical, but ElvUI and DBM (which uses the title `|cffffd200Deadly Boss Mods|r |cff69ccf0Core|r`) get pushed to the bottom.

![image](https://user-images.githubusercontent.com/287102/225174419-283ab28c-4c62-4428-b28e-b2ea8a532d01.png)

**Comment by Meorawr** [comment]
Resolved in 10.1.0.48661.

**Comment by Stanzilla** [comment]
@Meorawr for addon list as well or only compartment?

**Comment by Meorawr** [comment]
Compartment.
