### ISSUE TITLE
Addon Compartment: Add OnEnter/OnLeave and right-click support to menu entries

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#402]
With the new TOC-based metadata fields for the addon compartment we've got support for running an addon-provided function on left-click of an entry in the dropdown menu, however some addons today provide multi-function minimap buttons that perform different actions based on a left or right click, or with certain modifiers held, and would show a tooltip detailing what actions take place on certain click types.

These would be difficult to integrate into the compartment as-is. It may - as a distant goal - be useful as such to add the following fields to the dropdown entry `info` tables managed within the OnLoad handler of the compartment:

* `info.funcOnEnter = <function>` - Should call an addon-provided OnEnter function for showing a tooltip. Use of a function here is preferred since some addons will have complex tooltip requirements - such as showing a custom frame instead of a simple GameTooltip.
* `info.funcOnLeave = <function>` - As above, but for OnLeave.
* `info.registerForRightClick = true` - Enables right-clicking for dropdown menu entries. This should be accompanied with a change that additionally passes through the clicked button to the function executed by `info.func` so that addons can respond appropriately.

The OnEnter/OnLeave functions _could_ be implemented through yet more metadata fields (`AddonCompartmentOnEnterFunc`, etc.) however this feels a bit messy. Perhaps the existing `AddonCompartmentFunc` field could be reused here and when called simply gain a prefix argument that indicates the type of action (enter, leave, click) which the addon can then handle appropriately.

**Comment by kemayo** [comment]
It's a stretch, but could we encourage supporting the [LibDataBroker](https://github.com/tekkub/libdatabroker-1-1) spec in its entirety? It's what (almost) every single existing complex addon-button is using, hasn't needed to be changed in the last 15 years, and it'd make for a seamless transition...

**Comment by Meorawr** [comment]
Possibly - it does feel like with the explosion of compartment-related metadata fields (AddonCompartmentFunc, IconTexture, IconAtlas) it may be wise to consolidate these into a single `AddonCompartmentInfo` field that names a globally accessible table with some defined structure to be processed by the compartment.

This does however complicate initialization of the compartment; right now it doesn't require things to be present in the global environment until the button for an addon in the dropdown is actually clicked. Further such a change would conflict with #401; currently load on demand addons appear in the compartment - if these were to now require accessible global tables then they can no longer do so unless they're a demand-loaded component of a larger addon.

My concern with saying "implement LDB" is that it's a bit of complexity growth given it has three distinct methods for handling tooltips, and implementing support for some of the spec would also require further changes to UIDropDownMenu (namely those icon color fields).

That said - _if_ the table route were taken - it would be nice for there to be overlap between the LDB structure and whatever the compartment could support, with room for expansion in the future.

**Comment by Meorawr** [comment]
Implemented in 10.1.0.48776 with `AddonCompartmentFuncOnEnter` and `AddonCompartmentFuncOnLeave`. Additionally mouse button names are now passed through to `AddonCompartmentFunc`, and per #401 if the function is load-on-demand then it will be loaded prior to executing any of these functions if specified.
