### ISSUE TITLE
CreateForbiddenFrame is missing

### ISSUE THREAD

**Issue by miraage** [Stanzilla/WoWUIBugs#407]
Hello. I'm not sure if I should use it, but anyway..

I'm trying to find a workaround for moving `SecureActionButton` in-combat (neither `button:SetAllPoints` nor `button:SetPoint` work in-combat). I found `CreateFramePool`, which allows creating "forbidden" frames by passing 5th argument.

Is it a bug or is this function disabled on purpose as well?

If it's disabled intentionally, then maybe you could suggest a way to achieve my goal?
Currently, I the only option I see currently is to hook into RAM and wow process and override the memory block responsible for `issecure()` function call. Would very appreciate a normal way. Thank you!

**Comment by Nevcairiel** [comment]
Secure/Protected frames are not movable in combat. There is no way around that.
