### ISSUE TITLE
All addons being enabled for newly created toons

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#41]
After creating a new character, all addons are suddenly enabled for that toon. The addon list on the character selection screen would show them as disabled but in-game all addons are loaded anyway.

This issue seemed obvious enough but I'm sorry otherwise for reporting this so close to pre-patch.

* Expected behavior: Only the enabled addons to be loaded as set during the character selection screen.
* Reproduced on:
  * Beta 9.0.2 (35938)
  * PTR 9.0.1 (35944)

Video: https://streamable.com/pan5y6

**Comment by LybrialsGit** [comment]
This bug is a blizzard bug. It happens for everybody I guess.

**Comment by Ketho** [comment]
Can we get some attention to this issue again. It's obligatory now to click "Disable All" addons after creating a new character.

**Comment by Ghostopheles** [comment]
This appears to have been addressed in build 10.2.51425 - newly created characters now use the addons selected in the addon list on the character select screen.

**Comment by Ketho** [comment]
god bless
