### ISSUE TITLE
DressUpModel can't be dressed if SetCustomRace is used

### ISSUE THREAD

**Issue by kemayo** [Stanzilla/WoWUIBugs#42]
It used to be possible to use `DressUpModel.SetCustomRace` to see what items would look like on other races. You can still use it to see your current outfit on any other race/gender combo, but you can no longer try on items.

Try this as anything but a human female:

```LUA
local model = CreateFrame("DressUpModel", nil, UIParent)
model:SetSize(300, 500)
model:SetPoint("CENTER")
model:SetKeepModelOnHide(true)
model:Show()

model:SetUnit("none")
model:SetCustomRace(1, 1) -- human female
model:TryOn("item:128365") -- a distinctive hat
```

You will see a human female model in the center of the screen, wearing whatever your character is currently wearing. It will not be wearing the requested pirate hat.

There is a variant of this where instead of `model:SetUnit("none")` you do `model:SetUnit("player")`:

```LUA
local model = CreateFrame("DressUpModel", nil, UIParent)
model:SetSize(300, 500)
model:SetPoint("CENTER")
model:SetKeepModelOnHide(true)
model:Show()

model:SetUnit("player")
model:SetCustomRace(1, 1) -- human female
model:TryOn("item:128365") -- a distinctive hat
```

The model will be a human female with a messed up skin due to your current race's skin texture being used and (on beta) weird rendering artifacts in the armor. However, it _will_ try on the item:

![image](https://user-images.githubusercontent.com/2187/103443047-d5872380-4c20-11eb-89f5-f5012e57e822.png)

**Comment by Peterodox** [comment]
SetCustomRace has been broken since 8.2.
You want to use the transmog skin to replace the abhorrently displaced skin, but the geometry data is already messed up thus some gears won't be equipped in the right position after you use SetCustomRace. 

On 8.3.7, you may call this before SetCustomRace to avoid the texture issue but you won't be able to change its gears.
> model:SetBarberShopAlternateForm()

Currently, this method won't work on beta.

**Comment by kemayo** [comment]
> SetCustomRace has been broken since 8.2.
Good to know a timeline for it, thanks. The curse of trying to use functionality which is literally unused in the Blizzard UI.

> On 8.3.7, you may call this before SetCustomRace to avoid the texture issue but you won't be able to change its gears.
The `SetUnit("none")` in my example also fixes the skin on live and beta -- it's just that it, too, leaves it in the no-TryOn state.

**Comment by kemayo** [comment]
I edited my description to not mention the untextured-skin issue and added a new screenshot, since that's fixed now we're off beta. I also spelled out the different variants more explicitly.

**Comment by Bananaman** [comment]
Still a bug as of June 26th, 2021. WoW API really needs some "SetCustomModel(race, gender, FACE TEXTURE)" choice lol.

**Comment by Meorawr** [comment]
No longer an issue in 10.1.5 - not because it's been fixed, but because the SetCustomRace API itself has been removed.
