### ISSUE TITLE
debugstack() broken

### ISSUE THREAD

**Issue by shooter-z** [Stanzilla/WoWUIBugs#422]
As of 49190 (10.1 PTR) debugstack() returns only empty result.

**Comment by Meorawr** [comment]
I'll ask for clarification - it works fine within an error handler but it returns nothing outside of one. There's reasoning behind changes to this API but I'd hoped for something that wasn't quite as broad as this.

**Comment by Meorawr** [comment]
I believe - barring unforeseen circumstances - we'll see this change reverted in an upcoming build. Apply usual caveats and don't take my word as a promise of course.

**Comment by Tercioo** [comment]
@Meorawr could you tell us about the thoughts behind this change?

**Comment by Meorawr** [comment]
Basically all that happened was `debugstack` had - among other things - its initial checks synchronized to match that of `debuglocals` and as a result was made to return nothing if called outside of the global error handler.

In a future build that check will be removed from both functions and they'll both work if called outside the global error handler, reasoning being that as per #333 that check was trivially worked around anyway.

**Comment by Meorawr** [comment]
Fixed in 10.1.0.49222.
