### ISSUE TITLE
Missing tooltips for character bag slots on MainMenuBar

### ISSUE THREAD

**Issue by siweia** [Stanzilla/WoWUIBugs#43]
[BagSlotButton_OnEnter in Live](https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/MainMenuBarBagButtons.lua#L77-L97)

[BagSlotButton_OnEnter in Beta](https://github.com/Gethe/wow-ui-source/blob/beta/FrameXML/MainMenuBarBagButtons.lua#L77-L100)

`GameTooltip:SetOwner` is called after `GameTooltip:SetInventoryItem`, which causes the issue.

**Comment by Ketho** [comment]
Fixed on Beta https://github.com/Gethe/wow-ui-source/commit/855309432ade1d490b528463aa9b9fc1636e2de9#diff-42485bbe57b145b8f4af862daa9aad3b
