### ISSUE TITLE
New loot history window just stops working

### ISSUE THREAD

**Issue by stoppableforce** [Stanzilla/WoWUIBugs#439]
With no rhyme or reason, the new loot window will just stop updating results, showing only a single raid encounter's loot drops no matter what the dropdown at the top is changed to. This has happened to a few people (including myself!) just within a normal or heroic raid, and today to another person when moving from LFR wing 1 to wing 2 while the loot window was still open, leading to the following error being thrown over 1400 times:

```
1418x FrameXML/LootHistory.lua:411: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@FrameXML/LootHistory.lua"]:411: in function `UpdateTimer'
[string "@FrameXML/LootHistory.lua"]:405: in function <FrameXML/LootHistory.lua:404>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
```

**Comment by Meorawr** [comment]
I believe this is fixed on the 10.1.5 PTR as of build 50199.
