### ISSUE TITLE
Target/group/raid radius

### ISSUE THREAD

**Issue by Rauka22** [Stanzilla/WoWUIBugs#444]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Y8LNgpy/unknown.png" alt="unknown" border="0"></a>

Group radius doesn't show if target is dead. Previously, the character was a warlock, then deleted it and created a priest, because of this, the radius of the target is incorrectly shown. This bug was fixed a year ago and now it's reappearing.

passed this test, there were no errors, all addons were disabled except for ElvUI and nothing changed
Troubleshooting Steps (ElvUI)
Do these steps in order.
1) Type in chat in game /edebug on
2) Test - Do you still have the issue?
3) If you still have the issue/error - type in chat in game /estatus
4) Upload a full, uncropped screenshot showing the issue and the estatus.
5) If you are finished with debugging, you can enable your AddOns back with: /edebug off

**Comment by Meorawr** [comment]
This looks like an ElvUI issue, not a general UI API one.
