### ISSUE TITLE
FontString "Location" on the "CharSelectCharacterButtonTemplate" unnecessarily reduces the buttons's interactable area

### ISSUE THREAD

**Issue by Peterodox** [Stanzilla/WoWUIBugs#452]
### Context
To display an additional tooltip for returning players (referred to as RPE),  two functions **LocationText_OnEnter** and **LocationText_OnLeave** were assigned to **CharSelectCharacterButtonTemplate.buttonText.Location**. The location text, such as 
Stormwind", will be replaced by "Gear Update" if the character is qualified for RPE service.

### Issue
However, the FontString remains interactable for normal characters, reducing the character select button's interactable area by nearly half. **The button becomes harder to select** because its hit area is much smaller than its visual area.

![ezgif-1-a1960bfc4c](https://github.com/Stanzilla/WoWUIBugs/assets/49627468/127f0ce5-f95d-4f19-ba54-d02d32615707)

### Proposed Solutions

- Dynamically enabling/disabling mouse motion on the FontString, so that it only becomes interactable when the character is qualified.
- Make the FontString non-interactable (as it's always been), and move the RPE tooltip to the parent button's OnEnter script **CharacterSelectButton_OnEnter**

**Comment by Meorawr** [comment]
I believe this is fixed in 10.2.0.
