### ISSUE TITLE
ElvUI Cooldown Text with WeakAuras

### ISSUE THREAD

**Issue by ghost** [Stanzilla/WoWUIBugs#457]
I have a WeakAura that I use ElvUI Cooldown Text for: https://wago.io/WtwVFVDU9, the WeakAura is supposed to show stacks in the middle of the icon at >0 charges, and whenever it reaches 0 stacks it should show the Timer Text from the Display tab.

However, the issue I am having is that only SOMETIMES (I am not able to reproduce it always) the Timer Text does not show up. Clip of this happening: https://youtu.be/8Sa9A7e6jjI. I have checked with the Blizzard cooldown text aswell as with OmniCC and I am not able to reproduce it at all, only happens with the ElvUI Cooldown Text.

**Comment by InfusOnWoW** [comment]
That's most likely a bug in ElvUI then

That you can't reproduce it without ElvUI means that we do run function region:SetHideCountdownNumbers(cooldownTextDisabled) in Icon.lua, and thus ElvUI[1]:ToggleCooldown(cooldown, not cooldownTextDisabled); is called.

Please report the issue to them

**Comment by InfusOnWoW** [comment]
Eh also this is the totally wrong bug tracker to report that. This is not for user reports in random addons.
