### ISSUE TITLE
Items with effect "Run speed increased slightly" crash game when using GetItemStats

### ISSUE THREAD

**Issue by Flamanis** [Stanzilla/WoWUIBugs#471]
Retail client 10.1.7.51237. Occurs with no addons.

Boots such as "Highlander's Mail Greaves" or "Earthen Netherscale Boots".
The 2h staff "Explorer's Walking Stick". (Can't even buy it, instantly crashes on mouseover on vendor)

These items (and others with the effect) will cause a crash when mousing over or comparing with shift+mouseover. You can also trigger the crash by Searching your bag while having the item in your bags. This can also be triggered by addons using GetItemStats.

Any user with these items can be stuck in a crash loop from addons trying to index their gear on startup, until the addon is disabled.

**Comment by Flamanis** [comment]
[2023-09-08 03.08.07 Crash - 28248.txt](https://github.com/Stanzilla/WoWUIBugs/files/12557262/2023-09-08.03.08.07.Crash.-.28248.txt)
[2023-09-08 02.47.19 Crash - 15104.txt](https://github.com/Stanzilla/WoWUIBugs/files/12557264/2023-09-08.02.47.19.Crash.-.15104.txt)
[2023-09-08 02.43.33 Crash - 46728.txt](https://github.com/Stanzilla/WoWUIBugs/files/12557274/2023-09-08.02.43.33.Crash.-.46728.txt)

3 logs from 3 separate crash reasons. Search, Auction House with Shift+Mousover, and Vendor compare.

**Comment by Tercioo** [comment]
Hovered over the pattern and pressed Shift:
![image](https://github.com/Stanzilla/WoWUIBugs/assets/9000280/c24e5299-25c8-4048-8a3d-7298ffe13372)

**Comment by SpareSimian** [comment]
Doesn't crash for me.
![WoWScrnShot_090823_124813_small_for_github](https://github.com/Stanzilla/WoWUIBugs/assets/1709928/27f46498-0a65-4fb3-8108-0e2704a78c49)

**Comment by Flamanis** [comment]
Did you shift+mouseover to force a compare? Or just regular mouseover.

**Comment by Flamanis** [comment]
Seems to be silently fixed. No crashes on comparing on my end. Closing.
