### ISSUE TITLE
10.2.0: Addon compartment doesn't register any addons from TOC metadata

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#473]
In patch 10.2.0 build 51239 the addon compartment fails to register any addons that supply the AddonCompartmentFunc field in their TOC file.

The cause of this appears to be a change to the loadable state of addons at the point when the addon compartment loads; [this call to C_AddOns.GetAddOnInfo](https://github.com/Gethe/wow-ui-source/blob/67a9e4b8f7ed74dfbb13f0f0e3c6ac6c5113912d/Interface/FrameXML/AddonCompartment.lua#L12-L13) within the OnLoad script of the AddonCompartmentFrame is returning `false, "INSECURE"` for `loadable` and `reason` respectively, preventing the compartment from adding any insecure addons to the `registeredAddons` table.

If you execute `/run AddonCompartmentFrame:OnLoad()` by hand after the UI has fully loaded, C_AddOns.GetAddOnInfo will at that point no longer be marking addons as unloadable and the addon compartment populates correctly.

**Comment by zealvurte** [comment]
Seems to be working again in build 51425.
