### ISSUE TITLE
[WRATH PTR] "PIN_FRAME_LEVEL_VIGNETTE" frame level type not working

### ISSUE THREAD

**Issue by maqjav** [Stanzilla/WoWUIBugs#486]
In the current WRATH PTR (3.4.3.51572) the frame level type "PIN_FRAME_LEVEL_VIGNETTE" stopped working. The frames are added to the world map and they are visible only for 0.5 secs (you can barely see them changing of map). Replacing the frame level type by another one like "PIN_FRAME_LEVEL_AREA_POI" it works.

The frames are there, because mouse events keep working, however you cannot see the icon, it seems to be under the world map frame.

This frame level type worked in previous builds of 3.4.3.

Code example:

    MyMixin = CreateFromMixins(MapCanvasPinMixin);

    function MyMixin:OnAcquired()
	    self:UseFrameLevelType("PIN_FRAME_LEVEL_VIGNETTE", self:GetMap():GetNumActivePinsByTemplate("MyTemplate"));
	    ...
    end

**Comment by Meorawr** [comment]
Unsure if this really counts as a bug - 3.4.3 has made changes to the map and removed of a whole bunch of pin frame levels that never really made sense for Classic - vignettes included.

**Comment by maqjav** [comment]
Hey Meorawr.
It makes sence, there aren't vignettes in Classic.
I will close the ticket then,
Cheers.
