### ISSUE TITLE
[Wrath Classic 3.4.3] Chat macros throw "attempt to concatenate a nil value" error

### ISSUE THREAD

**Issue by SDPhantom** [Stanzilla/WoWUIBugs#492]
Try to run a macro with `/s test` as an example.

> Message: Interface/FrameXML/ChatFrame.lua:4524: attempt to concatenate a nil value
Stack: Interface/FrameXML/ChatFrame.lua:4524: attempt to concatenate a nil value
[string "@Interface/FrameXML/ChatFrame.lua"]:4524: in function 'ChatEdit_UpdateHeader'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function <Interface/FrameXML/ChatFrame.lua:4845>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/ChatFrame.lua"]:4960: in function 'ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4634: in function 'ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:3015: in function <Interface/FrameXML/ChatFrame.lua:3009>
[string "=[C]"]: in function 'UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:343: in function 'handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:625: in function 'SecureActionButton_OnClick'
[string "*ActionBarFrame.xml:15_OnClick"]:4: in function <[string "*ActionBarFrame.xml:15_OnClick"]:1>

This happens because `ChatEdit_UpdateHeader()` is called on the internal EditBox that's used by the macro system to execute commands. This EditBox has no name, so an error is thrown when trying to access the EditBox header (also doesn't exist) through `_G[editBox:GetName().."Header"]`.

**Comment by Meorawr** [comment]
This is fixed in the PTR build that's just gone up.
