### ISSUE TITLE
Desaturated PlayerModel widgets crash the game

### ISSUE THREAD

**Issue by p3lim** [Stanzilla/WoWUIBugs#51]
The following code with crash the game by doing the following:
- target some random NPC
- enter a vehicle

```lua
local Portrait = CreateFrame('PlayerModel', nil, UIParent)
Portrait:SetSize(50, 50)
Portrait:SetPoint('TOP', 0, -20)
Portrait:RegisterUnitEvent('UNIT_MODEL_CHANGED', 'target')
Portrait:RegisterUnitEvent('UNIT_PORTRAIT_UPDATE', 'target')
Portrait:RegisterEvent('PLAYER_TARGET_CHANGED')
Portrait:RegisterEvent('PORTRAITS_UPDATED')
Portrait:SetScript('OnEvent', function(self)
	if UnitIsVisible('target') then
		self:SetCamDistanceScale(1)
		self:SetPortraitZoom(1)
		self:SetPosition(0, 0, 0)
		self:ClearModel()
		self:SetUnit('target')
	else
		self:SetCamDistanceScale(0.25)
		self:SetPortraitZoom(0)
		self:SetPosition(0, 0, 0.25)
		self:ClearModel()
		self:SetModel([[Interface\Buttons\TalkToMeQuestionMark.m2]])
	end

	Portrait:SetDesaturation(1) -- disable this to prevent crashes
end)
```

Can easily be tested with [this quest](https://www.wowhead.com/quest=59940/the-choppy-booster-mk-5) early on in Exile's Reach on the horde side. Keep the quest giver targeted and enter the vehicle.
Happens in retail, PTR and beta (9.0 basically).

**Comment by p3lim** [comment]
Could possibly be narrowed down further, this was just a simplied example of what I encountered in one of my addons.

**Comment by Meorawr** [comment]
This appears to have been fixed at some point from what I can tell.
