### ISSUE TITLE
ButtonForge has a bug that cause micro stutters and binds stop working. (my first time posting)

### ISSUE THREAD

**Issue by forrestgump1212** [Stanzilla/WoWUIBugs#513]
1x [ADDON_ACTION_BLOCKED] AddOn 'ButtonForge' tried to call the protected function 'IsItemInRange()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `IsItemInRange'
[string "@ButtonForge/Button.lua"]:1970: in function `UpdateRangeTimerItem'
[string "@ButtonForge/Button.lua"]:1982: in function `UpdateRangeTimer'
[string "@ButtonForge/EventManager.lua"]:550: in function <ButtonForge/EventManager.lua:547>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

**Comment by Stanzilla** [comment]
Not a Blizzard UI bug
