### ISSUE TITLE
Enum.SeasonID doesn't include a value for Classic SoD

### ISSUE THREAD

**Issue by maqjav** [Stanzilla/WoWUIBugs#518]
Currently in a SoD server (Wild Growth) the value returned by `C_Seasons.GetActiveSeason()` is 2, however in the enumerator Enum.SeasonID, this ID takes the name Placeholder:

Enum.SeasonID
- 0: NoSeason
- 1: SeasonOfMastery
- **2: Placeholder**
- 3: Hardcore

I know it is a silly change, but the same that it exists SoM, they could add SoD.
Probably in the future this "Placeholder" will be used for another season and then it will cause problems in existing addons where the ID 2 is used for SOD.

**Comment by Meorawr** [comment]
Ideally it would be renamed and an alias added to Blizzard_Deprecated to maintain compatibility. Changing the name of this enumerant now will potentially break addon code that over the past ~4 weeks has started using `Enum.SeasonID.Placeholder`.

**Comment by Meorawr** [comment]
Fixed in 1.15.1 with the addition of `Enum.SeasonID.SeasonOfDiscovery`. There's a deprecation alias that'll allow usages of  `Enum.SeasonID.Placeholder` to keep working.
