### ISSUE TITLE
Wardrobe Help Tip Cannot Be Disabled Due To Missing BitField

### ISSUE THREAD

**Issue by Peterodox** [Stanzilla/WoWUIBugs#523]
The shortcuts help tip on the Appearance-Items UI always comes back when you open that tab.
![HideWardropbeTooltip](https://github.com/Stanzilla/WoWUIBugs/assets/49627468/d96d7acf-062c-45f2-9ae1-95789084f270)

"cvarBitfield" and "bitfieldFlag" were missing from the helpTipInfo so the game cannot flag the tip as read after closing.
The correct bitfield index is `LE_FRAME_TUTORIAL_WARDROBE_TRACKING_INTERFACE`

```
function WardrobeCollectionTutorialMixin:OnLoad()

	self.helpTipInfo = {
		text = WARDROBE_SHORTCUTS_TUTORIAL_1,
		buttonStyle = HelpTip.ButtonStyle.None,
		targetPoint = HelpTip.Point.BottomEdgeLeft,
		alignment = HelpTip.Alignment.Left,
		offsetX = 32,
		offsetY = 16,
		appendFrame = TrackingInterfaceShortcutsFrame,
	};

end
```

[Code](https://github.com/Gethe/wow-ui-source/blob/45cb43fde1273ac34a6238cd5c1a377013067049/Interface/AddOns/Blizzard_Collections/Blizzard_Wardrobe.lua#L2955)

**Comment by Ketho** [comment]
Fixed in [10.2.5 (53040)](https://github.com/BigWigsMods/WoWUI/commit/fe83d54bad4af28c4770b6420de954ed767fcaf6)
