### ISSUE TITLE
C_ChatInfo.SendAddonMessage with chatType WHISPER does not work on connected realms

### ISSUE THREAD

**Issue by papa-smurf** [Stanzilla/WoWUIBugs#535]
Using `C_ChatInfo.SendAddonMessage` with chatType `"WHISPER"` does not work on (all?) of Era's connected realms and according to reports (I haven't tested this personally) retail is not spared either.

I've tested this on classic era on the following realms: Mograine, Ashbringer and Bloodfang (EU)
I've also received multiple reports from players on American connected realms reporting the same issue.

Sending messages on PARTY/RAID works as expected.
Sending `WHISPER` addon messages to players on the same realm also works as expected.

There are no `CHAT_MSG_ADDON` events on the recipient's end whatsoever

**Comment by Meorawr** [comment]
Can confirm this is broken on retail, and that people who play on French RP servers are rather perturbed by this bug.

**Comment by LenweSaralonde** [comment]
It's also broken on PTR, even when sending to a player who is on the same realm.
Tested on Benedictus, build 10.2.7.54366

**Comment by Meorawr** [comment]
This was fixed with 10.2.7.
