### ISSUE TITLE
Voice Chat Volume requires number type, not nil

### ISSUE THREAD

**Issue by papa-smurf** [Stanzilla/WoWUIBugs#536]
Client: Version 1.15.1.53623
OS: Windows 11 - Home
Realm: Mograine-EU

On a completely fresh classic era install, with 0 add-ons, on first boot, I get the following lua error:

![image](https://github.com/Stanzilla/WoWUIBugs/assets/4224975/44fb390c-f817-4424-aae7-767939cf0681)

It doesn't persist after a `/reload` or reboot

**Comment by Meorawr** [comment]
I suspect this has been fixed with 1.15.4 as there were some settings changes to deal with voice chat being slow to initialize.
