### ISSUE TITLE
Microbar Ticket-Post-Symbol bugged

### ISSUE THREAD

**Issue by K3ndoo** [Stanzilla/WoWUIBugs#539]
The microbar ticket-symbol is in a weird position and you can't change it. (Screenshot 1).
You can change the position of the microbar itself, but not the symbol (Screenshot 2).
When you put the microbar on mouseover, the symbol will be hidden at least (Screenshot 3).

![image](https://github.com/Stanzilla/WoWUIBugs/assets/92563515/5b2d5438-00f0-439c-8738-af51e3e6dca8)
![image](https://github.com/Stanzilla/WoWUIBugs/assets/92563515/67a41e1b-014d-4fb0-b51d-7d825dfc8624)
![image](https://github.com/Stanzilla/WoWUIBugs/assets/92563515/75efbc9e-b3e0-4ae8-ab1f-979304af1126)

**Comment by K3ndoo** [comment]
Problem already seems to be worked on.

**Comment by Ketho** [comment]
This is an issue tracker for Blizzard bugs, not for addons
(woops misclicked)
