### ISSUE TITLE
C_Item.EquipItemByName() slot parameter not functioning correctly (as of 10.2.6)

### ISSUE THREAD

**Issue by Slackluster** [Stanzilla/WoWUIBugs#541]
The optional `slot` parameter is not working as intend anymore since the application of the 10.2.6 patch.

**Previous and intended behaviour (pre-10.2.6)**
Specifying a slot by its `InvSlotId` in `EquipItemByName()` would equip the item in the specified slot if appropriate, or return a "That item does not go in that slot" error.

**Current behaviour (10.2.6)**
Specifying a slot by its `InvSlotId` in `C_Item.EquipItemByName()` returns a "That item does not go in that slot" error, even when the proper slot number is specified. Specifying one number lower however, does equip the item.

**Example testing**
`GetInventorySlotInfo("FEETSLOT")` returns an `InvSlotId` of `8`
`/run C_Item.EquipItemByName("Nimblefinger Boots", 8)` returns the "That item does not go in that slot" error.
`/run C_Item.EquipItemByName("Nimblefinger Boots")` equips the item as expected.
`/run C_Item.EquipItemByName("Nimblefinger Boots", 7)` equips the item, despite the wrong slot number being specified.

**Comment by hollo6** [comment]
It seems the slot numbering got messed up, shifted by -1.
For example, INVSLOT_BACK translates to 15 but this function requires 14 for a back to equip.

**Comment by zeptognome** [comment]
Fixed on 10.2.7.54171 PTR
