### ISSUE TITLE
Targeted units nameplates do no longer show up beyond `nameplateMaxDistance` since 10.2.6

### ISSUE THREAD

**Issue by cont1nuity** [Stanzilla/WoWUIBugs#542]
Previous to 10.2.6 the nameplate of a unit would be shown when targeted regardless of range to the unit. It showed when you were able to see/target the unit in all cases.
This is no longer the case and likely a change introduced for Plunderstorm to not be able to see the nameplate of far away players.

**Comment by Tercioo** [comment]
I can confirm this bug is still happening.

**Comment by Yakehira** [comment]
Looks like this was recently fixed, no longer encountering this bug.
