### ISSUE TITLE
Keybinding STARTATTACK missing argument, lua error [retail]

### ISSUE THREAD

**Issue by mbattersby** [Stanzilla/WoWUIBugs#543]
The keybinding for StartAttack seems to be missing a (new?) required parameter for the StartAttack function.

```
  <Binding name="STARTATTACK" category="BINDING_HEADER_TARGETING">
    StartAttack();
  </Binding>
```

If you bind this and push the key you get this LUA error
```
Message: [string "STARTATTACK"]:1: Usage: StartAttack(name [, exactMatch])
Time: Fri Mar 29 11:15:27 2024
Count: 5
Stack: [string "STARTATTACK"]:1: Usage: StartAttack(name [, exactMatch])
[string "=[C]"]: in function `StartAttack'
[string "STARTATTACK"]:1: in function <[string "STARTATTACK"]:1>

Locals: 
```

**Comment by mbattersby** [comment]
New error in 10.2.6 presumably part of the wowlabs/plunderstorm changes.

**Comment by mbattersby** [comment]
I suspect it should be `StartAttack('target')` though I'm not sure how `STARTATTACK` and `ATTACKTARGET` are supposed to differ.

**Comment by Meorawr** [comment]
Reasonably sure this has been fixed at this point; recall seeing a change in the diffs to make the parameter optional.

**Comment by mbattersby** [comment]
Definitely fixed as of 10..2.7.
