### ISSUE TITLE
C_ChallengeMode.GetDungeonScoreRarityColor and related functions always return nil [retail]

### ISSUE THREAD

**Issue by mbattersby** [Stanzilla/WoWUIBugs#544]
Starting with today's retail build (10.2.6.53989) `C_ChallengeMode.GetDungeonScoreRarityColor` returns nil for all inputs instead of the correct rarity color for the M+ rating score.

Affects the Blizzard LFG ChallengesFrame ("Mythic+ Dungeons" tab), and any addons relying on it.

**Comment by eltreum0** [comment]
Not only `C_ChallengeMode.GetDungeonScoreRarityColor` but also `C_ChallengeMode.GetSpecificDungeonScoreRarityColor` and `C_ChallengeMode.GetSpecificDungeonOverallScoreRarityColor` return nil when any score is supplied

**Comment by KyrosKrane** [comment]
As reported in https://github.com/SavedInstances/SavedInstances/issues/828, `C_ChallengeMode.GetKeystoneLevelRarityColor()` is similarly affected.  It is returning `nil` for any integer value or any string value that can be coerced into an integer, and throws an error for any other value. The in game error message from testing the command indicates that the parameters haven't changed from what's documented on the wiki.

**Comment by Numynum** [comment]
Seems to have been fixed (confirmed on EU)
Edit: confirmed broken on US 🤔

**Comment by KyrosKrane** [comment]
> C_ChallengeMode.GetKeystoneLevelRarityColor()

As of today's patch, this function is again returning data instead of nil.

**Comment by eltreum0** [comment]
`C_ChallengeMode.GetDungeonScoreRarityColor`, `C_ChallengeMode.GetSpecificDungeonScoreRarityColor` and `C_ChallengeMode.GetSpecificDungeonOverallScoreRarityColor`  all seem to be working again
