### ISSUE TITLE
EnableAddOn() does not enable account-wide

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#55]
In the in-game addon list, enabling/disabling an addon does not affect your other characters. For example I'm disabling an addon for "All" and then relogging to a different character to see that addon is still enabled: https://streamable.com/t4u8o3

On another note, the second argument of `EnableAddOn()` does not seem to work, when passing a character name or `true` the addon will not be enabled for that/all characters.

Tested on Live 9.0.1 (36492) and Beta 9.0.2 (36492)

**Comment by Meorawr** [comment]
Reopening for re-test in the next build.
