### ISSUE TITLE
`C_Spell.GetSpellInfo` returns swapped values for `minRange` and `maxRange` in TWW Alpha

### ISSUE THREAD

**Issue by cont1nuity** [Stanzilla/WoWUIBugs#557]
`C_Spell.GetSpellInfo` returns swapped values for `minRange` and `maxRange`, showing range as 25-0 instead of 0-25:

![image](https://github.com/Stanzilla/WoWUIBugs/assets/10164755/bdc2aaa2-7efb-4910-9e15-5f81b5b272c1)

**Comment by Meorawr** [comment]
![image](https://github.com/Stanzilla/WoWUIBugs/assets/287102/e469794c-dcd0-463b-b24b-a612af6a93b8)

Seems to have been fixed in one of the builds.
