### ISSUE TITLE
Gametooltip SetHyperlink crashes the client

### ISSUE THREAD

**Issue by shooter-z** [Stanzilla/WoWUIBugs#558]
Using Sethyperlink with some items results in ACCESS_VIOLATIONS error.
One item that does it for me is Keeshan's Bandana.

Repro steps:
`/run GameTooltip:SetHyperlink("item:60734::::::::80:::::::::")`
wait a second or two for item to be cached
`/run GameTooltip:SetHyperlink("item:60734::::::::80:::::::::")`

version: 4.4.0.54377, Cataclysm Beta

**Comment by Meorawr** [comment]
While normally we'd just close crash tickets on account of reports getting automatically submitted, I'll keep this one around (as with #556) due to the potential impact as people start testing their stuff in the current Classic build.

**Comment by Meorawr** [comment]
Fixed in 4.4.0.54427.
