### ISSUE TITLE
IsAdvancedFlyableArea() always returns false for characters below 70

### ISSUE THREAD

**Issue by mbattersby** [Stanzilla/WoWUIBugs#568]
Seems to have broken in today's build 10.2.7-54630.

Also affects "Summon Random Favorite Mount" / C_MountJounal.SummonByID(0) for characters below 70, where only flying mounts will be summoned and never dragonriding mounts.

**Comment by mbattersby** [comment]
Possibly (likely?) only affects characters that previously relied on the account-wide unlock, and may not affect characters that did the unlock quests directly.

**Comment by Malivil** [comment]
Something that we were discussing in the linked issue -- It was found on a WoW Forum thread that deleting the Cache folder fixes this problem. I was able to verify that myself that doing so does resolve the issue, though it's unclear why that is necessary.

**Comment by mbattersby** [comment]
Gonna close this, I guess it's fixed for everyone by now with TWW release resetting the cache.
