### ISSUE TITLE
ClearClampedTextureRotation() throws an error when calling SetClampedTextureRotation()

### ISSUE THREAD

**Issue by SDPhantom** [Stanzilla/WoWUIBugs#57]
**ClearClampedTextureRotation()** doesn't send its _**texture**_ argument to **SetClampedTextureRotation()**. It ends up calling `SetClampedTextureRotation(0);` which throws an attempt to index a number error.

This error occurs on both classic and retail clients at the following locations.

Classic 1.13.6.36714:
SharedXML\Util.lua:97

Retail 9.0.2.36753:
SharedXML\TextureUtil.lua:77
SharedXML\Util.lua:107

**Comment by Meorawr** [comment]
This is on the radar to be looked at Soon™ and should be resolved for both TBC and Retail we hope. Unsure on Classic at present.

**Comment by Meorawr** [comment]
For TBC this has been fixed in build 38225, I'll remove the label for that but keep it open until we see this trickle down to Retail PTR. Unsure if we'll see this fixed on Classic.

**Comment by Meorawr** [comment]
This should be fixed in an upcoming 9.1 PTR build. The fix has also been applied to Classic, but as 1.13.7 has already launched the timing of when this fix will appear there is nebulous.

**Comment by Meorawr** [comment]
Fixed on Classic as of 1.13.7.38475. Just waiting on 9.1 :)

**Comment by Meorawr** [comment]
For 9.1 this is resolved in 9.1.0.38511.

**Comment by Meorawr** [comment]
As this is fixed in both Classic and BC and will also be fixed in 9.1 I'm going to close this ahead of time to clean up the issue tracker a bit.
