### ISSUE TITLE
BNToastFrame is popping up in the middle of the screen

### ISSUE THREAD

**Issue by JourneyOver** [Stanzilla/WoWUIBugs#570]
It seems that in today's build 10.2.7-54630, there has been an issue where the `BNToastFrame` appears in the middle of the in-game screen.

I've tried troubleshooting by disabling all addons and even using a fresh WTF folder, but the issue persists.

To address this, I've temporarily downloaded an addon called `Drift` to move this frame, as it doesn't seem to be movable through standard means (other option is to just disable the online/offline friends for the time being).

Several people in my guild have mentioned that they are experiencing the same issue, so it seems to be something caused by Blizzard.

**Comment by Meorawr** [comment]
Should be fixed in the (upcoming) 10.2.7.54673 build.
