### ISSUE TITLE
SendAddonMessage can trigger disconnects if sending whispers to cross-realm players with long names

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#573]
Sending a whisper addon message while to a player with long character and realm names can trigger an immediate disconnect. This is particularly easy to trigger with names composed of Cyrillic glyphs on Russian realms.

* The issue appears to only occur if the combined character and realm name (with delimiting "-") exceeds 47 or 48 bytes.
* The disconnect appears to be server-issued; the call to SendAddonMessage returns a success status and can render to the chat frame if you print it prior to getting kicked.
* You need to have seen the player in your area of interest during the current client session. After having seen them once, any messages to the player can trigger the disconnect until you restart your game client.
* Sometimes you may be able to send them one message without disconnecting, and only disconnect if you send a second message. This appears to be the case if you reconnect (_without_ restarting the client) while in a location that doesn't have the target player in your local area of interest.
* The disconnect occurs irrespective of whether or not you qualify their player name with the realm name as part of the SendAddonMessage call.
* The issue can be reproduced with no addons enabled, and also without registering any addon messaging prefixes.

**Comment by MysticalOS** [comment]
something tells me they won't meet that 2 week timer.
just had to push fix to DBM for this here: https://github.com/DeadlyBossMods/DeadlyBossMods/commit/2104182e388481a3660efe6bc85dfb45a2118c83

**Comment by Meorawr** [comment]
@MysticalOS This issue seems to be resolved for addon whispers (but not normal chat ones) as part of this week's maintenance. I'll poke about chat whispers separately and keep the issue open until I hear back.

**Comment by Meorawr** [comment]
Appears to be fully resolved now for both addon and normal chat whispers in 10.2.7.55261 and with weekly server restarts applied.
