### ISSUE TITLE
Opening the main menu breaks achievement micro button tooltip

### ISSUE THREAD

**Issue by ls-** [Stanzilla/WoWUIBugs#588]
Afaik, this issue was introduced in 10.2 (52068). The problem is in the `DisableMicroButtons` function, to fix it [the `AchievementMicroButton.tooltipText = nil;` line](https://github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua#L145) should be removed. It serves no purpose, most likely, it's mistakenly added or it's just a leftover from an earlier dev build.

**Comment by Meorawr** [comment]
Resolved in 11.0.5.56487.
