### ISSUE TITLE
C_TradeSkillUI.GetCategories() when called while Cooking is open returns two categories for "Food of Draenor"

### ISSUE THREAD

**Issue by teelolws** [Stanzilla/WoWUIBugs#59]
Dump: value=C_TradeSkillUI.GetCategories()
[1]=1323,
[2]=1118,
[3]=475,
[4]=342,
[5]=1013,
[6]=90,
[7]=75,
[8]=74,
[9]=73,
[10]=72

The problem is with this part:
[4]=342,
[5]=1013,

They both correspond to Food of Draenor, where 1013 is "Food of Draenor - Header". No other "____ - Header" is returned by this function for any other expansion or any other profession. That entry should not be part of the array.

**Comment by Ketho** [comment]
Yeah it seems to be an empty category. Not sure why it only shows up in the filters menu.

https://streamable.com/dl5a23

![image](https://user-images.githubusercontent.com/1073877/102700480-1446d200-424e-11eb-890d-af2e6bca403a.png)
