### ISSUE TITLE
Modifying any Menu taints `GetPlaystyleString` and taints Advertisement Reports in the LFG frame

### ISSUE THREAD

**Issue by Numynum** [Stanzilla/WoWUIBugs#595]
Steps to reproduce, with 0 addons loaded:

1. `/run Menu.ModifyMenu('MENU_LFG_FRAME_SEARCH_ENTRY', function(owner, rootDescription) rootDescription:CreateTitle('foo') end)`
2. Open the LFG window, premade groups
3. Right-click any group
4. Left-click any group
5. `'*** ForceTaint_Strong ***' tried to call the protected function 'GetPlaystyleString()'`

Edit: actually modifying _any_ menu will cause the above error to manifest

From reading the taintlog, it looks like quite some parts of the scrollbox get tainted, including `LFGListSearchEntry`'s `resultID` property
This also results in blocking LFG advertisement reports, similar to https://github.com/Stanzilla/WoWUIBugs/issues/237

One option, is to unprotect `GetPlaystyleString`, as has been suggested in https://github.com/Stanzilla/WoWUIBugs/issues/195, though this might not help with https://github.com/Stanzilla/WoWUIBugs/issues/237

**Comment by Meorawr** [comment]
This'll be resolved in 11.0.2, so we'll have a few small weeks of blocked action warnings but should be very temporary.

**Comment by Meorawr** [comment]
Resolved in 11.0.2.55789.

**Comment by argium** [comment]
Was this ever fixed by Bliz?  I'm still experiencing problems with addons that modify the LFG tool right click menu tainting report advertisement.
