### ISSUE TITLE
[CATA] Both zh client get frame error when open Community UI

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#597]
zhCN
`Message: ...face/AddOns/Blizzard_GuildControlUI/Localization.lua:16: attempt to index global 'GuildControlUIRankSettingsFrameRosterLabel' (a nil value)`

zhTW
`Message: ...face/AddOns/Blizzard_GuildControlUI/Localization.lua:26: attempt to index global 'GuildControlUIRankSettingsFrameRosterLabel' (a nil value)`

They are same issue: incorrect adjust in localization, should cleaned up outdated content in the localization files.
https://github.com/Gethe/wow-ui-source/blob/classic/Interface/AddOns/Blizzard_GuildControlUI/Localization.lua

**Comment by Meorawr** [comment]
Fixed in 1.15.4.56419 and presumably also 4.4.1 when that appears publicly.
