### ISSUE TITLE
[Vanilla/SOD] The position of the PlayerFrameHealthBarText is incorrect in zhTW/zhCN/koKR client

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#598]
Happened when show status text with value or percent option.
![5G~$K6JIM4M_3 {1TJMA%L7](https://github.com/user-attachments/assets/4d9b3464-1cf2-4c0b-98c0-fda2bd32d192)
![48) 0@DQL1W45_3J}0BD( 9](https://github.com/user-attachments/assets/5f9d34bc-9d42-456f-bf37-42953d5ec669)

https://github.com/Gethe/wow-ui-source/blob/classic_era/Interface/AddOns/Blizzard_FrameXMLBase/Vanilla/Localization.lua#L53
this line should be removed:
`PlayerFrameHealthBarText:AdjustPointsOffset(50, 3);`

**Comment by Meorawr** [comment]
Fixed in 1.15.4.56573 and 4.4.1.56574.
