### ISSUE TITLE
ButtonForge does not load at all after 19JUL2024 "fix"

### ISSUE THREAD

**Issue by Fl1pp3d0ff** [Stanzilla/WoWUIBugs#599]
Date: 2024-07-20 19:43:36
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/ButtonForge/Util.lua line 1953:
   attempt to index field 'SpellBookSkillLineIndex' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ButtonForge/Util.lua"]:1953: CacheSpellIndexes()
   [string "@Interface/AddOns/ButtonForge/EventManager.lua"]:234:
      Interface/AddOns/ButtonForge/EventManager.lua:228
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  KalielsTracker, v6.6.0
  Swatter, v<%version%> (<%codename%>)
  WowheadLooter, v100207
  Ace3, vRelease-r1341
  AceGUI30SelectablePanel, vv1.1
  AddonFactory, v10.2.019
  Altoholic, v10.2.020
  AskMrRobot, v134
  Auctioneer, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.15 (OneMawTime)
  AutoSellMyJunk, v1.4
  AutoSummonRandomFavoritePet, v1.0.0
  BagBrother, v
  Bagnon, v10.2.31
  ButtonForge, v1.2.2.6
  Carbonite, vv10.2.0.8
  CarboniteNotes, vv10.2.0.6
  CPR, v3.1
  DataStore, v2024.06.26
  DataStoreAchievements, v2024.06.23
  DataStoreAgenda, v2024.06.23
  DataStoreAuctions, v2024.06.23
  DataStoreCharacters, v2024.06.23
  DataStoreContainers, v2024.06.26
  DataStoreCrafts, v2024.06.26
  DataStoreCurrencies, v2024.06.23
  DataStoreGarrisons, v2024.05.20
  DataStoreInventory, v2024.06.23
  DataStoreMails, v2024.06.23
  DataStorePets, v2024.05.20
  DataStoreQuests, v2024.06.26
  DataStoreReputations, v2024.06.24
  DataStoreSpells, v2024.06.23
  DataStoreStats, v2024.05.20
  DataStoreTalents, v2024.06.23
  DBMCore, v10.2.54
  DBMCountPackAsmongold, v1.0.21
  DBMCountPackHotS, v1.7.38
  DBMCountPackOverwatch, v1.4.42
  DBMSMGEventsPack, v1.5.37
  DBMSoundEventsPack, v1.6.36
  DBMStatusBarTimers, v10.2.54
  DBMVPVEM, veeae112
  Details, v#Details.12813.158
  DetailsChartViewer, v
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v9.1.BETA.5.15 (OneMawTime)
  GatherMate2, v1.49
  Informant, v9.1.BETA.5.15 (OneMawTime)
  Molinari, v100207.114-Release
  NumPadBar, v10.0.5
  Paste, v10.2.7-20240508_1
  Postal, vv4.1.7
  RCLootCouncil, v3.12.1
  SilverDragon, vv2024.5
  SilverDragonOverlay, vv2024.5
  SilverDragonRangeExtender, vv2024.5
  Simulationcraft, v10.2.7-01
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.15 (OneMawTime)
  Titan, v8.0.15
  titansimulationcraft, vv1.0.5.70100-alpha5
  TitanBag, v8.0.15
  TitanClock, v8.0.15
  TitanCurrency, v10.1.0
  TitanGold, v8.0.15
  TitanGuild, v10.0.0.5
  TitanLocation, v8.0.15
  TitanLootType, v8.0.15
  TitanPerformance, v8.0.15
  TitanRepair, v8.0.15
  TitanReputations, vv1.42
  TitanVolume, v8.0.15
  TitanXP, v8.0.15
  TomTom, vv3.6.4-release
  BlizRuntimeLib v10.2.7.55664(US) <enUS>
  (ck=96b)

Date: 2024-07-20 19:43:36
ID: 2
Error occured in: Global
Count: ∞
Message: Interface/AddOns/ButtonForge/Util.lua line 1953:
   attempt to index field 'SpellBookSkillLineIndex' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ButtonForge/Util.lua"]:1953: CacheSpellIndexes()
   [string "@Interface/AddOns/ButtonForge/EventManager.lua"]:234:
      Interface/AddOns/ButtonForge/EventManager.lua:228
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  KalielsTracker, v6.6.0
  Swatter, v<%version%> (<%codename%>)
  WowheadLooter, v100207
  Ace3, vRelease-r1341
  AceGUI30SelectablePanel, vv1.1
  AddonFactory, v10.2.019
  Altoholic, v10.2.020
  AskMrRobot, v134
  Auctioneer, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.15 (OneMawTime)
  AutoSellMyJunk, v1.4
  AutoSummonRandomFavoritePet, v1.0.0
  BagBrother, v
  Bagnon, v10.2.31
  ButtonForge, v1.2.2.6
  Carbonite, vv10.2.0.8
  CarboniteNotes, vv10.2.0.6
  CPR, v3.1
  DataStore, v2024.06.26
  DataStoreAchievements, v2024.06.23
  DataStoreAgenda, v2024.06.23
  DataStoreAuctions, v2024.06.23
  DataStoreCharacters, v2024.06.23
  DataStoreContainers, v2024.06.26
  DataStoreCrafts, v2024.06.26
  DataStoreCurrencies, v2024.06.23
  DataStoreGarrisons, v2024.05.20
  DataStoreInventory, v2024.06.23
  DataStoreMails, v2024.06.23
  DataStorePets, v2024.05.20
  DataStoreQuests, v2024.06.26
  DataStoreReputations, v2024.06.24
  DataStoreSpells, v2024.06.23
  DataStoreStats, v2024.05.20
  DataStoreTalents, v2024.06.23
  DBMCore, v10.2.54
  DBMCountPackAsmongold, v1.0.21
  DBMCountPackHotS, v1.7.38
  DBMCountPackOverwatch, v1.4.42
  DBMSMGEventsPack, v1.5.37
  DBMSoundEventsPack, v1.6.36
  DBMStatusBarTimers, v10.2.54
  DBMVPVEM, veeae112
  Details, v#Details.12813.158
  DetailsChartViewer, v
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v9.1.BETA.5.15 (OneMawTime)
  GatherMate2, v1.49
  Informant, v9.1.BETA.5.15 (OneMawTime)
  Molinari, v100207.114-Release
  NumPadBar, v10.0.5
  Paste, v10.2.7-20240508_1
  Postal, vv4.1.7
  RCLootCouncil, v3.12.1
  SilverDragon, vv2024.5
  SilverDragonOverlay, vv2024.5
  SilverDragonRangeExtender, vv2024.5
  Simulationcraft, v10.2.7-01
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.15 (OneMawTime)
  Titan, v8.0.15
  titansimulationcraft, vv1.0.5.70100-alpha5
  TitanBag, v8.0.15
  TitanClock, v8.0.15
  TitanCurrency, v10.1.0
  TitanGold, v8.0.15
  TitanGuild, v10.0.0.5
  TitanLocation, v8.0.15
  TitanLootType, v8.0.15
  TitanPerformance, v8.0.15
  TitanRepair, v8.0.15
  TitanReputations, vv1.42
  TitanVolume, v8.0.15
  TitanXP, v8.0.15
  TomTom, vv3.6.4-release
  BlizRuntimeLib v10.2.7.55664(US) <enUS>
  (ck=96b)

**Comment by Ketho** [comment]
This is an addon issue and not related to wow ui bugs
