### ISSUE TITLE
UnitPopup bug that infers with the ability to invite a player from another realm in chat.

### ISSUE THREAD

**Issue by Yakehira** [Stanzilla/WoWUIBugs#6]
When trying to invite a Player from Chat it can fail because when hovering over the 'Report player' option, the -Realm portion of that Player is removed from the `name`, so when trying to Invite someone after hovering over this option, it will fail if that Player is from another realm.

To test:
`/run hooksecurefunc("UnitPopup_ShowMenu", function(_,_,_,name) print(name) end)`

Right-click a player in chat, and hover over the report option. On Init you will get `Player-Realm`, after hovering the report option, it will be `Player` and Invite will attempt to Invite `Player` not `Player-Realm`

Needs testing on 8.2.0 PTR.

**Comment by Ketho** [comment]
Fixed on 9.0.1/9.0.2
