### ISSUE TITLE
Chat frame message configuration is incorrect on fresh logins

### ISSUE THREAD

**Issue by Ghostopheles** [Stanzilla/WoWUIBugs#604]
# The Issue
`GetChatWindowMessages`, despite it's name, does not actually return messages. Instead, it's used by the ChatFrame to fetch the list of chat types it should be listening for, according to the player's server-side (or locally cached) chat config.

Early on in the loading process, this function returns the **default** chat configuration rather than the player's saved config.

As a result of this, when the `UPDATE_CHAT_WINDOWS` event fires, the chat config is not loaded and it results in the ChatFrame using the default chat type list. Coincidentally, this event fires multiple times, and by the last time it fires, it's able to grab the right configuration. However, the ChatFrame has already registered the relevant frame events for the bad configuration from earlier, and it doesn't make any effort to correct it.

# Repro
As of **11.0.2.55789**:
- Log into a character
- Open the chat config and uncheck `SAY`
- Log out and log into a *different* character
- Log out and back over to the first character
- Type in say chat and observe the message appearing in the chat box
- Bonus: Open the chat config and observe the UI correctly reflecting the config state

Toggling the checkbox in the UI fixes the issue until the chat config is evicted.

# Solution
It's probably be easiest to have one of the configuration functions (like `ChatConfig_UpdateCheckboxes`) clean up the unused events on the chat frame.

A more in-depth fix would be ensuring the correct chat configuration is loaded by the time the first `UPDATE_CHAT_WINDOWS` event fires. I believe this was the behavior in the past and why we didn't see this bug before.

**Comment by Meorawr** [comment]
I'm gonna assume 11.0.0.55899 fixes this without testing it.

**Comment by Ghostopheles** [comment]
After 7 hours of procrastination, I can confirm that 11.0.0.55899 fixes this issue (for anyone paranoid).
