### ISSUE TITLE
Private Aura Tooltip error when leaving private aura anchor

### ISSUE THREAD

**Issue by cont1nuity** [Stanzilla/WoWUIBugs#609]
Steps to reproduce:
1) No addons active.
2) Login to PTR 11.0.0
3) Go to Private Aura test training dummies
4) Get Private Auras applied
5) Mouse-Over the default player private aura tracking to show the tooltip of one aura.
6) Leave the aura with the mouse and receive the following error.

Error:
```Message: [string "*Blizzard_PrivateAurasUI.xml:35_OnTooltipCl..."]:1: attempt to call global 'GameTooltip_ClearMoney' (a nil value)
Time: Mon Jul 29 19:34:30 2024
Count: 2
Stack: [string "*Blizzard_PrivateAurasUI.xml:35_OnTooltipCl..."]:1: attempt to call global 'GameTooltip_ClearMoney' (a nil value)
[string "*Blizzard_PrivateAurasUI.xml:35_OnTooltipCleared"]:1: in function <[string "*Blizzard_PrivateAurasUI.xml:35_OnTooltipCl..."]:1>
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/Blizzard_PrivateAurasUI/Blizzard_PrivateAurasUI.lua"]:25: in function <.../Blizzard_PrivateAurasUI/Blizzard_PrivateAurasUI.lua:24>
```

I assume `Blizzard_PrivateAurasUI` is loaded before `Blizzard_MoneyFrame` and `GameTooltip_ClearMoney` is not available when `PrivateAurasTooltip` is created from XML.

**Comment by Elnarfim** [comment]
It has fixed in 11.0.2 as far as I know
