### ISSUE TITLE
[TWW] Non-macro SecureActionButton not clickable by macro

### ISSUE THREAD

**Issue by mqstu7zz** [Stanzilla/WoWUIBugs#610]
Hi, I have learned in TWW we can no longer /click a button with a macro/macrotext. 
But it seems other types of secure action buttons cannot be /clicked either in 11.0.0, like a simple secure button with type="spell".
Is it intentional change to disable all "/click secureButtonX" macros, including non-macro/macrotext ones in TWW?

**Comment by Meorawr** [comment]
This sounds suspiciously like the usual trap of the ActionButtonUseKeyDown CVar and not having RegisterForClicks("AnyUp", "AnyDown") on your secure button.

**Comment by mbattersby** [comment]
Using `pressAndHoldAction` and `typeRelease` is the best workaround for the crappy SABT behaviours introduced in DF.

https://github.com/Stanzilla/WoWUIBugs/issues/317#issuecomment-1510847497

**Comment by mqstu7zz** [comment]
> This sounds suspiciously like the usual trap of the ActionButtonUseKeyDown CVar and not having RegisterForClicks("AnyUp", "AnyDown") on your secure button.

I've used these for a quick test on 11.0 55846 client. It casts the spell when I click the icon, but not with macro "/click test".
```
local button = CreateFrame("Button", "test", UIParent, "SecureActionButtonTemplate")
button:SetHeight(100)
button:SetWidth(100)
button:SetPoint("CENTER")
button:SetAttribute("type", "spell")
button:SetAttribute("spell", "Blitzschlag") -- any spell name here
button:SetAttribute("unit", "target")
button:SetNormalTexture(134414)
button:RegisterForClicks("AnyDown", "AnyUp")
button:Show()
```

**Comment by mqstu7zz** [comment]
> Using `pressAndHoldAction` and `typeRelease` is the best workaround for the crappy SABT behaviours introduced in DF.
> 
> [#317 (comment)](https://github.com/Stanzilla/WoWUIBugs/issues/317#issuecomment-1510847497)

Thanks.  Adding 
```
button:SetAttribute("pressAndHoldAction", true);
button:SetAttribute("typerelease", "spell");
```
after my code fixed it. 👍👍 
Though I am pretty sure I don't need these several months ago.
