### ISSUE TITLE
[TWW] Lua error when clicking travel pass button in FriendsFrame

### ISSUE THREAD

**Issue by Witnesscm** [Stanzilla/WoWUIBugs#611]
https://github.com/BigWigsMods/WoWUI/blob/c67fe840e55f702ae0a49012e7553ee1c8739ff8/AddOns/Blizzard_FriendsFrame/Mainline/FriendsFrame.lua#L2472

This is caused by the travel pass menu using deprecated BN API, which currently prevents inviting BN friends with multiple online accounts.

**Comment by Meorawr** [comment]
This is fixed in 11.0.0.55899.
