### ISSUE TITLE
Guild Applicant History Whisper - ClubFinderApplicantList.lua:547: attempt to call method 'GetSelectedClubId' (a nil value)

### ISSUE THREAD

**Issue by Malivil** [Stanzilla/WoWUIBugs#622]
On the Applicant History page of the Guild window's Roster tab, right-clicking an entry and clicking "Whisper" generates the following error with no addons enabled:

Message: ...Ons/Blizzard_Communities/ClubFinderApplicantList.lua:547: attempt to call method 'GetSelectedClubId' (a nil value)
Time: Thu Aug  8 11:25:57 2024
Count: 1
Stack: ...Ons/Blizzard_Communities/ClubFinderApplicantList.lua:547: attempt to call method 'GetSelectedClubId' (a nil value)
[string "@Interface/AddOns/Blizzard_Communities/ClubFinderApplicantList.lua"]:547: in function `ClubFinderMessageApplicant'
[string "@Interface/AddOns/Blizzard_Communities/ClubFinderApplicantList.lua"]:76: in function <...Ons/Blizzard_Communities/ClubFinderApplicantList.lua:75>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_Menu/Menu.lua"]:854: in function `Pick'
[string "@Interface/AddOns/Blizzard_Menu/MenuTemplates.lua"]:64: in function <Interface/AddOns/Blizzard_Menu/MenuTemplates.lua:58>

Locals: self = Button {
 Class = Texture {
 }
 faction = 1
 Note = FontString {
 }
 ClassName = "Druid"
 Info = <table> {
 }
 Level = FontString {
 }
 RoleIcon2 = Texture {
 }
 CancelInvitationButton = Button {
 }
 ItemLevel = FontString {
 }
 RoleIcon1 = Texture {
 }
 ClassColor = <table> {
 }
 RoleIcon3 = Texture {
 }
 Name = FontString {
 }
 RequestStatus = FontString {
 }
 AllSpec = FontString {
 }
 InviteButton = Button {
 }
}
communityFrame = UIParent {
 variablesLoaded = true
 Tabs = <table> {
 }
 firstTimeLoaded = 1
}
(*temporary) = nil
(*temporary) = UIParent {
 variablesLoaded = true
 Tabs = <table> {
 }
 firstTimeLoaded = 1
}
(*temporary) = "attempt to call method 'GetSelectedClubId' (a nil value)"

**Comment by Meorawr** [comment]
Should be fixed in 11.0.5.

**Comment by Malivil** [comment]
Great! Thanks =)

**Comment by Meorawr** [comment]
Fixed in 11.0.2.56162.
