### ISSUE TITLE
Teleport spells' new overlay leaves an opaque green border

### ISSUE THREAD

**Issue by SinusPi** [Stanzilla/WoWUIBugs#624]
An image instead of a thousand words.
![image](https://github.com/user-attachments/assets/b03c037a-3220-47eb-abdc-d8ad47b3b75e)
That green border should probably be alpha=0, and yet it's there. Happens on every cast of a mage Teleport spell.

**Comment by Nevcairiel** [comment]
Thst doesn't look much like a UI issue. General game issues should be reported using official channels.

**Comment by SinusPi** [comment]
Only FrameXML issues here, not whole-screen visuals. Got it.
