### ISSUE TITLE
Typo in PetConstantsDocumentation.lua "`(int)`"

### ISSUE THREAD

**Issue by mrbuds** [Stanzilla/WoWUIBugs#626]
An incorrect `(int)` break `Blizzard_ApiDocumentationGenerated\PetConstantsDocumentation.lua` in tables `PetConsts_PostCata`, `PetConsts_PreWrath`, and `PetConsts_Wrath`

This affect
- 11.0.2 56071 (beta)
- 11.0.2 55959 (ptr)
- 1.15.3 55917 (classic_era)

This does not affect (yet)
- 11.0.0 55960 (live)
- 4.4.0 56014 (classic)

```Lua
{ Name = "EXTRA_PET_STABLE_SLOT", Type = "number", Value = (int)MAX_SUMMONABLE_HUNTER_PETS },
```

![image](https://github.com/user-attachments/assets/bb39a60c-ae3f-405e-9eed-d56fa4720dc8)

How to reproduce

```
/run C_AddOns.LoadAddOn("Blizzard_APIDocumentation")
/run APIDocumentation_LoadUI()
```

**Comment by mrbuds** [comment]
And now it also affects 11.0.2.56110 (live) :(

**Comment by mrbuds** [comment]
classic_era_ptr 1.15.4 56400 fix this issue

**Comment by rodneycheung** [comment]
retail 56513 the issual is still not fixed

**Comment by ChrisKader** [comment]
As of today, this still impacts 11.0.2.56647 (Mainline/Retail/wow)

**Comment by Meorawr** [comment]
The issue is closed because it's fixed in all current PTR clients; no need to keep pointing out that it's still there on live - this issue isn't important enough to justify a hotfix into any live client.
