### ISSUE TITLE
Combat log names have region appended to them

### ISSUE THREAD

**Issue by funkydude** [Stanzilla/WoWUIBugs#631]
As of 11.0.2, the sourceName (arg 5) and destName (arg 9) delivered by the in game combat log `CombatLogGetCurrentEventInfo()` will have a region appended to it if the player is not from your home server.

e.g. `PlayerName-ServerName-Region`

This seems to be an oversight aimed at improving the advanced combat log (out of game) but should not be applying to the in game combat log.

**Comment by MysticalOS** [comment]
Gross

**Comment by funkydude** [comment]
There will be a fix for this next week.
