### ISSUE TITLE
Secure "macrotext" buttons call a nil global "RunMacroText"

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#642]
In Mainline, the global RunMacroText [was moved to C_Macro.RunMacroText](https://github.com/Gethe/wow-ui-source/blob/703e072b4f993d3242317ee84d6739c80066391b/Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua#L445) as part of the recent kerfuffle around macrotext buttons.

In Classic Era 1.15.4.56400, the API has been similarly relocated but [SecureTemplates.lua hasn't been updated to accomodate this change](https://github.com/Gethe/wow-ui-source/blob/1959db0ba84dca24f844537dd40fcb39a3d821ad/Interface/AddOns/Blizzard_FrameXML/Classic/SecureTemplates.lua#L416) and as such attempts to call the now-nil global.

**Comment by plusmouse** [comment]
This affects the latest Cataclysm PTR too 4.4.1.56464

**Comment by Artemishowl** [comment]
Valid issue, ticket made

**Comment by Meorawr** [comment]
Resolved in 1.15.4.56573. Assuming also fixed in 4.4.1.56574.
