### ISSUE TITLE
Classic Era GetSpellSubtext causes an ACCESS_VIOLATION exception when the spell does not exist in the local cache

### ISSUE THREAD

**Issue by Snakybo** [Stanzilla/WoWUIBugs#662]
After 1.15.4, running `C_Spell.GetSpellSubtext` with any spell ID that has not yet been cached will cause the game to crash.

## Repro steps

1. Log in to a non-Rogue
2. Type and run `/run C_Spell.GetSpellSubtext(8676)`
3. Observe an ACCESS_VIOLATION exception and a game crash

![image](https://github.com/user-attachments/assets/cbc571ea-961e-42bd-813f-cd82ac53555f)

**Comment by skyler-code** [comment]
![image](https://github.com/user-attachments/assets/bf047fdd-e7a2-48c4-8c63-71959a5d6adf)
This issue also exists on Cataclysm PTR 4.4.1.56574

**Comment by skyler-code** [comment]
Issue looks to be fixed in both 1.15.4.56857 and 4.4.1.56859
