### ISSUE TITLE
Detail and Plater LUA errors

### ISSUE THREAD

**Issue by kitethrow** [Stanzilla/WoWUIBugs#668]
These LUA errors only happen when I am playing Windwalker or Brewmaster. I use the same plater/details profiles for those specs as I do Mistweaver but I don't get any errors when playing MW. I have completely deleted and reinstalled these addons and am still getting these errors.

Message: [string "Constructor for Interrupt not ready Cast Co..."]:65: attempt to call global 'GetSpellCooldown' (a nil value)
Time: Fri Oct 11 13:06:42 2024
Count: 1
Stack: [string "Constructor for Interrupt not ready Cast Co..."]:65: attempt to call global 'GetSpellCooldown' (a nil value)
[string "Constructor for Interrupt not ready Cast Color"]:65: in function `GetCastColor'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1042: in function `UpdateCastColor'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1530: in function `UpdateCastingInfo'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1453: in function `PLAYER_ENTERING_WORLD'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1266: in function <Interface/AddOns/Details/Libs/DF/unitframe.lua:1261>
[string "=[C]"]: in function `OnEvent'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1157: in function `SetUnit'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:2207: in function `SetUnit'
[string "@Interface/AddOns/Plater/Plater.lua"]:3484: in function `func'
[string "@Interface/AddOns/Plater/Plater.lua"]:4021: in function <Interface/AddOns/Plater/Plater.lua:4017>

Locals: self = NamePlate1PlaterUnitFrameCastBar {
 isNamePlate = true
 barBorderTextureForMask = Texture {
 }
 BorderShield = Texture {
 }
 extraBackground = Texture {
 }
 HookList = <table> {
 }
 unit = "nameplate9"
 canInterrupt = true
 Colors = <table> {
 }
 unitFrame = NamePlate1PlaterUnitFrame {
 }
 IsCastBar = true
 fadeInAnimation = AnimationGroup {
 }
 spellTexture = 631519
 casting = true
 stagePips = <table> {
 }
 spellName = "Night Bolt"
 maxValue = 2
 barTexture = Texture {
 }
 fadeOutAnimation = AnimationGroup {
 }
 flashAnimation = AnimationGroup {
 }
 Icon = Texture {
 }
 lazyUpdateCooldown = 0.100000
 value = 0
 spellEndTime = 39571.275000
 spellStartTime = 39569.275000
 castID = "Cast-3-3887-2662-4139-431303-000009692F"
 percentText = FontString {
 }
 spellID = 431303
 empowered = false
 PlateFrame = NamePlate1 {
 }
 FrameOverlay = NamePlate1PlaterUnitFrameCastBarOverlayFrame {
 }
 Settings = <table> {
 }
 borderChangeHooked = true
 PixelSnapDisabled = true
 Spark = Texture {
 }
 FadeAnimation = AnimationGroup {
 }
 displayedUnit = "nameplate9"
 CastBarEvents = <table> {
 }
 customborder = Frame {
 }
 castColorTexture = NamePlate1PlaterUnitFrameCastBarCastColor {
 }
 TargetName = FontString {
 }
 FrameDownlayer = NamePlate1PlaterUnitFrameCastBarDownlayerFrame {
 }
 _points = <table> {
 }
 interruptSpellId = 116705
 flashTexture = Texture {
 }
 Text = FontString {
 }
 barTextureMask = MaskTexture {
 }
 WidgetType = "castBar"
 ThrottleUpdate = 0
 background = Texture {
 }
}
(*temporary) = 2
(*temporary) = nil
(*temporary) = 116705
(*temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
noKickReadyColor = "gray"

Message: [string "Constructor for Interrupt not ready Cast Co..."]:65: attempt to call global 'GetSpellCooldown' (a nil value)
Time: Fri Oct 11 13:06:49 2024
Count: 10
Stack: [string "Constructor for Interrupt not ready Cast Co..."]:65: attempt to call global 'GetSpellCooldown' (a nil value)
[string "Constructor for Interrupt not ready Cast Color"]:65: in function GetCastColor'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1042: in function UpdateCastColor'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1530: in function UpdateCastingInfo'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1544: in function eventFunc'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1278: in function <Interface/AddOns/Details/Libs/DF/unitframe.lua:1261>
[string "=[C]"]: ?

Locals: self = NamePlate6PlaterUnitFrameCastBar {
 isNamePlate = true
 barBorderTextureForMask = Texture {
 }
 CanInterrupt = false
 BorderShield = Texture {
 }
 extraBackground = Texture {
 }
 HookList = <table> {
 }
 unit = "nameplate14"
 canInterrupt = true
 Colors = <table> {
 }
 unitFrame = NamePlate6PlaterUnitFrame {
 }
 SpellName = "Darkblade"
 IsCastBar = true
 fadeInAnimation = AnimationGroup {
 }
 spellTexture = 631519
 casting = true
 stagePips = <table> {
 }
 spellName = "Night Bolt"
 maxValue = 2
 barTexture = Texture {
 }
 fadeOutAnimation = AnimationGroup {
 }
 flashAnimation = AnimationGroup {
 }
 Icon = Texture {
 }
 borderChangeHooked = true
 PixelSnapDisabled = true
 ReUpdateNextTick = true
 lazyUpdateCooldown = 0.100000
 IsInterrupted = false
 SpellEndTime = 39570.275000
 SpellStartTime = 39569.275000
 SpellTexture = 368868
 SpellID = 431493
 value = 0
 spellEndTime = 39579.482000
 percentText = FontString {
 }
 spellStartTime = 39577.482000
 castID = "Cast-3-3887-2662-4139-431303-0003896939"
 spellID = 431303
 PlateFrame = NamePlate6 {
 }
 FrameOverlay = NamePlate6PlaterUnitFrameCastBarOverlayFrame {
 }
 Settings = <table> {
 }
 empowered = false
 Spark = Texture {
 }
 FadeAnimation = AnimationGroup {
 }
 displayedUnit = "nameplate14"
 CastBarEvents = <table> {
 }
 customborder = Frame {
 }
 castColorTexture = NamePlate6PlaterUnitFrameCastBarCastColor {
 }
 TargetName = FontString {
 }
 FrameDownlayer = NamePlate6PlaterUnitFrameCastBarDownlayerFrame {
 }
 _points = <table> {
 }
 interruptSpellId = 116705
 flashTexture = Texture {
 }
 Text = FontString {
 }
 barTextureMask = MaskTexture {
 }
 WidgetType = "castBar"
 ThrottleUpdate = -1
 background = Texture {
 }
}
(temporary) = 2
(temporary) = nil
(temporary) = 116705
(temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
noKickReadyColor = "gray"

**Comment by Meorawr** [comment]
Not a Blizzard issue.

**Comment by kitethrow** [comment]
Where can I post this for help?

**Comment by Meorawr** [comment]
Broadly; https://github.com/Tercioo/Plater-Nameplates and https://github.com/Tercioo/Details-Damage-Meter.

That said - given the issue persists across a reinstall and the leading "Constructor for Interrupt not ready Cast Co..." in the error output you've posted, I'd likely assume there's some custom mod you've got stored in Plater that's causing the issue - so odds are the advice they'll give is to go to the "Plater Modding" tab and disable things there.

**Comment by kitethrow** [comment]
Thank you!
