### ISSUE TITLE
Fire Breath Not showing Cooldown

### ISSUE THREAD

**Issue by Oelenor** [Stanzilla/WoWUIBugs#670]
very self explanatory. When Fire Breath for Evoker is placed on Button Forge button bars, it does not always show the cooldown on it visually, so you don't know when you can use it again.

**Comment by Oelenor** [comment]
I am Chronowarden Preservation, I seem to notice the issue the most with this spec and hero traits

**Comment by Oelenor** [comment]
I also find that if I set my spec, exit the game entirely, relaunch the game, Button Forge will then show the cooldown for that instance.

**Comment by Meorawr** [comment]
This just sounds like an issue with ButtonForge specifically.
