### ISSUE TITLE
Please fire the SPELL_DISPEL event (or similar) when the dungeon affix is dispelled

### ISSUE THREAD

**Issue by JuicyJuuce** [Stanzilla/WoWUIBugs#672]
Last week the mythic dungeon affix was Xal'atath's Bargain: Devour. This periodically puts a heal absorb on all five party members that can either be healed through or dispelled. It counts as magic, curse, poison, and disease so most classes have a way of helping dispel the debuff. However, it seems that dispelling the it doesn't fire the SPELL_DISPEL event.

For the average user, the means that they can't use addons like "Details!" to track who is helping dispel.

(I also posted about this in the forums: https://us.forums.blizzard.com/en/wow/t/please-fire-the-spelldispel-event-when-this-weeks-affix-is-dispelled/1981483)

**Comment by funkydude** [comment]
This is a game data issue not a UI issue.

**Comment by JuicyJuuce** [comment]
Is there a better place to report this issue? I posted on the WoW forums (see linked thread) and was directed here.
