### ISSUE TITLE
[Button Forge] Cooldown timer is not working for Voidwraith - disci priest hero talent

### ISSUE THREAD

**Issue by Przemohawryl** [Stanzilla/WoWUIBugs#675]
As in title, when you used skill Voidwraith, then no timer for cooldown is visible

**Comment by funkydude** [comment]
This is not the Button Forge bug tracker. Who linked you to this website?

**Comment by Dairyman** [comment]
[ButtonForge](https://legacy.curseforge.com/wow/addons/button-forge) has this right at the top of their description:
```
Known Issues for Dragonflight (10.0)

    Spell flyouts are not working  Flyouts will now work on ButtonForge via a custom implementation to work around the issue
    Bug Report: https://github.com/Stanzilla/WoWUIBugs/issues/302
```
🤷
