### ISSUE TITLE
[Retail] Guild news scroll list repeatedly add data cause loading issue

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#683]
`QueryGuildNews()` requests an update of guild news during login and loading screen.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/AddOns/Blizzard_Communities/GuildNews.lua#L51

```
function CommunitiesGuildNewsFrame_OnEvent(self, event)
	if event == "PLAYER_ENTERING_WORLD" then
		QueryGuildNews();
	else
		if ( self:IsShown() ) then
			CommunitiesGuildNews_Update(self);
		end
	end
end
```

This causes `GUILD_NEWS_UPDATE` to be triggered excessively to updating the guild news scroll list, a positive correlation between the event trigger counts and the number of guild news entries, and **each guild news entry causes the list to be cleared and then re-added once.**

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/AddOns/Blizzard_Communities/GuildNews.lua#L84

```
for index = 1, GetNumGuildNews() do
	dataProvider:Insert({index=index, news=true});
end
self.ScrollBox:SetDataProvider(dataProvider);
```

For example, if a guild over 100 people online throughout the year and members running old instances usually, can have more than 5,000 guild news entry at any given time, fired `GUILD_NEWS_UPDATE` thoundens times to refresh guild news list. The combination of these factors results in the guild news repeatedly adding data up to ***several millions times*** during each loading screen.

To temp fix, there are 2 ways:

1. Disable all guild news: `GUILD_NEWS_UPDATE` still triggered but won't update guild news scroll list.
2. Temp fix code from original post :

```
local BLZCommunitiesGuildNewsFrame_OnEvent = CommunitiesGuildNewsFrame_OnEvent
local newsRequireUpdate, newsTimer
CommunitiesFrameGuildDetailsFrameNews:SetScript("OnEvent", function(frame, event)
    if event == "GUILD_NEWS_UPDATE" then
        if newsTimer then
            newsRequireUpdate = true
        else
            BLZCommunitiesGuildNewsFrame_OnEvent(frame, event)
            
            newsTimer = C_Timer.NewTimer(1, function()
                if newsRequireUpdate then
                    BLZCommunitiesGuildNewsFrame_OnEvent(frame, event)
                end
                newsTimer = nil
            end)
        end
    else
        BLZCommunitiesGuildNewsFrame_OnEvent(frame, event)
    end
end)
```

original post on anthor forum by @Sanluli36li
https://bbs.nga.cn/read.php?tid=42399961
issue feedback on reddit
https://www.reddit.com/r/wow/comments/1gnc0k0/help_needed_game_window_freeze_entering_new_area/
https://www.reddit.com/r/wow/comments/1f34paa/loading_screen_time/
issue feedback on official forum
https://eu.forums.blizzard.com/en/wow/t/freezing-after-a-loading-screen-recent-bug/548251
https://eu.forums.blizzard.com/en/wow/t/5-10-seconds-freeze-after-loading-screen/548390

**Comment by EKE00372** [comment]
The conditional check `self:IsShown()` in `CommunitiesGuildNewsFrame_OnEvent` doesn't actually serve any purpose because this frame is Shown by default. It's hide by default and load when open guild frame before BFA, but changed when new community system replaced old guild frame.

After the revamp to the Guild Frame which merge it into Community Frame in BfA, the Guild News Frame `GuildNewsFrame` become frame template `CommunitiesGuildNewsFrameTemplate`. The new frame template is no longer hidden at load or in any case, as it's become sub-frame of frame template `GuildDetailsFrameTemplate` which become tab currectly and will be show or hidden.

This makes the code `if ( self:IsShown() ) then` in event script handler of `CommunitiesGuildNewsFrameTemplate` always return true. The handler updates the news scroll frame every time `GUILD_NEWS_UPDATE` fires, regardless the news frame is visible or not.

In TWW, the event `GUILD_NEWS_UPDATE` will fire 2000 times on in a big guild which has 7000 guild news, which makes the game frozen after login or changing zone.

Legion:
https://github.com/Gethe/wow-ui-source/blob/4657dad9560ca6bc811b6ff0365603d6f1c1dd0e/AddOns/Blizzard_GuildUI/Blizzard_GuildNews.xml#L41
Since BFA:
https://github.com/Gethe/wow-ui-source/blob/02905451beb5cd7a8ef69a4c905e34af2c1e4d0e/Interface/AddOns/Blizzard_Communities/GuildNews.xml#L255

**Comment by EKE00372** [comment]
`/run local l = GetNumGuildNews() local e = ceil(l / 2) for i = 1, e do CommunitiesGuildNewsFrame_OnEvent(CommunitiesFrameGuildDetailsFrameNews) end`

When the guild news exceeds 2,000 entries, running this macro causes client freeze more than 5 sec.

`/run hooksecurefunc(C_GuildInfo, 'GetGuildNewsInfo', function(i) print('GetGuildNewsInfo', i) end)`

After hooking the function and test, it appears that it's not a full update; perhaps it doesn't reach the 'millions of times' mentioned in the original text, but the number of times is still enough to cause loading issue, possible **how many times `GUILD_NEWS_UPDATE` be triggered** x **18 (where the number of guild news entrieds displayed at one time in guild frame)**.

**Comment by Sanluli36li** [comment]
> `/run local l = GetNumGuildNews() local e = ceil(l / 2) for i = 1, e do CommunitiesGuildNewsFrame_OnEvent(CommunitiesFrameGuildDetailsFrameNews) end`
> 
> When the guild news exceeds 2,000 entries, running this macro causes client freeze more than 5 sec.
> 
> `/run hooksecurefunc(C_GuildInfo, 'GetGuildNewsInfo', function(i) print('GetGuildNewsInfo', i) end)`
> 
> After hooking the function and test, it appears that it's not a full update; perhaps it doesn't reach the 'millions of times' mentioned in the original text, but the number of times is still enough to cause loading issue, possible **how many times `GUILD_NEWS_UPDATE` be triggered** x **18 (where the number of guild news entrieds displayed at one time in guild frame)**.

Actually my test is not very rigorous, but now I think the source of the lag is to continuously create empty tables and fill them, rather than the behavior of `self.ScrollBox:SetDataProvider(dataProvider)` that I mentioned earlier

If you only open a few filters with less content, the freeze will not occur, but a large number of events will still occur

But none of this matters. The key is this series of accidentally triggered `GUILD_NEWS_UPDATE`, which is supposed to be triggered only once

**Comment by Meorawr** [comment]
I believe an attempt was made to resolve this in 11.0.7.57637; specifically the OnEvent handler now checks if the frame is visible rather than shown.
