### ISSUE TITLE
Version Attribute for XML Templates

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#69]
This feature request is to add a "version" attribute (as a non-negative integer) to XML template declarations which, if present and greater than any existing version associated with a template, will make the game silently replace the existing template and not raise a Lua warning.

In patch 8.0 a change was made where declarations of XML templates whose names conflict with already existing ones would raise a warning such as the following:

```
Message: Deferred XML Node object named LibMeow_UnicornTemplate already exists
```

The problem the change caused is that our ecosystem involves a system of embedded libraries where (often duplicated) copies of libraries are placed inside each addon and are loaded, a version check occurs, and things are upgraded seamlessly.

For libraries that embedded templates, this change meant that we'd get script errors raised whenever two addons loaded the same library. Addon authors generally request that users of addons run with script errors enabled so that we can fix bugs in our code, and users typically don't like receiving errors.

The solution that followed was for libraries to stop shipping templates and instead require code changes for authors to implement since users receiving Lua warnings - which to them look like standard errors - wasn't desirable. As an example of two cases:

* [LibUIDropDownMenu](https://www.wowace.com/projects/libuidropdownmenu/pages/faq/changes-regarding-to-dropdown-templates-usage)
* [MSA-DropDownMenu](https://www.curseforge.com/wow/addons/msa-dropdownmenu-10/pages/documentation)

The warning itself is technically correct and desirable in _some_ cases. If an addon loaded an older version of a library after a newer version had brought in a template which was changed between the two versions, the old version would replace the new by virtue of being loaded last. This can be avoided with extreme care but is quite difficult.

However to solve this in a way that's more generally useful for addon developers, what I'd like to propose is the addition of a "version" attribute which, **if present and greater than any existing version** associated with a duplicate XML template, would make the client **silently replace** the template declaration and not raise the Lua warning. As an example:

```xml
<!-- Addon A loads a library which defines this: -->
<Frame name="LibMeow_UnicornTemplate" virtual="true" version="1"/>

<!-- Addon B loads a newer version of the template, which should silently replace version 1: -->
<Frame name="LibMeow_UnicornTemplate" virtual="true" version="2" useParentScale="true"/>
```

In the case where the order is inverted, such that version 2 is loaded before version 1, we'd expect that the template declaration for version 1 would be **silently ignored** and **not replace the existing template**.

```xml
<!-- Addon A loads a library which brings in the newer version: -->
<Frame name="LibMeow_UnicornTemplate" virtual="true" version="2" useParentScale="true"/>

<!-- Addon B loads an older version, the expectation is this would be silently ignored: -->
<Frame name="LibMeow_UnicornTemplate" virtual="true" version="1"/>

<!-- Addon C loads the same version "2", this should also be silently ignored: -->
<Frame name="LibMeow_UnicornTemplate" virtual="true" version="2"/>
```

In the final case where an addon attempts to replace a template that has no pre-existing "version" attribute, the warning should still be emitted as usual:

```xml
<!-- FrameXML defines a template with no "version "attribute: -->
<Frame name="Blizzard_PonyTemplate" virtual="true"/>

<!-- Addon accidentally replaces a FrameXML template, this should warn as the original had no associated version: -->
<Frame name="Blizzard_PonyTemplate" virtual="true" version="1"/>

<!--Future attempts should continue to warn: -->
<Frame name="Blizzard_PonyTemplate" virtual="true" version="1"/>
```

Templates should only be allowed to declare non-negative version numbers, so any declaration with `version="-1"` need not be supported. This is to permit the internal representation to reserve negative numbers to mark templates without associated version metadata.

**Comment by Meorawr** [comment]
I've changed this proposal from an "override" attribute to a "version" one which I think is more generally useful for the embedded library upgrade case; while templates can be versioned in libraries with care, if we had a dedicated "version" attribute which the client could use to silently ignore and not downgrade templates things would be made much safer and easier in that regard.

**Comment by kemayo** [comment]
A completely different approach here that would largely accomplish the same goals would be to let us make `virtual` frames from lua.

Certainly, I'm mainly using XML to interact with world map data providers, since they require XML template names for easy interaction with the built-in methods. If I could just make those templates from lua, problem solved.

**Comment by Meorawr** [comment]
I'd definitely agree that the ability to create `virtual` and perhaps even custom `intrinsic` frames in Lua would solve a _lot_ of problems and be the most useful thing for everyone, however I think that it could be a much larger ask and would probably need some further forethought.

At its simplest, I could envisage a `CreateFrameTemplate("frameType", "templateName", factoryFunc[, "inherits"])` API that'd invoke the supplied function passing in a frame of the supplied type when the template were instantiated would suit most cases.

```lua
CreateFrameTemplate("Button", "MyAddOn_Template", function(button)
    button:SetSize(200, 32);
    button:SetPoint("CENTER");
end);

-- This would create a Button and invoke the above function to initialize it:
local button = CreateFrame("Button", nil, UIParent, "MyAddOn_Template");
```

Which would be equivalent to the following XML:

```xml
<Button name="MyAddOn_Template" virtual="true">
    <Scripts>
        <OnLoad inherit="prepend">
            self:SetSize(200, 32);
            self:SetPoint("CENTER");
        </OnLoad>
    </Scripts>
</Button>
```

**Comment by Meorawr** [comment]
Closing in favour of #71 per feedback given. Thank you :)
