### ISSUE TITLE
Using edit mode will move the taskbar up a short distance

### ISSUE THREAD

**Issue by ghost** [Stanzilla/WoWUIBugs#691]
After entering the game, if you enter the edit mode, the taskbar will move a little above. This bug has existed for a long time. Although the impact is not great, I hope the official can fix it.

**Comment by ghost** [comment]
This is what it looks like when you first enter the game. Pay attention to the distance between the bottom of the coordinates and the taskbar.
![微信截图_20241204135608](https://github.com/user-attachments/assets/e972898e-0976-44ba-959c-b9d3a90f2469)



When entering edit mode, the taskbar moves up:
![微信截图_20241204135627](https://github.com/user-attachments/assets/6de0d6d7-03da-4021-9d6a-6e39b9206f32)



And it stays like this after you exit edit mode.
![微信截图_20241204135646](https://github.com/user-attachments/assets/0c52f597-db3c-402a-a534-ffe449ca2663)

**Comment by EKE00372** [comment]
this called **ObjectiveTracker**, not taskbar.
