### ISSUE TITLE
The notification message when a friend comes online is in the wrong place

### ISSUE THREAD

**Issue by ghost** [Stanzilla/WoWUIBugs#692]
It seems to be a problem caused by UI scaling, Hope this little problem can be fixed soon.

**Comment by Ketho** [comment]
Hope you can elaborate a little bit with screenshots and the relevant UI scale

**Comment by ghost** [comment]
I set the UI scaling to 68%, I don't know if it has anything to do with this
![12314](https://github.com/user-attachments/assets/95197957-7c24-4163-8cba-bcf7c3c19701)
