### ISSUE TITLE
SPELL_AURA_REFRESH missing on stacking auras in COMBAT_LOG_EVENT

### ISSUE THREAD

**Issue by d87** [Stanzilla/WoWUIBugs#70]
When you reach a maximum stack count for an aura, combat log doesn't show any subsequent refresh/applied dose events
Present on both live and classic. Example spells: Sunder Armor on classic, Agony on live

So wIth Sunder it goes like
_SPELL_AURA_APPLIED_
_SPELL_AURA_APPLIED_DOSE_ x4
Then nothing until it fades

**Comment by Aviana** [comment]
This has been fixed for TBC with beta build 38401.

**Comment by d87** [comment]
Also has been fixed on 9.1 PTR.
