### ISSUE TITLE
CreateFrameTemplate API

### ISSUE THREAD

**Issue by Meorawr** [Stanzilla/WoWUIBugs#71]
This request is aimed at providing an API function that allows for the creation of new virtual frame templates from within Lua. 

The aim of this proposal is to solve a longstanding pain point in the existing environment where FrameXML utilities and systems such as frame pools, map data providers, hybrid scroll frames, and a growing list of other items have generally tended towards being easier to use when supplied XML templates instead of Lua-based factory functions.

We are also with this proposal aiming to solve a case where the definition of XML templates is actually flat-out impossible, namely within embedded libraries. Libraries can't bring templates with them because there's no way to control whether or not a template is conditionally made available based on version metadata. This was discussed in more depth in #69.

Note that this proposal as-is is likely _not_ suitable for cases where a template would need to inherit from secure protected frame templates. It aims to solve the common case first, and leaves room open for an alternative solution to be found for those if desirable.

---

The API as proposed would have the following signature, following the existing `CreateFrame` API very closely:

```lua
CreateFrameTemplate("frameType", "templateName", onLoadFunc[, "inherits"])
```

The arguments are as follows:

* `frameType` (string) - The frame object type this template is being defined for.
* `templateName` (string) - The name of the template to be created.
* `onLoadFunc` (function) - A function to be installed as the OnLoad script handler for this template. The script handler will inherit any existing OnLoad script handlers, as if by use of the `inherit="prepend"` XML attribute.
* `inherits` (string, optional) - A comma-delimited list of templates to inherit, as already provided by `CreateFrame`.

This function would have no return values. The named template will be readily available for use upon return of the function and **must** be usable within subsequent calls to the `CreateFrame` API immediately after, or from within any `inherits` attributes in following XML fragments. To facilitate checking if a template exists, the existing `DoesTemplateExist` function **must** return true for templates created via this API function.

Aside from standard argument type-checking, an error condition should be raised if any of the following is true:

* The caller supplies an invalid or unknown frame type.
* The caller attempts to create a template whose name conflicts with an already existing template.

An example of its usage is given below, where we create a new `Button` template named "MyAddOn_ButtonTemplate", we give it an OnLoad script handler (which will inherit any existing one as if `inherit="prepends"`), and inherits a pre-existing FrameXML template.

```lua
function Button_OnLoad(self)
    self:SetPoint("CENTER");
    self:SetText("Hello!");
end

CreateFrameTemplate("Button", "MyAddOn_ButtonTemplate", Button_OnLoad, "UIPanelButtonTemplate");
```

This would be directly equivalent to the following XML:

```xml
<Button name="MyAddOn_ButtonTemplate" virtual="true" inherits="UIPanelButtonTemplate">
    <Scripts>
        <OnLoad inherit="prepend">
            self:SetPoint("CENTER");
            self:SetText("Hello!");
        </Onload>
    </Scripts>
</Button>
```

The button could then be instantiated as normal either from the Lua `CreateFrame` API or in XML immediately after having been defined:

```lua
CreateFrame("Button", "TestButton1", UIParent, "MyAddOn_ButtonTemplate");
```

```xml
<Button name="TestButton1" parent="UIParent" inherits="MyAddOn_ButtonTemplate"/>
```

---

A more complex proposal could be considered whereby the new API function could return a _virtual frame handle_, allowing the calling code to then set frame attributes like size and positioning, install script handlers, create further children, and finally freeze it. The advantages this would have is we envisage it could be used with frames inheriting from secure frame templates, however it's likely that this would be a far more complex option. This could nevertheless be considered as a future extension or a separate API entirely.

**Comment by kemayo** [comment]
Since your proposal maintains the "can't redefine a template" behavior, what're you envisioning for the library-upgrade use case?

Thinking about it, I guess that approximately the following would work...

```lua
local template_name = "MyLibraryTemplate17" -- incremented as-needed
if not DoesTemplateExist(template_name) then
    -- create it
end
-- just use template_name from here onwards, rather than a string-literal reference to it
local myframe = CreateFrame("Button", nil, nil, template_name)
```

**Comment by Meorawr** [comment]
Yeah, I'd mentioned that this needs to work with `DoesTemplateExist` so that we can check if a template is already defined. An example I'd imagine with LibStub to handle the versioning of the factory would be something like:

```lua
local LibFoo = LibStub:NewLibrary("LibFoo-1.0", 1);

function LibFoo:InitFrame(frame)
    frame:SetSize(200, 20);
end

if not DoesTemplateExist("LibFoo_Template") then
    CreateFrameTemplate("Frame", "LibFoo_Template", function(self)
        LibFoo:InitFrame(self);
    end);
end
```

If you needed to make some incompatible change to the template (perhaps you wanted `InitFrame` to no longer include a child called `NameText`) then you'd likely do so by representing that with a different template name.
