### ISSUE TITLE
All forms of SetTexture API need fileID support

### ISSUE THREAD

**Issue by funkydude** [Stanzilla/WoWUIBugs#8]
Any and every form of widget API that sets a texture needs to be updated to support fileIDs, many currently don't.

This has been acknowledged by Blizzard as an issue and is being tracked internally. They have confirmed that they are looking at it from the C++ side so hopefully no obscure references are missed.

**After it is confirmed to us that this work is done**, we can create a checklist and start verifying each known API call. Doing so before that would be a waste of time.

Works with fileIDs

- 1
- 2

Needs updated to work with fileIDs

- 1
- 2

**Comment by Stanzilla** [comment]
As of 30669

```
[00:29:22] TSquare: FYI - we did make a bunch more functions use file ID (as well as path)
[00:29:49] TSquare: ReplaceIconTexture
[00:29:49] TSquare: SetThumbTexture
[00:29:49] TSquare: SetStatusBarTexture
[00:29:49] TSquare: PlaySoundFile
[00:29:49] TSquare: SetBorderTexture
[00:29:50] TSquare: SetSwipeTexture
[00:29:52] TSquare: SetEdgeTexture
[00:29:54] TSquare: SetBlingTexture
[00:29:56] TSquare: SetFogOfWarBackgroundTexture
[00:29:58] TSquare: SetMaskTexture
[00:30:02] TSquare: SetPlayerPingTexture
```

**Comment by MysticalOS** [comment]
Did he elaborate on whether or not this applies to classic as well? Those of us maintaining version of mods for both need to know if making changes for 8.2 will break them for classic.

**Comment by Ketho** [comment]
I'm not familiar with the widget API but do look through https://wow.gamepedia.com/Widget_API for any functions that still need to be updated

**Comment by Ketho** [comment]
I'm a bit late with this, but `SetBackdrop`  and `SetHighlightTexture` don't seem to be updated yet from the ones mentioned on IRC

**Comment by funkydude** [comment]
@Ketho `SetBackdrop` is known. They've said they plan on retiring it eventually so it probably won't be updated.

`SetHighlightTexture` works right now on live, at least on buttons.
