### ISSUE TITLE
TBC: FrameXML\RestrictedExecution.lua:473: Cannot call restricted closure from insecure code

### ISSUE THREAD

**Issue by siweia** [Stanzilla/WoWUIBugs#80]
`frame:Execute([[
		buttons = table.new()
		for i = 1, 12 do
			tinsert(buttons, self:GetFrameRef("ActionButton"..i))
		end
	]])`

This error popups out when you have actionbar code written as above.

**Comment by Meorawr** [comment]
Closing as duplicate of #66.
