### ISSUE TITLE
TBC: IsFlying/IsFlyableArea is missing

### ISSUE THREAD

**Issue by shooter-z** [Stanzilla/WoWUIBugs#81]
IsFlying() does not exist, as of build 2.5.1 38169

**Comment by Meorawr** [comment]
Presumably this will also affect [IsFlyableArea](https://wowpedia.fandom.com/wiki/API_IsFlyableArea) and the [flyable/flying](https://wowpedia.fandom.com/wiki/Macro_conditionals#Boolean_Conditions) macro conditionals.

**Comment by shooter-z** [comment]
IsFlying has been added.
IsFlyableArea still missing.

**Comment by mrbuds** [comment]
This is still true with version 2.5.1.38285

**Comment by Ketho** [comment]
[Added](https://github.com/Ketho/BlizzardInterfaceResources/commit/d22a88fcc7f6347655f1a6ba46c7cd37f3374703#diff-ca64e26bbd77a0dd7b6d3699c75cbf60dd7ac03e379b8085dd7efcca4a52510eR1814) in 2.5.1 (38548)
