### ISSUE TITLE
Classic: Typo's in FrameXML\SecureHandlers.lua

### ISSUE THREAD

**Issue by Luckyone961** [Stanzilla/WoWUIBugs#84]
Line 619: MakeForbbiden is typo'd it's supposed to be MakeForbidden
Line 665: MakeForbbiden is typo'd it's supposed to be MakeForbidden

**Comment by Meorawr** [comment]
For TBC this is fixed in 2.5.1.38598.

**Comment by Meorawr** [comment]
This was fixed in Classic Era at err... some point.
