### ISSUE TITLE
TBC: zhCN clinet can not start the client because LocalizeFrames error

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#86]
Happened on 2.5.1.38285
It's an error feedback from other people, when using zhCN localize, they cannot start the client, just freeze with black screen.

error:
`Interface\GlueXML\GlueParent.lua:75: attempt to call global 'LocalizeFrames' (a nil value)`

![image](https://user-images.githubusercontent.com/1412472/114480053-4b455700-9c34-11eb-81fa-368153c6f08f.png)

**Comment by qqytqqyt** [comment]
After dumping the interface Xml files I noticed syntax error in Interface\GlueXML\GlueLocalization.lua file for zhCN locale:

Line 21:

```
classicLogo[LE_EXPANSION_CLASSIC] = {filename = 'Interface\\Glues\\Common\\GLUES-WOW-CLASSICLOGO', uv = { 0, 1, 0, 1 }},
classicLogo[LE_EXPANSION_BURNING_CRUSADE] = {filename = 'Interface\\Glues\\Common\\GLUES-WOW-CLASSICLOGO', uv = { 0, 1, 0, 1 }},
```

where comma was incorrectly used to break lines (where it is supposed to be semi-colon or just carriage return). I suspect this was the cause of the issue.

The interface GlueXml files in other languages don’t have the issue.

**Comment by EKE00372** [comment]
fixed by patch 38339 just pushed
