### ISSUE TITLE
Crash when loading tons of textures(?)

### ISSUE THREAD

**Issue by Stanzilla** [Stanzilla/WoWUIBugs#9]
Reported by @Justw8 and also reproduced by me. Reported to Crosshash on May 17th with a link to SavedVariables that repo it and a matching WeakAuras version

Crash: https://i.imgur.com/LTdr9fi.png
WA Version: https://www.wowace.com/projects/weakauras-2/files/2711904
SavedVariables: https://www.dropbox.com/s/cdicwef5pbzd2tk/WeakAuras.zip?dl=0

**Comment by InfusOnWoW** [comment]
That looks like something to do with loading the right font. And apparently the code is asserting that the font could either be:
* Not loaded
* Has the requested pixel size.

I think there's nothing we can except report that to Blizzard.

It might be font specific though, so try suggesting switching all fonts to Fritz to Justwait

**Comment by InfusOnWoW** [comment]
It might be easier if he ensured that he has no custom fonts anywhere, so that they cannot be loaded. :)

**Comment by Justw8** [comment]
https://streamable.com/vkk83
Don't have any fonts folder of some kind.

**Comment by Ketho** [comment]
Was this fixed? I can't reproduce it anymore with `2.12.4-beta2-2-g03f556b` and the latest version

**Comment by mooreatv** [comment]
update the title to something font related (as you can make hundreds of thousands of textures and get no crash)
