### ISSUE TITLE
ColorMixin does not round hex values

### ISSUE THREAD

**Issue by Ketho** [Stanzilla/WoWUIBugs#98]
This is a very minor issue but the hex string for class colors is not rounded.
https://github.com/Gethe/wow-ui-source/blob/9.0.5/SharedXML/Color.lua#L47
```lua
/dump RAID_CLASS_COLORS.PRIEST:GenerateHexColor():upper() -- returns "FFFEFEFE" instead of "FFFFFFFF"
```
Partly related to [C_ClassColor.GetClassColor()](https://wowpedia.fandom.com/wiki/API_C_ClassColor.GetClassColor) having floating-point issues.

![](https://user-images.githubusercontent.com/1073877/114780469-bb102a80-9d77-11eb-882b-ab703a6d74b0.png)

**Comment by zealvurte** [comment]
@Ketho, I noticed you marked this at not planned, but it was already fixed in https://github.com/Gethe/wow-ui-source/commit/f0084386950fe3dc31a1d61de33b364e268cf66b, no?

**Comment by Ketho** [comment]
Sorry, that's what I get for lazily assuming they never fixed it. But happy they did.
